<?php
if(!isset($userId))return;$vbProactiveTripId=(int)($_GET['id']??($tripId??0));if($vbProactiveTripId<1)return;
try{$vbProactiveService=new ProactiveTravelService(db());if(!$vbProactiveService->ready())return;$vbProactive=$vbProactiveService->assessTrip((int)$userId,$vbProactiveTripId,true,'worker');$vbProactiveIssues=array_slice((array)($vbProactive['issues']??[]),0,3);}catch(Throwable $e){error_log('Proactive trip panel failed: '.$e->getMessage());return;}
?>
<section class="dashboard vb-proactive-panel"><div class="shell"><div class="dashboard-card">
  <div class="vb-proactive-panel-head"><div><span class="eyebrow">Proactive Vacation Brain</span><h2>What needs attention before you ask?</h2><p class="muted">Saved live data, readiness, itinerary timing and traveler signals are continuously reconciled into approval-safe Next Moves.</p></div><div class="vb-proactive-panel-stat"><strong><?=(int)($vbProactive['risk_score']??0)?></strong><span><?=e((string)($vbProactive['risk_label']??'Under control'))?></span></div></div>
  <?php if(!$vbProactiveIssues):?><div class="vb-proactive-empty"><strong>No meaningful issue is open.</strong> Current saved data looks calm.</div><?php else:?><div class="vb-proactive-panel-list"><?php foreach($vbProactiveIssues as $issue):?><a href="<?=e(app_url('proactive-trip.php?id='.$vbProactiveTripId.'#issue-'.(int)$issue['id']))?>"><span><?=e(ucfirst((string)$issue['severity']))?> · <?=e(ucfirst((string)$issue['source_state']))?></span><strong><?=e((string)$issue['title'])?></strong><small><?=e((string)$issue['body'])?></small></a><?php endforeach;?></div><?php endif;?>
  <div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:14px"><a class="button primary small" href="<?=e(app_url('proactive-trip.php?id='.$vbProactiveTripId))?>">Open proactive trip view</a><a class="button secondary small" href="<?=e(app_url('proactive-settings.php'))?>">Settings</a></div>
</div></div></section>
