<?php
declare(strict_types=1);

final class TripMemoryService
{
    private const SIGNALS=['relaxation'=>'Relaxation','adventure'=>'Adventure','food'=>'Food & dining','nightlife'=>'Nightlife','culture'=>'Culture & history','beach'=>'Beach','pool'=>'Pool','luxury'=>'Luxury','budget_sensitivity'=>'Value / budget','resort_preference'=>'Resorts','city_preference'=>'City energy','romance'=>'Romance','activity_level'=>'Activities','spontaneity'=>'Spontaneity','convenience'=>'Convenience','morning_tolerance'=>'Early mornings','direct_flight_preference'=>'Direct flights'];
    private const TERMS=['relaxation'=>['relax','spa','beach','resort','slow','quiet'],'adventure'=>['adventure','hiking','outdoor','excursion','mountain','nature'],'food'=>['food','dining','restaurant','culinary','market'],'nightlife'=>['nightlife','night','bars','clubs','late','music'],'culture'=>['culture','history','museum','architecture','art'],'beach'=>['beach','ocean','coast','island','seaside','tropical'],'pool'=>['pool','cabana','resort'],'luxury'=>['luxury','premium','upscale','resort','spa'],'budget_sensitivity'=>['budget','value','affordable','deal'],'resort_preference'=>['resort','all-inclusive','spa','pool'],'city_preference'=>['city','urban','neighborhood','downtown','nightlife','culture'],'romance'=>['romantic','romance','sunset','wine'],'activity_level'=>['activity','adventure','hiking','tour','excursion'],'spontaneity'=>['flexible','spontaneous','easy','open-ended'],'convenience'=>['easy','direct','walkable','convenient','central'],'morning_tolerance'=>['sunrise','morning','early'],'direct_flight_preference'=>['direct flight','nonstop','non-stop']];

    public function __construct(private PDO $pdo) {}
    public function ready(): bool{return db_table_exists('trip_memories')&&db_table_exists('trip_memory_signals')&&db_table_exists('trip_memory_items');}
    public function signalCatalog(): array{return self::SIGNALS;}

    public function snapshot(int $userId,int $tripId): array
    {
        if($userId<1||$tripId<1)throw new InvalidArgumentException('Trip is required.');
        $trip=(new DreamService($this->pdo))->get($userId,$tripId,false);if(!$trip)throw new OutOfBoundsException('Trip not found.');
        $memory=$this->memoryRow($userId,$tripId);$signals=[];$feedback=[];
        if($this->ready()){
            $q=$this->pdo->prepare('SELECT signal_key,signal_value FROM trip_memory_signals WHERE user_id=? AND dream_trip_id=?');$q->execute([$userId,$tripId]);foreach($q->fetchAll()?:[] as $r)$signals[(string)$r['signal_key']]=(int)$r['signal_value'];
            $q=$this->pdo->prepare('SELECT source_kind,source_id,rating,sentiment,note FROM trip_memory_items WHERE user_id=? AND dream_trip_id=?');$q->execute([$userId,$tripId]);foreach($q->fetchAll()?:[] as $r)$feedback[(string)$r['source_kind'].':'.(int)$r['source_id']]=$r;
        }
        return ['ready'=>$this->ready(),'eligible'=>$this->eligible($trip),'trip'=>$trip,'memory'=>$memory,'stats'=>$this->tripStats($userId,$trip),'signals'=>$signals,'signal_catalog'=>self::SIGNALS,'items'=>$this->itemCandidates($userId,$trip,$feedback),'learning'=>$this->learningSummary($userId),'privacy_note'=>'Private notes stay inside Trip Memory. Only structured ratings and preference signals can influence recommendations when learning is enabled.'];
    }

    public function save(int $userId,int $tripId,array $input,bool $complete=false): array
    {
        if(!$this->ready())throw new RuntimeException('Run System Upgrade for Post-Trip Memory.');
        $trip=(new DreamService($this->pdo))->get($userId,$tripId,false);if(!$trip)throw new OutOfBoundsException('Trip not found.');if(!$this->eligible($trip))throw new InvalidArgumentException('Trip Memory opens after the trip is completed.');
        $before=$this->memoryRow($userId,$tripId);$status=$complete||(($before['status']??'')==='complete')?'complete':'draft';
        $overall=$this->rating($input['overall_rating']??null);$value=$this->rating($input['value_rating']??null);if($complete&&$overall===null)throw new InvalidArgumentException('Add an overall trip rating before completing Trip Memory.');
        $pace=in_array((string)($input['pace_fit']??''),['too_slow','just_right','too_packed'],true)?(string)$input['pace_fit']:null;$return=in_array((string)($input['would_return']??''),['yes','maybe','no'],true)?(string)$input['would_return']:null;
        $actual=$this->money($input['actual_spend']??null);$currency=$this->currency((string)($input['currency']??($trip['currency']??'USD')));$stats=$this->tripStats($userId,$trip);$booked=$stats['booked_spend_by_currency'][$currency]??null;
        $summary=$this->clip((string)($input['summary_text']??''),1400);$private=$this->clip((string)($input['private_notes']??''),8000);$favorite=$this->clip((string)($input['favorite_moment']??''),700);$miss=$this->clip((string)($input['biggest_miss']??''),700);$learn=!empty($input['learning_enabled'])?1:0;
        $this->pdo->beginTransaction();
        try{
            $sql='INSERT INTO trip_memories (user_id,dream_trip_id,destination_catalog_id,status,overall_rating,value_rating,pace_fit,would_return,target_budget_snapshot,booked_spend_snapshot,actual_spend,currency,summary_text,private_notes,favorite_moment,biggest_miss,learning_enabled,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,IF(?=\'complete\',NOW(),NULL)) ON DUPLICATE KEY UPDATE destination_catalog_id=VALUES(destination_catalog_id),status=VALUES(status),overall_rating=VALUES(overall_rating),value_rating=VALUES(value_rating),pace_fit=VALUES(pace_fit),would_return=VALUES(would_return),target_budget_snapshot=VALUES(target_budget_snapshot),booked_spend_snapshot=VALUES(booked_spend_snapshot),actual_spend=VALUES(actual_spend),currency=VALUES(currency),summary_text=VALUES(summary_text),private_notes=VALUES(private_notes),favorite_moment=VALUES(favorite_moment),biggest_miss=VALUES(biggest_miss),learning_enabled=VALUES(learning_enabled),completed_at=IF(VALUES(status)=\'complete\',COALESCE(completed_at,NOW()),NULL),updated_at=NOW()';
            $this->pdo->prepare($sql)->execute([$userId,$tripId,$trip['destination_catalog_id']??null,$status,$overall,$value,$pace,$return,$trip['target_budget']??null,$booked,$actual,$currency,$summary?:null,$private?:null,$favorite?:null,$miss?:null,$learn,$status]);
            $sig=$this->pdo->prepare('INSERT INTO trip_memory_signals (user_id,dream_trip_id,signal_key,signal_value) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE signal_value=VALUES(signal_value),updated_at=NOW()');foreach(self::SIGNALS as $key=>$label){if(array_key_exists('signal_'.$key,$input))$sig->execute([$userId,$tripId,$key,max(-2,min(2,(int)$input['signal_'.$key]))]);}
            $allowed=[];foreach($this->itemCandidates($userId,$trip,[]) as $i)$allowed[(string)$i['source_key']]=$i;$sent=is_array($input['item_sentiment']??null)?$input['item_sentiment']:[];$ratings=is_array($input['item_rating']??null)?$input['item_rating']:[];$notes=is_array($input['item_note']??null)?$input['item_note']:[];
            $item=$this->pdo->prepare('INSERT INTO trip_memory_items (user_id,dream_trip_id,source_kind,source_id,item_type,title,rating,sentiment,note) VALUES (?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE item_type=VALUES(item_type),title=VALUES(title),rating=VALUES(rating),sentiment=VALUES(sentiment),note=VALUES(note),updated_at=NOW()');
            foreach($allowed as $key=>$i){$s=(string)($sent[$key]??'neutral');if(!in_array($s,['favorite','good','neutral','skip'],true))$s='neutral';$item->execute([$userId,$tripId,$i['source_kind'],$i['source_id'],$i['item_type'],$i['title'],$this->rating($ratings[$key]??null),$s,$this->clip((string)($notes[$key]??''),500)?:null]);}
            if($status==='complete'){
                if(db_column_exists('dream_trips','operational_state'))$this->pdo->prepare("UPDATE dream_trips SET status='completed',operational_state='completed',travel_mode_completed_at=COALESCE(travel_mode_completed_at,NOW()),updated_at=NOW() WHERE id=? AND user_id=?")->execute([$tripId,$userId]);else $this->pdo->prepare("UPDATE dream_trips SET status='completed',updated_at=NOW() WHERE id=? AND user_id=?")->execute([$tripId,$userId]);
                if($complete&&($before['status']??'')!=='complete')$this->pdo->prepare('INSERT INTO user_events (user_id,event_type,dream_trip_id,value_numeric,value_text) VALUES (?,"trip_memory_completed",?,?,?)')->execute([$userId,$tripId,$overall,(string)($trip['destination_name']??$trip['name'])]);
            }
            $this->pdo->commit();
        }catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}
        return $this->snapshot($userId,$tripId);
    }

    public function learningSignals(int $userId): array
    {
        if(!$this->ready())return [];$q=$this->pdo->prepare('SELECT s.signal_key,AVG(s.signal_value) avg_value,COUNT(*) samples FROM trip_memory_signals s JOIN trip_memories m ON m.user_id=s.user_id AND m.dream_trip_id=s.dream_trip_id WHERE s.user_id=? AND m.status="complete" AND m.learning_enabled=1 GROUP BY s.signal_key');$q->execute([$userId]);$out=[];foreach($q->fetchAll()?:[] as $r){$key=(string)$r['signal_key'];if(isset(self::SIGNALS[$key]))$out[$key]=['key'=>$key,'label'=>self::SIGNALS[$key],'value'=>(float)$r['avg_value'],'samples'=>(int)$r['samples']];}return $out;
    }

    public function augmentTraits(int $userId,array $traits): array
    {
        foreach($this->learningSignals($userId) as $key=>$s){$delta=max(-15,min(15,(float)$s['value']*7.5));if(isset($traits[$key])){$traits[$key]['score']=max(0,min(100,(float)($traits[$key]['score']??50)+$delta));$traits[$key]['confidence']=max((float)($traits[$key]['confidence']??0),min(90,45+$s['samples']*10));$traits[$key]['trip_learning_delta']=$delta;$traits[$key]['trip_learning_count']=$s['samples'];}else $traits[$key]=['slug'=>$key,'name'=>$s['label'],'trait_group'=>'post_trip','score'=>max(0,min(100,50+$delta)),'confidence'=>min(90,45+$s['samples']*10),'interaction_count'=>$s['samples'],'trip_learning_delta'=>$delta,'trip_learning_count'=>$s['samples']];}return $traits;
    }

    public function rerankDestinations(int $userId,array $rows): array
    {
        $signals=$this->learningSignals($userId);if(!$signals)return $rows;foreach($rows as &$r){$hay=strtolower(implode(' ',[(string)($r['name']??''),(string)($r['short_description']??''),(string)($r['description']??''),(string)($r['best_for']??''),(string)($r['vibe']??''),(string)($r['prompt_summary']??''),(string)($r['visual_keywords_json']??''),(string)($r['activity_keywords_json']??'')]));$score=0;$why=[];$avoid=[];foreach($signals as $key=>$s){$v=(float)$s['value'];if(abs($v)<.5)continue;$hits=0;foreach(self::TERMS[$key]??[] as $term)if(str_contains($hay,$term))$hits++;if(!$hits)continue;$score+=$v*(1+min(2,$hits)*.45);if($v>=.75)$why[]='Trip memory: '.$s['label'];elseif($v<=-.75)$avoid[]=$s['label'];}$r['_memory_score']=round($score,3);$r['_recommendation_score']=(float)($r['_recommendation_score']??0)+$score;$r['_recommendation_reasons']=array_values(array_unique(array_merge((array)($r['_recommendation_reasons']??[]),$why)));if($avoid)$r['_memory_cautions']=array_values(array_unique($avoid));}unset($r);usort($rows,fn($a,$b)=>((float)($b['_recommendation_score']??0)<=>(float)($a['_recommendation_score']??0))?:((int)($b['featured']??0)<=>(int)($a['featured']??0)));return $rows;
    }

    public function learningSummary(int $userId): array
    {
        if(!$this->ready())return ['completed_trips'=>0,'average_rating'=>null,'positive'=>[],'negative'=>[],'favorite_types'=>[]];$q=$this->pdo->prepare('SELECT COUNT(*) total,AVG(overall_rating) avg_rating FROM trip_memories WHERE user_id=? AND status="complete"');$q->execute([$userId]);$base=$q->fetch()?:[];$pos=[];$neg=[];foreach($this->learningSignals($userId) as $s){if($s['value']>=.75)$pos[]=$s;elseif($s['value']<=-.75)$neg[]=$s;}usort($pos,fn($a,$b)=>$b['value']<=>$a['value']);usort($neg,fn($a,$b)=>$a['value']<=>$b['value']);$q=$this->pdo->prepare("SELECT item_type,COUNT(*) total,AVG(COALESCE(rating,CASE sentiment WHEN 'favorite' THEN 5 WHEN 'good' THEN 4 ELSE 3 END)) avg_rating FROM trip_memory_items i JOIN trip_memories m ON m.user_id=i.user_id AND m.dream_trip_id=i.dream_trip_id WHERE i.user_id=? AND m.status='complete' AND m.learning_enabled=1 AND i.sentiment IN ('favorite','good') GROUP BY item_type ORDER BY total DESC,avg_rating DESC LIMIT 5");$q->execute([$userId]);return ['completed_trips'=>(int)($base['total']??0),'average_rating'=>$base['avg_rating']!==null?round((float)$base['avg_rating'],1):null,'positive'=>array_slice($pos,0,6),'negative'=>array_slice($neg,0,4),'favorite_types'=>$q->fetchAll()?:[]];
    }

    public function agentContext(int $userId): string
    {
        $s=$this->learningSummary($userId);if(($s['completed_trips']??0)<1)return '';$likes=array_map(fn($x)=>$x['label'],(array)$s['positive']);$avoid=array_map(fn($x)=>$x['label'],(array)$s['negative']);$parts=['Post-trip learning from '.$s['completed_trips'].' completed trip recap'.($s['completed_trips']===1?'':'s')];if($s['average_rating']!==null)$parts[]='average trip rating '.$s['average_rating'].'/5';if($likes)$parts[]='learned preferences: '.implode(', ',$likes);if($avoid)$parts[]='learned avoid/less-of signals: '.implode(', ',$avoid);return implode('; ',$parts).'. Structured preference learning only; private trip notes are excluded.';
    }

    private function memoryRow(int $userId,int $tripId): array{if(!$this->ready())return ['status'=>'none','overall_rating'=>null,'value_rating'=>null,'pace_fit'=>null,'would_return'=>null,'actual_spend'=>null,'currency'=>'USD','summary_text'=>'','private_notes'=>'','favorite_moment'=>'','biggest_miss'=>'','learning_enabled'=>1];$q=$this->pdo->prepare('SELECT * FROM trip_memories WHERE user_id=? AND dream_trip_id=? LIMIT 1');$q->execute([$userId,$tripId]);return $q->fetch()?:['status'=>'none','overall_rating'=>null,'value_rating'=>null,'pace_fit'=>null,'would_return'=>null,'actual_spend'=>null,'currency'=>'USD','summary_text'=>'','private_notes'=>'','favorite_moment'=>'','biggest_miss'=>'','learning_enabled'=>1];}
    private function eligible(array $trip): bool{if(($trip['status']??'')==='completed'||($trip['operational_state']??'')==='completed')return true;$end=trim((string)($trip['end_date']??''));return $end!==''&&$end<date('Y-m-d');}
    private function tripStats(int $userId,array $trip): array{$items=count(is_array($trip['items']??null)?$trip['items']:[]);$all=$confirmed=0;$spend=[];if(db_table_exists('trip_bookings')){$q=$this->pdo->prepare('SELECT status,payment_status,amount,currency FROM trip_bookings WHERE user_id=? AND dream_trip_id=?');$q->execute([$userId,(int)$trip['id']]);foreach($q->fetchAll()?:[] as $r){$all++;if(in_array((string)$r['status'],['booked','confirmed','changed'],true)){$confirmed++;if($r['amount']!==null&&(string)$r['payment_status']!=='refunded'){$c=$this->currency((string)$r['currency']);$spend[$c]=($spend[$c]??0)+(float)$r['amount'];}}}}return ['planned_items'=>$items,'booking_records'=>$all,'confirmed_bookings'=>$confirmed,'planned_budget'=>$trip['target_budget']!==null?(float)$trip['target_budget']:null,'booked_spend_by_currency'=>$spend];}
    private function itemCandidates(int $userId,array $trip,array $feedback): array{$out=[];foreach((array)($trip['items']??[]) as $r){$id=(int)($r['id']??0);if($id){$key='itinerary:'.$id;$out[]=['source_key'=>$key,'source_kind'=>'itinerary','source_id'=>$id,'item_type'=>(string)($r['item_type']??'idea'),'title'=>(string)($r['title']??'Trip item'),'feedback'=>$feedback[$key]??null];}}if(db_table_exists('trip_bookings')){$q=$this->pdo->prepare("SELECT id,booking_type,title FROM trip_bookings WHERE user_id=? AND dream_trip_id=? AND status IN ('booked','confirmed','changed') ORDER BY id");$q->execute([$userId,(int)$trip['id']]);foreach($q->fetchAll()?:[] as $r){$key='booking:'.(int)$r['id'];$out[]=['source_key'=>$key,'source_kind'=>'booking','source_id'=>(int)$r['id'],'item_type'=>(string)$r['booking_type'],'title'=>(string)$r['title'],'feedback'=>$feedback[$key]??null];}}return array_slice($out,0,40);}
    private function rating(mixed $v): ?int{if($v===null||$v==='')return null;$n=(int)$v;if($n<1||$n>5)throw new InvalidArgumentException('Ratings must be from 1 to 5.');return $n;}
    private function money(mixed $v): ?float{if($v===null||trim((string)$v)==='')return null;if(!is_numeric($v))throw new InvalidArgumentException('Actual spend must be a number.');$n=(float)$v;if($n<0||$n>99999999)throw new InvalidArgumentException('Actual spend is outside the supported range.');return round($n,2);}
    private function currency(string $v): string{$v=strtoupper(trim($v));return preg_match('/^[A-Z]{3}$/',$v)?$v:'USD';}
    private function clip(string $v,int $max): string{$v=trim($v);if($v==='')return '';return function_exists('mb_substr')?mb_substr($v,0,$max):substr($v,0,$max);}
}
