<?php
declare(strict_types=1);

/**
 * Budget-Aware Trip Planning + Affordability Intelligence.
 *
 * Forecasts a trip from saved booking values, explicit category plans, saved provider
 * snapshots and (for the owner only) aggregate completed-trip cost history. It never
 * refreshes providers, converts currency, exposes private expense text, or executes a
 * booking/payment/cancellation/refund/provider action.
 */
final class TripAffordabilityService
{
    private const CATEGORIES=[
        'flight'=>'Flights','lodging'=>'Lodging','transport'=>'Transportation','food'=>'Food & dining',
        'activity'=>'Activities','event'=>'Events & tickets','shopping'=>'Shopping','fees'=>'Fees & misc. charges','other'=>'Other',
    ];
    private const OVERRIDE_FIELDS=[
        'flight'=>'flight_override','lodging'=>'lodging_override','transport'=>'transport_override','food'=>'food_override',
        'activity'=>'activity_override','event'=>'event_override','shopping'=>'shopping_override','fees'=>'fees_override',
    ];

    public function __construct(private PDO $pdo) {}

    public function ready(): bool
    {
        return db_table_exists('trip_affordability_settings')
            && db_table_exists('trip_affordability_scenarios')
            && db_table_exists('trip_affordability_events')
            && db_table_exists('trip_cost_category_plans');
    }

    public function snapshot(int $userId,int $tripId): array
    {
        $access=$this->access($userId,$tripId);$trip=$this->trip($tripId);$owner=!empty($access['is_owner']);$canPlan=!empty($access['can_plan']);$role=(string)($access['role']??'viewer');
        if(!$this->ready())return $this->emptySnapshot($trip,$role,$owner,$canPlan);
        if(!$canPlan)return ['ready'=>true,'trip'=>$this->publicTrip($trip),'role'=>$role,'can_view'=>false,'can_manage'=>false,'settings'=>[],'forecast'=>[],'scenarios'=>[],'fit_suggestions'=>[],'privacy_note'=>'Affordability forecasting is available to the trip owner and Co-planner. Traveler and Viewer roles do not receive budget projections.','safety_note'=>$this->safetyNote()];
        $settings=$owner?$this->settings($userId,$tripId):$this->storedSettings((int)$trip['user_id'],$tripId);if(!$owner)$settings['include_learned_history']=0;
        $forecast=$this->forecast($userId,$trip,$settings,$owner,null);
        $scenarios=[];
        if($owner){foreach($this->scenarioRows($userId,$tripId) as $row){$scenario=$this->castScenario($row);$sf=$this->forecast($userId,$trip,$settings,true,$scenario);$sf['scenario_id']=(int)$row['id'];$sf['label']=(string)$row['label'];$sf['estimated_savings']=round(max(0,(float)($forecast['expected_final']??0)-(float)($sf['expected_final']??0)),2);$sf['value_score']=$this->valueScore($sf,$forecast,$scenario);$scenarios[]=$sf;}}
        return ['ready'=>true,'trip'=>$this->publicTrip($trip),'role'=>$role,'can_view'=>true,'can_manage'=>$owner,'settings'=>$owner?$settings:[],'forecast'=>$forecast,'scenarios'=>$scenarios,'fit_suggestions'=>$this->fitSuggestions($forecast),'privacy_note'=>$owner?'Completed-trip learning is reduced to aggregate cost baselines before forecasting. Merchant names, expense notes, Trip Memory narrative, confirmation codes, payment data and disruption evidence are never exposed here or to ordinary agent context.':'This shared forecast uses the owner’s saved forecast policy with learned-history input disabled, plus role-appropriate trip budget, saved booking values and saved public provider estimates. The owner’s private expense history and Trip Memory actual-spend detail are excluded.','safety_note'=>$this->safetyNote()];
    }

    public function settings(int $userId,int $tripId): array
    {
        if(!$this->ready())return $this->defaultSettings();$this->requireOwner($userId,$tripId);return $this->storedSettings($userId,$tripId);
    }

    public function saveSettings(int $userId,int $tripId,array $input): array
    {
        $this->requireReady();$this->requireOwner($userId,$tripId);$tolerance=strtolower(trim((string)($input['risk_tolerance']??'balanced')));if(!in_array($tolerance,['comfortable','balanced','stretch'],true))$tolerance='balanced';$cont=$this->pct($input['contingency_pct']??10,0,50);$reserve=$this->pct($input['disruption_reserve_pct']??5,0,50);$alert=$this->pct($input['alert_overage_pct']??5,0,100);$history=!empty($input['include_learned_history'])?1:0;
        $sql='INSERT INTO trip_affordability_settings (user_id,dream_trip_id,risk_tolerance,contingency_pct,disruption_reserve_pct,alert_overage_pct,include_learned_history,updated_by) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE risk_tolerance=VALUES(risk_tolerance),contingency_pct=VALUES(contingency_pct),disruption_reserve_pct=VALUES(disruption_reserve_pct),alert_overage_pct=VALUES(alert_overage_pct),include_learned_history=VALUES(include_learned_history),updated_by=VALUES(updated_by),updated_at=NOW()';
        $this->pdo->prepare($sql)->execute([$userId,$tripId,$tolerance,$cont,$reserve,$alert,$history,$userId]);$this->event($userId,$tripId,'settings_saved',['risk_tolerance'=>$tolerance,'contingency_pct'=>$cont,'disruption_reserve_pct'=>$reserve,'alert_overage_pct'=>$alert,'include_learned_history'=>$history]);return $this->settings($userId,$tripId);
    }

    public function saveScenario(int $userId,int $tripId,array $input): int
    {
        $this->requireReady();$this->requireOwner($userId,$tripId);$trip=$this->trip($tripId);$id=max(0,(int)($input['scenario_id']??0));$label=$this->clip((string)($input['label']??''),120);if($label==='')throw new InvalidArgumentException('Give this affordability scenario a name.');
        $travelers=$this->optionalInt($input['travelers']??null,1,30);$days=$this->optionalInt($input['duration_days']??null,1,120);$budget=$this->optionalMoney($input['target_budget']??null);$currency=$this->currency((string)($input['currency']??($trip['currency']??'USD')));$tripCurrency=$this->currency((string)($trip['currency']??'USD'));if($currency!==$tripCurrency)throw new InvalidArgumentException('Scenario currency must match the trip currency. Vacation Brain does not guess exchange rates.');
        $values=[];foreach(self::OVERRIDE_FIELDS as $field)$values[$field]=$this->optionalMoney($input[$field]??null);$cont=$this->optionalPct($input['contingency_pct']??null,0,50);$reserve=$this->optionalPct($input['disruption_reserve_pct']??null,0,50);
        $params=[$label,$travelers,$days,$budget,$currency,$values['flight_override'],$values['lodging_override'],$values['transport_override'],$values['food_override'],$values['activity_override'],$values['event_override'],$values['shopping_override'],$values['fees_override'],$cont,$reserve];
        if($id>0){$q=$this->pdo->prepare('UPDATE trip_affordability_scenarios SET label=?,travelers=?,duration_days=?,target_budget=?,currency=?,flight_override=?,lodging_override=?,transport_override=?,food_override=?,activity_override=?,event_override=?,shopping_override=?,fees_override=?,contingency_pct=?,disruption_reserve_pct=?,updated_at=NOW() WHERE id=? AND user_id=? AND dream_trip_id=?');$q->execute([...$params,$id,$userId,$tripId]);if($q->rowCount()!==1){$check=$this->pdo->prepare('SELECT id FROM trip_affordability_scenarios WHERE id=? AND user_id=? AND dream_trip_id=?');$check->execute([$id,$userId,$tripId]);if(!$check->fetchColumn())throw new OutOfBoundsException('Affordability scenario not found.');}}else{$count=$this->pdo->prepare('SELECT COUNT(*) FROM trip_affordability_scenarios WHERE user_id=? AND dream_trip_id=?');$count->execute([$userId,$tripId]);if((int)$count->fetchColumn()>=12)throw new DomainException('Keep up to 12 comparison scenarios per trip. Remove one before adding another.');$q=$this->pdo->prepare('INSERT INTO trip_affordability_scenarios (label,travelers,duration_days,target_budget,currency,flight_override,lodging_override,transport_override,food_override,activity_override,event_override,shopping_override,fees_override,contingency_pct,disruption_reserve_pct,user_id,dream_trip_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([...$params,$userId,$tripId]);$id=(int)$this->pdo->lastInsertId();}
        $this->event($userId,$tripId,'scenario_saved',['scenario_id'=>$id]);return $id;
    }

    public function deleteScenario(int $userId,int $tripId,int $scenarioId): void
    {
        $this->requireReady();$this->requireOwner($userId,$tripId);$q=$this->pdo->prepare('DELETE FROM trip_affordability_scenarios WHERE id=? AND user_id=? AND dream_trip_id=?');$q->execute([$scenarioId,$userId,$tripId]);if($q->rowCount()!==1)throw new OutOfBoundsException('Affordability scenario not found.');$this->event($userId,$tripId,'scenario_deleted',['scenario_id'=>$scenarioId]);
    }

    /** Safe owner-only Trip Inbox projection. Null means the prior warning can resolve. */
    public function inboxProjection(int $userId,int $tripId): ?array
    {
        if(!$this->ready())return null;$a=$this->access($userId,$tripId);if(empty($a['is_owner']))return null;$trip=$this->trip($tripId);$settings=$this->settings($userId,$tripId);$f=$this->forecast($userId,$trip,$settings,true,null);$target=$f['target_budget']??null;$final=$f['expected_final']??null;if($target===null||$target<=0||$final===null)return null;$over=max(0,(float)$final-(float)$target);$overPct=$target>0?($over/$target*100):0;if($over<=0||$overPct<(float)$settings['alert_overage_pct'])return null;$priority=$overPct>=25?94:($overPct>=15?88:($overPct>=5?80:72));$start=strtotime((string)($trip['start_date']??''));$daysAway=$start?(int)floor(($start-time())/86400):999;$urgency=$daysAway<=2?'today':'before_trip';return ['source_key'=>(string)$tripId,'thread_key'=>'affordability:'.$tripId,'item_type'=>'risk','priority'=>$priority,'urgency'=>$urgency,'title'=>'Trip forecast is over the target budget','body'=>(string)$trip['name'].' is currently projected around '.$this->moneyLabel((float)$final,(string)$f['currency']).', about '.$this->moneyLabel($over,(string)$f['currency']).' above the '.$this->moneyLabel((float)$target,(string)$f['currency']).' target. This is a planning estimate, not a quote or bank-settled total.','action_label'=>'Review affordability','action_url'=>app_url('trip-affordability.php?id='.$tripId),'source_status'=>'over_budget','requires_action'=>true,'occurred_at'=>date('Y-m-d H:i:s')];
    }

    /** Aggregate planning context only; no merchant, note, payment, claim, or Trip Memory narrative fields. */
    public function safeAgentContext(int $userId,int $limitTrips=3): array
    {
        if(!$this->ready())return [];$limitTrips=max(1,min(5,$limitTrips));$trips=$this->accessiblePlanningTrips($userId,$limitTrips);$out=[];foreach($trips as $trip){$tripId=(int)$trip['id'];try{$a=$this->access($userId,$tripId);if(empty($a['can_plan']))continue;$owner=!empty($a['is_owner']);$settings=$owner?$this->settings($userId,$tripId):$this->storedSettings((int)$trip['user_id'],$tripId);if(!$owner)$settings['include_learned_history']=0;$f=$this->forecast($userId,$trip,$settings,$owner,null);}catch(Throwable){continue;}$drivers=[];foreach(array_slice((array)($f['top_drivers']??[]),0,4) as $d)$drivers[]=['category'=>(string)$d['category'],'expected'=>(float)$d['expected']];$fits=[];foreach(array_slice($this->fitSuggestions($f),0,3) as $s)$fits[]=['title'=>(string)$s['title'],'estimated_savings'=>(float)$s['estimated_savings']];$out[]=['trip_id'=>$tripId,'trip_name'=>(string)$trip['name'],'role'=>(string)($a['role']??'viewer'),'currency'=>(string)$f['currency'],'target_budget'=>$f['target_budget'],'saved_booking_value'=>(float)$f['booked_value'],'expected_final'=>(float)$f['expected_final'],'expected_remaining'=>(float)$f['expected_remaining'],'headroom'=>$f['headroom'],'risk_status'=>(string)$f['risk_status'],'confidence'=>(string)$f['confidence'],'top_drivers'=>$drivers,'fit_options'=>$fits];}return $out;
    }

    private function forecast(int $userId,array $trip,array $settings,bool $allowHistory,?array $scenario): array
    {
        $tripId=(int)$trip['id'];$currency=$this->currency((string)($trip['currency']??'USD'));$travelers=$scenario&&$scenario['travelers']!==null?(int)$scenario['travelers']:max(1,(int)($trip['travelers']??1));$days=$scenario&&$scenario['duration_days']!==null?(int)$scenario['duration_days']:$this->tripDays($trip);$target=$scenario&&$scenario['target_budget']!==null?(float)$scenario['target_budget']:($trip['target_budget']!==null?(float)$trip['target_budget']:null);$cont=$scenario&&$scenario['contingency_pct']!==null?(float)$scenario['contingency_pct']:(float)$settings['contingency_pct'];$reservePct=$scenario&&$scenario['disruption_reserve_pct']!==null?(float)$scenario['disruption_reserve_pct']:(float)$settings['disruption_reserve_pct'];
        $booked=array_fill_keys(array_keys(self::CATEGORIES),0.0);foreach($this->bookingRows($tripId) as $r){if($r['amount']===null||in_array((string)$r['status'],['unbooked','ready_to_book','cancelled'],true)||(string)$r['payment_status']==='refunded')continue;if($this->currency((string)$r['currency'])!==$currency)continue;$cat=$this->bookingCategory((string)$r['booking_type']);$booked[$cat]=round(($booked[$cat]??0)+(float)$r['amount'],2);}
        $plans=array_fill_keys(array_keys(self::CATEGORIES),0.0);foreach($this->planRows($tripId) as $r){if($this->currency((string)$r['currency'])!==$currency)continue;$cat=(string)$r['cost_category'];if(isset($plans[$cat]))$plans[$cat]=(float)$r['amount'];}
        $live=$this->liveEstimates($trip,$travelers,$currency);$history=['samples'=>0,'estimated_total'=>0.0,'by_category'=>[],'disruption_overhead_pct'=>0.0];if($allowHistory&&!empty($settings['include_learned_history'])&&class_exists('TripCostIntelligenceService')){try{$costs=new TripCostIntelligenceService($this->pdo);if($costs->ready()){$model=$costs->historyModel($userId,40);$m=$model['currencies'][$currency]??null;if(is_array($m)&&!empty($m['samples'])){$total=0.0;if(($m['average_per_traveler_day']??null)!==null)$total=(float)$m['average_per_traveler_day']*$travelers*$days;elseif(($m['average_per_day']??null)!==null)$total=(float)$m['average_per_day']*$days;else $total=(float)($m['average_trip_cost']??0);$history=['samples'=>(int)$m['samples'],'estimated_total'=>round(max(0,$total),2),'by_category'=>[],'disruption_overhead_pct'=>(float)($m['disruption_overhead_pct']??0)];foreach((array)($m['top_categories']??[]) as $cat){$key=(string)($cat['category']??'');if(isset(self::CATEGORIES[$key]))$history['by_category'][$key]=round($total*((float)($cat['share_pct']??0)/100),2);}}}}catch(Throwable){}}
        if($allowHistory&&$history['samples']>0)$reservePct=max($reservePct,min(25,(float)$history['disruption_overhead_pct']));
        $categories=[];$sources=[];$bookedTotal=0.0;$subtotal=0.0;foreach(self::CATEGORIES as $cat=>$label){$b=round((float)($booked[$cat]??0),2);$p=round((float)($plans[$cat]??0),2);$l=round((float)($live[$cat]['amount']??0),2);$h=round((float)($history['by_category'][$cat]??0),2);$override=null;if($scenario&&isset(self::OVERRIDE_FIELDS[$cat])){$field=self::OVERRIDE_FIELDS[$cat];if(array_key_exists($field,$scenario)&&$scenario[$field]!==null)$override=(float)$scenario[$field];}$expected=$override!==null?max($b,$override):max($b,$p,$l,$h);$source='none';$max=max($b,$p,$l,$h);if($override!==null)$source='scenario';elseif($max>0){if($max===$b)$source='booked';elseif($max===$p)$source='category_plan';elseif($max===$l)$source='saved_provider_estimate';else $source='learned_history';}$categories[$cat]=['label'=>$label,'booked'=>$b,'planned'=>$p,'live_estimate'=>$l?:null,'history_estimate'=>$allowHistory&&$h>0?$h:null,'scenario_override'=>$override,'expected'=>round($expected,2),'expected_remaining'=>round(max(0,$expected-$b),2),'source'=>$source];$bookedTotal+=$b;$subtotal+=$expected;if($source!=='none')$sources[$source]=($sources[$source]??0)+1;}
        $contingency=round($subtotal*($cont/100),2);$reserve=round($subtotal*($reservePct/100),2);$final=round($subtotal+$contingency+$reserve,2);$remaining=round(max(0,$final-$bookedTotal),2);$headroom=$target!==null?round($target-$final,2):null;$ratio=$target!==null&&$target>0?$final/$target:null;$confidence=($sources['booked']??0)+($sources['category_plan']??0)>=4?'high':(($history['samples']??0)>=2||($sources['saved_provider_estimate']??0)>0?'medium':'low');$comfortable=match((string)$settings['risk_tolerance']){'comfortable'=>0.80,'stretch'=>0.90,default=>0.85};$rawRisk=$ratio===null?'unknown':($ratio<=$comfortable?'comfortable':($ratio<=1?'tight':'over_budget'));$risk=$rawRisk!=='over_budget'&&$confidence==='low'?'unknown':$rawRisk;$drivers=array_values($categories);usort($drivers,static fn($a,$b)=>((float)$b['expected'])<=>((float)$a['expected']));$drivers=array_values(array_filter($drivers,static fn($r)=>(float)$r['expected']>0));foreach($drivers as $i=>$d){$key=array_search($d['label'],self::CATEGORIES,true);$drivers[$i]['category']=$key===false?'other':$key;}
        $f=['currency'=>$currency,'travelers'=>$travelers,'duration_days'=>$days,'target_budget'=>$target,'booked_value'=>round($bookedTotal,2),'forecast_subtotal'=>round($subtotal,2),'contingency_pct'=>round($cont,2),'contingency'=>round($contingency,2),'disruption_reserve_pct'=>round($reservePct,2),'disruption_reserve'=>round($reserve,2),'expected_final'=>$final,'expected_remaining'=>$remaining,'headroom'=>$headroom,'budget_ratio_pct'=>$ratio!==null?round($ratio*100,1):null,'risk_status'=>$risk,'confidence'=>$confidence,'categories'=>$categories,'top_drivers'=>array_slice($drivers,0,6),'source_counts'=>$sources,'history_samples'=>$allowHistory?(int)$history['samples']:0,'live_observed_at'=>$live['_observed_at']??null,'semantics'=>'Planning forecast only. Saved booking amounts are booking values, live estimates come only from previously saved provider snapshots, and no currency conversion is inferred.'];$f['value_score']=$this->valueScore($f,$f,null);return $f;
    }

    private function fitSuggestions(array $f): array
    {
        $target=$f['target_budget']??null;$final=(float)($f['expected_final']??0);if($target===null||$target<=0||$final<=$target)return [];$needed=round($final-$target,2);$out=[];$cats=(array)($f['categories']??[]);$add=function(string $title,string $body,float $save,string $tradeoff,string $kind) use (&$out):void{if($save<1)return;$out[]=['title'=>$title,'body'=>$body,'estimated_savings'=>round($save,2),'tradeoff'=>$tradeoff,'kind'=>$kind];};
        $days=max(1,(int)($f['duration_days']??1));if($days>2){$variable=max(0,(float)$f['expected_remaining']-(float)$f['contingency']-(float)$f['disruption_reserve']);$add('Compare a trip that is one day shorter','Model one fewer lodging/food/local-transport day before changing any reservation.',$variable/$days,'Less time at the destination','scenario');}
        foreach([['lodging',0.15,'Research a lower-cost stay','Compare another property, neighborhood or set of dates.','Different lodging'],['flight',0.10,'Compare alternate dates or airports','Research a lower fare before changing a booked flight.','Less convenient routing or dates'],['food',0.15,'Shift part of dining to lower-cost meals','Keep the experiences that matter while reducing routine meal spend.','Different dining mix'],['activity',0.25,'Trim paid activities','Keep the highest-value activities and leave more open/local time.','Fewer paid activities'],['event',0.25,'Trim ticketed events','Compare the most important event against free or lower-cost alternatives.','Fewer ticketed events']] as [$cat,$pct,$title,$body,$trade]){$r=$cats[$cat]??[];$flex=max(0,(float)($r['expected']??0)-(float)($r['booked']??0));$add($title,$body,$flex*$pct,$trade,'category');}
        usort($out,static fn($a,$b)=>((float)$b['estimated_savings'])<=>((float)$a['estimated_savings']));$running=0.0;foreach($out as &$row){$running+=(float)$row['estimated_savings'];$row['covers_overage']=$running>=$needed;}unset($row);return array_slice($out,0,6);
    }

    private function valueScore(array $f,array $baseline,?array $scenario): int
    {
        $score=92;$ratio=$f['budget_ratio_pct']??null;if($ratio!==null&&$ratio>100)$score-=min(45,(int)round(($ratio-100)*1.4));if((string)($f['confidence']??'low')==='low')$score-=8;elseif((string)($f['confidence']??'')==='medium')$score-=3;if($scenario){$baseDays=max(1,(int)($baseline['duration_days']??1));$days=max(1,(int)($f['duration_days']??$baseDays));if($days<$baseDays)$score-=min(20,($baseDays-$days)*6);$baseTravel=max(1,(int)($baseline['travelers']??1));$travel=max(1,(int)($f['travelers']??$baseTravel));if($travel<$baseTravel)$score-=min(25,($baseTravel-$travel)*10);foreach(self::OVERRIDE_FIELDS as $cat=>$field){if(($scenario[$field]??null)===null)continue;$base=(float)($baseline['categories'][$cat]['expected']??0);$now=(float)($f['categories'][$cat]['expected']??0);if($base>0&&$now<$base)$score-=min(6,(int)round((1-$now/$base)*6));}}return max(0,min(100,$score));
    }

    private function liveEstimates(array $trip,int $travelers,string $currency): array
    {
        $out=[];if(!db_table_exists('trip_intelligence_snapshots'))return $out;$owner=(int)$trip['user_id'];$tripId=(int)$trip['id'];foreach(['flights'=>'flight','lodging'=>'lodging'] as $type=>$cat){$q=$this->pdo->prepare("SELECT payload_json,observed_at,expires_at FROM trip_intelligence_snapshots WHERE dream_trip_id=? AND user_id=? AND data_type=? AND source_status='success' ORDER BY observed_at DESC,id DESC LIMIT 1");$q->execute([$tripId,$owner,$type]);$r=$q->fetch();if(!$r||strtotime((string)$r['expires_at'])<time())continue;$p=json_decode((string)$r['payload_json'],true);if(!is_array($p)||empty($p['ok'])||!isset($p['min_price'])||$p['min_price']===null)continue;$pc=$this->currency((string)($p['currency']??$currency));if($pc!==$currency)continue;$amount=(float)$p['min_price'];if($cat==='flight')$amount*=$travelers;$out[$cat]=['amount'=>round(max(0,$amount),2),'observed_at'=>(string)$r['observed_at']];$out['_observed_at']=max((string)($out['_observed_at']??''),(string)$r['observed_at']);}return $out;
    }

    private function accessiblePlanningTrips(int $userId,int $limit): array
    {
        $q=$this->pdo->prepare("SELECT * FROM dream_trips WHERE user_id=? AND status<>'abandoned' ORDER BY FIELD(operational_state,'planning','booking','ready','traveling','completed'),COALESCE(start_date,'9999-12-31'),id LIMIT {$limit}");$q->execute([$userId]);$rows=$q->fetchAll()?:[];if(count($rows)<$limit&&db_table_exists('trip_collaborators')){$remaining=$limit-count($rows);$s=$this->pdo->prepare("SELECT dt.* FROM trip_collaborators tc JOIN dream_trips dt ON dt.id=tc.dream_trip_id WHERE tc.user_id=? AND tc.status='active' AND tc.role='co_planner' AND dt.status<>'abandoned' ORDER BY COALESCE(dt.start_date,'9999-12-31'),dt.id LIMIT {$remaining}");$s->execute([$userId]);foreach($s->fetchAll()?:[] as $r)$rows[]=$r;}return $rows;
    }

    private function scenarioRows(int $userId,int $tripId): array{$q=$this->pdo->prepare('SELECT * FROM trip_affordability_scenarios WHERE user_id=? AND dream_trip_id=? ORDER BY updated_at DESC,id DESC');$q->execute([$userId,$tripId]);return $q->fetchAll()?:[];}
    private function castScenario(array $r): array{$out=['travelers'=>$r['travelers']!==null?(int)$r['travelers']:null,'duration_days'=>$r['duration_days']!==null?(int)$r['duration_days']:null,'target_budget'=>$r['target_budget']!==null?(float)$r['target_budget']:null,'currency'=>$this->currency((string)$r['currency']),'contingency_pct'=>$r['contingency_pct']!==null?(float)$r['contingency_pct']:null,'disruption_reserve_pct'=>$r['disruption_reserve_pct']!==null?(float)$r['disruption_reserve_pct']:null];foreach(self::OVERRIDE_FIELDS as $field)$out[$field]=$r[$field]!==null?(float)$r[$field]:null;return $out;}
    private function bookingRows(int $tripId): array{if(!db_table_exists('trip_bookings'))return [];$q=$this->pdo->prepare('SELECT booking_type,status,payment_status,amount,currency FROM trip_bookings WHERE dream_trip_id=? ORDER BY id');$q->execute([$tripId]);return $q->fetchAll()?:[];}
    private function planRows(int $tripId): array{$q=$this->pdo->prepare('SELECT cost_category,amount,currency FROM trip_cost_category_plans WHERE dream_trip_id=? ORDER BY id');$q->execute([$tripId]);return $q->fetchAll()?:[];}
    private function bookingCategory(string $type): string{return match($type){'flight'=>'flight','lodging'=>'lodging','transport'=>'transport','restaurant'=>'food','activity'=>'activity','event'=>'event',default=>'other'};}
    private function storedSettings(int $ownerUserId,int $tripId): array{$q=$this->pdo->prepare('SELECT risk_tolerance,contingency_pct,disruption_reserve_pct,alert_overage_pct,include_learned_history FROM trip_affordability_settings WHERE user_id=? AND dream_trip_id=? LIMIT 1');$q->execute([$ownerUserId,$tripId]);$r=$q->fetch();if(!$r)return $this->defaultSettings();return ['risk_tolerance'=>(string)$r['risk_tolerance'],'contingency_pct'=>(float)$r['contingency_pct'],'disruption_reserve_pct'=>(float)$r['disruption_reserve_pct'],'alert_overage_pct'=>(float)$r['alert_overage_pct'],'include_learned_history'=>(int)$r['include_learned_history']];}
    private function defaultSettings(): array{return ['risk_tolerance'=>'balanced','contingency_pct'=>10.0,'disruption_reserve_pct'=>5.0,'alert_overage_pct'=>5.0,'include_learned_history'=>1];}
    private function access(int $userId,int $tripId): array{if(class_exists('TripItineraryIntelligenceService'))return (new TripItineraryIntelligenceService($this->pdo))->access($userId,$tripId);$t=$this->trip($tripId);if((int)$t['user_id']===$userId)return ['role'=>'owner','is_owner'=>true,'can_plan'=>true];throw new OutOfBoundsException('Trip not found or permission denied.');}
    private function requireOwner(int $userId,int $tripId): void{$a=$this->access($userId,$tripId);if(empty($a['is_owner']))throw new DomainException('Only the trip owner can change affordability assumptions or saved scenarios.');}
    private function trip(int $tripId): array{$q=$this->pdo->prepare('SELECT * FROM dream_trips WHERE id=? LIMIT 1');$q->execute([$tripId]);$r=$q->fetch();if(!$r)throw new OutOfBoundsException('Trip not found.');return $r;}
    private function publicTrip(array $t): array{return ['id'=>(int)$t['id'],'name'=>(string)$t['name'],'currency'=>$this->currency((string)($t['currency']??'USD')),'start_date'=>$t['start_date']??null,'end_date'=>$t['end_date']??null,'travelers'=>max(1,(int)($t['travelers']??1)),'target_budget'=>$t['target_budget']!==null?(float)$t['target_budget']:null,'operational_state'=>(string)($t['operational_state']??'planning')];}
    private function tripDays(array $trip): int{$s=strtotime((string)($trip['start_date']??''));$e=strtotime((string)($trip['end_date']??''));if(!$s||!$e||$e<$s)return 1;return max(1,(int)floor(($e-$s)/86400)+1);}
    private function currency(string $v): string{$v=strtoupper(trim($v));return preg_match('/^[A-Z]{3}$/',$v)?$v:'USD';}
    private function pct(mixed $v,float $min,float $max): float{if($v===null||trim((string)$v)===''||!is_numeric($v))throw new InvalidArgumentException('Enter a valid percentage.');$n=round((float)$v,2);if($n<$min||$n>$max)throw new InvalidArgumentException('Percentage is outside the supported range.');return $n;}
    private function optionalPct(mixed $v,float $min,float $max): ?float{if($v===null||trim((string)$v)==='')return null;return $this->pct($v,$min,$max);}
    private function optionalMoney(mixed $v): ?float{if($v===null||trim((string)$v)==='')return null;if(!is_numeric($v))throw new InvalidArgumentException('Enter a valid scenario amount.');$n=round((float)$v,2);if($n<0||$n>99999999)throw new InvalidArgumentException('Scenario amount is outside the supported range.');return $n;}
    private function optionalInt(mixed $v,int $min,int $max): ?int{if($v===null||trim((string)$v)==='')return null;$raw=trim((string)$v);if(!preg_match('/^\d+$/',$raw))throw new InvalidArgumentException('Enter a valid whole number.');$n=(int)$raw;if($n<$min||$n>$max)throw new InvalidArgumentException('Scenario value is outside the supported range.');return $n;}
    private function clip(string $v,int $max): string{$v=trim(preg_replace('/\s+/u',' ',$v)??$v);return function_exists('mb_substr')?mb_substr($v,0,$max):substr($v,0,$max);}
    private function event(int $userId,int $tripId,string $type,array $payload): void{$this->pdo->prepare('INSERT INTO trip_affordability_events (user_id,dream_trip_id,event_type,event_json) VALUES (?,?,?,?)')->execute([$userId,$tripId,$type,json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE)]);}
    private function moneyLabel(float $v,string $currency): string{return ($currency==='USD'?'$':$currency.' ').number_format($v,0);}
    private function safetyNote(): string{return 'Affordability Intelligence is planning analysis only. It never pays, books, cancels, changes a reservation, submits a claim, requests a refund, redeems a credit, opens checkout, or performs a provider transaction.';}
    private function requireReady(): void{if(!$this->ready())throw new RuntimeException('Run System Upgrade for Budget-Aware Trip Planning + Affordability Intelligence.');}
    private function emptySnapshot(array $trip,string $role,bool $owner,bool $canPlan): array{return ['ready'=>false,'trip'=>$this->publicTrip($trip),'role'=>$role,'can_view'=>$canPlan,'can_manage'=>$owner,'settings'=>[],'forecast'=>[],'scenarios'=>[],'fit_suggestions'=>[],'privacy_note'=>'Run System Upgrade for v1.52 / migration 060.','safety_note'=>$this->safetyNote()];}
}
