<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$service=new DestinationOwnerService($pdo);
$pageStyles=['assets/destination-owner.css'];$title='Claim a Destination — Vacation Brain';
if(!$service->ready()){
    require __DIR__.'/partials/header.php';?>
    <section class="dashboard destination-owner-page"><div class="shell"><div class="dashboard-card"><h1>Destination claims need the latest upgrade.</h1><?php if(is_admin()):?><a class="button primary" href="<?=e(app_url('upgrade.php'))?>">Run System Upgrade</a><?php endif;?></div></div></section>
    <?php require __DIR__.'/partials/footer.php';exit;
}
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{$destinationId=(int)($_POST['destination_id']??0);$service->requestClaim($userId,$destinationId,$_POST);flash('success','Destination claim submitted for administrator review.');redirect('destination-claim.php?destination_id='.$destinationId);}catch(Throwable $e){flash('error',$e->getMessage());redirect('destination-claim.php?destination_id='.(int)($_POST['destination_id']??0));}
}
$q=trim((string)($_GET['q']??''));$selectedId=(int)($_GET['destination_id']??0);$sampleClause=(db_column_exists('destination_catalog','is_sample')&&!sample_data_enabled())?' AND is_sample=0':'';$args=[];
$sql="SELECT id,name,city,region,country,hero_image_url,publication_status FROM destination_catalog WHERE publication_status='published'".$sampleClause;
if($q!==''){$sql.=' AND (name LIKE ? OR city LIKE ? OR region LIKE ? OR country LIKE ?)';$like='%'.$q.'%';$args=array_fill(0,4,$like);}$sql.=' ORDER BY featured DESC,sort_order,name LIMIT 150';$stmt=$pdo->prepare($sql);$stmt->execute($args);$destinations=$stmt->fetchAll()?:[];
$selected=$selectedId?$service->destination($selectedId):null;$claims=$service->claimsForUser($userId);$success=flash('success');$error=flash('error');require __DIR__.'/partials/header.php';
?>
<section class="dashboard destination-owner-page"><div class="shell"><div class="destination-owner-head"><div><span class="eyebrow">Destination Ownership</span><h1>Claim a destination</h1><p class="muted">Already represent a destination Vacation Brain knows? Submit a claim. Approval assigns the Destination Owner account type and unlocks the listing dashboard.</p></div><div class="destination-owner-actions"><a class="button secondary small" href="<?=e(app_url('destinations.php'))?>">Browse destinations</a><?php if($service->canUseDashboard($userId)):?><a class="button secondary small" href="<?=e(app_url('destination-dashboard.php'))?>">Destination Dashboard</a><?php endif;?></div></div>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="destination-claim-grid"><div class="destination-owner-stack"><article class="dashboard-card"><h2>Find your listing</h2><form method="get"><div class="destination-owner-inline"><div class="field"><label>Search destinations</label><input class="input" type="search" name="q" value="<?=e($q)?>" placeholder="Sedona, resort, Arizona…"></div><button class="button secondary small">Search</button></div></form><div class="destination-owner-list" style="margin-top:14px"><?php foreach(array_slice($destinations,0,20) as $d):?><a class="destination-owner-listing" href="<?=e(app_url('destination-claim.php?destination_id='.(int)$d['id'].($q!==''?'&q='.urlencode($q):'')))?>"><span class="destination-owner-thumb"<?php if($d['hero_image_url']):?> style="background-image:url('<?=e(media_url((string)$d['hero_image_url']))?>')"<?php endif;?>></span><span><h3><?=e($d['name'])?></h3><p><?=e(trim(implode(', ',array_filter([$d['city'],$d['region'],$d['country']]))))?></p></span><span>→</span></a><?php endforeach;?><?php if(!$destinations):?><p class="muted">No matching destination listing was found.</p><?php endif;?></div></article>
<?php if($claims):?><article class="dashboard-card"><h2>Your claims</h2><?php foreach($claims as $claim):?><div class="destination-claim-row"><div><strong><?=e($claim['name'])?></strong><small><?=e($claim['created_at'])?></small><?php if($claim['resolution_note']):?><small><?=e($claim['resolution_note'])?></small><?php endif;?></div><span class="destination-owner-status <?=e($claim['status'])?>"><?=e(ucfirst($claim['status']))?></span></div><?php endforeach;?></article><?php endif;?></div>

<div class="destination-owner-stack"><?php if($selected):?><article class="destination-preview-card"><div class="destination-preview-media"<?php if($selected['hero_image_url']):?> style="background-image:url('<?=e(media_url((string)$selected['hero_image_url']))?>')"<?php endif;?>></div><div class="destination-preview-body"><span class="eyebrow">Claiming</span><h2><?=e($selected['name'])?></h2><p><?=e(trim(implode(', ',array_filter([$selected['city'],$selected['region'],$selected['country']]))))?></p></div></article><form class="dashboard-card destination-owner-form" method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="destination_id" value="<?=(int)$selected['id']?>"><div class="field"><label>Business / organization name</label><input class="input" name="business_name" maxlength="255" placeholder="Optional operating or tourism organization name"></div><div class="field"><label>Official website</label><input class="input" type="url" name="business_url" placeholder="https://…"></div><div class="field"><label>How are you connected to this destination?</label><textarea class="input" name="proof_text" rows="7" minlength="20" required placeholder="Tell the administrator why you should control this listing and what can be verified."></textarea></div><div class="destination-owner-notice"><strong>What approval does</strong><p class="muted small">Approval creates the destination ownership relationship, changes your account type to Destination Owner, and gives you the listing editor/team dashboard. It does not expose private Vacation Brain user data.</p></div><button class="button primary" type="submit">Submit destination claim</button></form><?php else:?><article class="dashboard-card"><h2>Select a destination first.</h2><p class="muted">Choose an existing Vacation Brain destination from the results. If it is not listed yet, an administrator can create the catalog record before assigning ownership.</p></article><?php endif;?></div></div>
</div></section><?php require __DIR__.'/partials/footer.php';
