<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();
if(!db_table_exists('destination_reports')){
    $title='Destination Research — Vacation Brain';require __DIR__.'/partials/header.php';?>
    <section class="dashboard"><div class="shell"><div class="dashboard-card upgrade-required-card"><div class="eyebrow">Destination Research</div><h1>Research is waiting for the latest upgrade.</h1><p class="muted">An administrator needs to run the pending database migration before destination reports can be saved.</p><?php if(can_show_admin_entry()):?><a class="button primary" href="<?=e(app_url('upgrade.php'))?>">Run System Upgrade</a><?php endif;?></div></div></section>
    <?php require __DIR__.'/partials/footer.php';exit;
}
$service=new DestinationResearchService($pdo);$error='';$report=null;$destination=null;
$destinationId=(int)($_GET['destination_id']??$_POST['destination_id']??0);$reportId=(int)($_GET['report_id']??0);$q=trim((string)($_GET['q']??$_POST['q']??''));
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{$report=$service->generate($userId,$destinationId?:null,$q,(string)($_POST['start_date']??''),(string)($_POST['end_date']??''));$destinationId=(int)($report['destination_catalog_id']??0);flash('success','Destination research saved to Vacation Brain.');redirect('destination-report.php?report_id='.(int)$report['id']);}
    catch(Throwable $e){$error=$e->getMessage();}
}
if($reportId)$report=$service->report($reportId);
if($report && !empty($report['destination_catalog_id'])){$destinationId=(int)$report['destination_catalog_id'];$destination=$service->destination($destinationId);}
elseif($destinationId){$destination=$service->destination($destinationId);if($destination)$report=$service->latestForDestination($destinationId);}
$gallery=$destinationId?$service->gallery($destinationId):[];$success=flash('success');
$title=($destination['name']??$report['normalized_location']??($q?:'Destination Research')).' — Vacation Brain';require __DIR__.'/partials/header.php';
$decodeList=function($v){return is_array($v)?$v:[];};
$lodging=$decodeList($report['lodging']??[]);$day=$decodeList($report['day_trips']??[]);$restaurants=$decodeList($report['restaurants']??[]);$shows=$decodeList($report['shows']??[]);$sources=$decodeList($report['sources']??[]);$weatherHistory=$decodeList($report['weather_history']??[]);$forecast=$decodeList($report['weather_forecast']??[]);
if(isset($day['day_trips'])||isset($day['entertainment'])){$dayTrips=$decodeList($day['day_trips']??[]);$entertainment=$decodeList($day['entertainment']??[]);}else{$dayTrips=$day;$entertainment=[];}
?>
<section class="dashboard destination-report-page"><div class="shell">
<div class="dashboard-head"><div><div class="eyebrow">Vacation Brain Destination Report</div><h1><?=e($destination['name']??$report['normalized_location']??($q?:'Research a destination'))?></h1><p class="muted">One reusable research snapshot: weather, lodging, food, activities, events, photos and sources — saved back into Vacation Brain.</p></div><a class="button secondary small" href="<?=e(app_url('destinations.php'))?>">← Destinations</a></div>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(!$report):?>
<div class="destination-research-start"><div class="dashboard-card"><h2>Build a destination report</h2><p class="muted">The active OpenAI or Claude key will research the public web, create the report, save the sources, and catalog useful lodging, restaurants and activities for future Vacation Brain use.</p><form method="post" class="research-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="destination_id" value="<?=$destinationId?>"><label>Destination<input class="input" name="q" required value="<?=e($q?:($destination['name']??''))?>" placeholder="Lisbon, Portugal"></label><div class="form-grid two"><label>Travel start <input class="input" type="date" name="start_date"></label><label>Travel end <input class="input" type="date" name="end_date"></label></div><button class="button primary">Research with Vacation Brain AI</button><p class="microcopy">Live research uses the configured LLM provider and may incur provider web-search/token charges. Reports are cached in Vacation Brain after generation.</p></form></div><div class="dashboard-card"><h2>What gets researched</h2><div class="research-criteria-grid"><?php foreach($service->criteria() as $k=>$label):?><div class="info-card"><strong><?=e(ucwords(str_replace('_',' ',$k)))?></strong><p><?=e($label)?></p></div><?php endforeach;?></div></div></div>
<?php else:?>
<?php if(!empty($report['is_sample'])):?><div class="alert warning"><strong>Sample destination report.</strong> This demonstrates the report UI and database structure. Click <strong>Refresh with live AI research</strong> for sourced current weather, lodging, reviews and events.</div><?php endif;?>
<div class="report-meta-row"><span>Generated <?=e($report['generated_at']??'')?></span><span><?=e(($report['provider']??'')?ucfirst((string)$report['provider']).' · '.(string)$report['model_name']:'Sample / saved data')?></span><?php if(!empty($report['travel_start_date'])):?><span><?=e($report['travel_start_date'])?><?=!empty($report['travel_end_date'])?' → '.e($report['travel_end_date']):''?></span><?php endif;?></div>
<div class="destination-report-hero" <?php if(!empty($destination['hero_image_url'])):?>style="background-image:linear-gradient(90deg,rgba(10,27,43,.72),rgba(10,27,43,.18)),url('<?=e($destination['hero_image_url'])?>')"<?php endif;?>><div><span class="eyebrow">General summary</span><h2><?=e($report['normalized_location']??($destination['name']??''))?></h2><div class="report-summary"><?=nl2br(e((string)$report['summary_text']))?></div></div></div>
<div class="report-action-row"><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="destination_id" value="<?=$destinationId?>"><input type="hidden" name="q" value="<?=e($destination['name']??$report['normalized_location']??'')?>"><button class="button primary small">Refresh with live AI research</button></form><?php if(is_admin()):?><a class="button secondary small" href="<?=e(app_url('admin/destination-reports.php'))?>">Research library</a><?php endif;?></div>
<div class="report-grid two-col">
<article class="dashboard-card report-section"><div class="report-section-head"><span>☀</span><div><h2>Weather history</h2><p>Typical patterns, not a substitute for the date-specific forecast.</p></div></div><p><?=e((string)($weatherHistory['summary']??'No weather-history summary saved.'))?></p><?php foreach((array)($weatherHistory['seasonal_notes']??[]) as $w):?><div class="report-list-item"><strong><?=e($w['period']??'Season')?></strong><p><?=e($w['conditions']??'')?></p><small><?=e(trim(implode(' · ',array_filter([$w['typical_high']??null,$w['typical_low']??null,$w['rain_notes']??null]))))?></small></div><?php endforeach;?></article>
<article class="dashboard-card report-section"><div class="report-section-head"><span>↗</span><div><h2>Forecast</h2><p><?=e(!empty($forecast['as_of'])?'As of '.$forecast['as_of']:'Current forecast when available')?></p></div></div><p><?=e((string)($forecast['summary']??'No live forecast saved.'))?></p><div class="forecast-strip"><?php foreach(array_slice((array)($forecast['days']??[]),0,10) as $f):?><div><strong><?=e($f['date']??'')?></strong><span><?=e($f['conditions']??'')?></span><small><?=e(trim(($f['high']??'').' / '.($f['low']??''),' /'))?></small></div><?php endforeach;?></div></article>
</div>
<article class="dashboard-card report-section"><div class="report-section-head"><span>▤</span><div><h2>Lodging</h2><p><?=e((string)($lodging['summary']??'Hotels and vacation-rental options.'))?></p></div></div><div class="lodging-columns"><?php foreach(['hotels'=>'Hotels','airbnb'=>'Airbnb','vrbo'=>'Vrbo'] as $key=>$label):?><div><h3><?=$label?></h3><?php foreach((array)($lodging[$key]??[]) as $x):?><div class="report-option"><strong><?=e($x['name']??'Option')?></strong><span><?=e(trim(implode(' · ',array_filter([$x['area']??null,$x['price_text']??null,isset($x['rating'])&&$x['rating']!==null?'★ '.$x['rating']:null]))))?></span><p><?=e($x['summary']??'')?></p><div class="source-links"><?php if(!empty($x['booking_url'])):?><a href="<?=e($x['booking_url'])?>" target="_blank" rel="noopener">Booking/listing ↗</a><?php endif;?><?php if(!empty($x['source_url']) && $x['source_url']!==($x['booking_url']??'')):?><a href="<?=e($x['source_url'])?>" target="_blank" rel="noopener">Source ↗</a><?php endif;?></div></div><?php endforeach;?><p class="muted small"><?=empty($lodging[$key])?'No verified options saved in this report.':''?></p></div><?php endforeach;?></div></article>
<div class="report-grid two-col"><article class="dashboard-card report-section"><div class="report-section-head"><span>⌖</span><div><h2>Day trips & things to do</h2><p>Activities, attractions and excuses to leave the pool.</p></div></div><?php foreach(array_merge($dayTrips,$entertainment) as $x):?><div class="report-option"><strong><?=e($x['name']??'Activity')?></strong><span><?=e(trim(implode(' · ',array_filter([$x['category']??null,$x['distance']??null,$x['price_text']??null]))))?></span><p><?=e($x['summary']??'')?></p><?php if(!empty($x['source_url'])):?><a href="<?=e($x['source_url'])?>" target="_blank" rel="noopener">Source ↗</a><?php endif;?></div><?php endforeach;?></article>
<article class="dashboard-card report-section"><div class="report-section-head"><span>✦</span><div><h2>Favorite local restaurants</h2><p>Current review/reputation signals, not Vacation Brain pretending it personally ate there.</p></div></div><?php foreach($restaurants as $x):?><div class="report-option"><strong><?=e($x['name']??'Restaurant')?></strong><span><?=e(trim(implode(' · ',array_filter([$x['cuisine']??null,$x['area']??null,isset($x['rating'])&&$x['rating']!==null?'★ '.$x['rating']:null,!empty($x['review_count'])?number_format((int)$x['review_count']).' reviews':null,$x['price_text']??null]))))?></span><p><?=e($x['summary']??'')?></p><?php if(!empty($x['source_url'])):?><a href="<?=e($x['source_url'])?>" target="_blank" rel="noopener">Review/source ↗</a><?php endif;?></div><?php endforeach;?></article></div>
<article class="dashboard-card report-section"><div class="report-section-head"><span>♫</span><div><h2>Upcoming shows & events</h2><p>Concerts, theater, festivals, sports and other date-sensitive reasons to adjust the trip.</p></div></div><div class="events-grid"><?php foreach($shows as $x):?><div class="report-option"><strong><?=e($x['name']??'Event')?></strong><span><?=e(trim(implode(' · ',array_filter([$x['category']??null,$x['venue']??null,$x['starts_at']??null]))))?></span><p><?=e($x['summary']??'')?></p><div class="source-links"><?php if(!empty($x['ticket_url'])):?><a href="<?=e($x['ticket_url'])?>" target="_blank" rel="noopener">Tickets ↗</a><?php endif;?><?php if(!empty($x['source_url'])):?><a href="<?=e($x['source_url'])?>" target="_blank" rel="noopener">Source ↗</a><?php endif;?></div></div><?php endforeach;?><?php if(!$shows):?><p class="muted">No verified upcoming events were saved in this report.</p><?php endif;?></div></article>
<article class="dashboard-card report-section"><div class="report-section-head"><span>▧</span><div><h2>Destination gallery</h2><p>General-location imagery saved with the destination; source links are retained when research provides them.</p></div></div><div class="destination-report-gallery"><?php foreach($gallery as $img):?><figure><img src="<?=e($img['image_url'])?>" alt="<?=e($img['caption']??($destination['name']??'Destination'))?>" loading="lazy"><figcaption><?=e($img['caption']??'')?></figcaption></figure><?php endforeach;?><?php if(!$gallery):?><div class="empty-gallery">No reusable images saved yet. Vacation Brain did, however, save the report. Priorities.</div><?php endif;?></div></article>
<details class="dashboard-card report-sources"><summary><strong>Sources & research trail</strong><span><?=count($sources)?> saved</span></summary><div class="source-list"><?php foreach($sources as $s):?><?php if(!empty($s['url'])):?><a href="<?=e($s['url'])?>" target="_blank" rel="noopener"><strong><?=e($s['title']??$s['publisher']??'Source')?></strong><span><?=e($s['publisher']??'')?></span><small><?=e($s['url'])?></small></a><?php endif;?><?php endforeach;?><?php if(!$sources):?><p class="muted">This is a sample report and does not pretend demo records are live citations. Refresh it with AI research to populate sources.</p><?php endif;?></div></details>
<?php endif;?>
</div></section>
<?php require __DIR__.'/partials/footer.php';?>
