<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$service=new DestinationOwnerService($pdo);
$destinationId=(int)($_GET['destination_id']??0);$d=$destinationId?$service->destination($destinationId):null;
if(!$d || ($service->ready() && (($d['publication_status']??'draft')!=='published' || ($d['status']??'draft')!=='active'))){http_response_code(404);$title='Destination not found — Vacation Brain';require __DIR__.'/partials/header.php';?><section class="dashboard"><div class="shell"><div class="dashboard-card"><h1>That destination is not currently published.</h1><a class="button secondary" href="<?=e(app_url('destinations.php'))?>">Back to destinations</a></div></div></section><?php require __DIR__.'/partials/footer.php';exit;}
if($service->ready())$service->logEngagement($destinationId,$userId,'view',['source'=>'official_listing']);
$tripTypes=$service->ready()?$service->tripTypes($destinationId):[];$tripCatalog=$service->tripTypeCatalog();$hasReport=db_table_exists('destination_reports');$gallery=[];
if(db_table_exists('destination_gallery_images')){$stmt=$pdo->prepare('SELECT * FROM destination_gallery_images WHERE destination_catalog_id=? ORDER BY sort_order,id LIMIT 12');$stmt->execute([$destinationId]);$gallery=$stmt->fetchAll()?:[];}
$pageStyles=['assets/destination-owner.css'];$title=$d['name'].' — Vacation Brain';$metaDescription=trim((string)($d['short_description']??''))?:'Explore '.$d['name'].' with Vacation Brain.';$ogImage=media_url((string)($d['hero_image_url']??''));require __DIR__.'/partials/header.php';
?>
<section class="dashboard destination-owner-page"><div class="shell">
<div class="destination-owner-head"><div><div class="eyebrow"><?=!empty($d['owner_verified'])?'Verified official listing':'Vacation Brain destination'?></div><h1><?=e($d['name'])?></h1><p class="muted"><?=e(trim(implode(' · ',array_filter([$d['city'],$d['region'],$d['country']]))))?></p></div><div class="destination-owner-actions"><a class="button secondary small" href="<?=e(app_url('destinations.php'))?>">← Destinations</a><?php if($service->canManage($userId,$destinationId)):?><a class="button secondary small" href="<?=e(app_url('destination-dashboard.php?destination_id='.$destinationId))?>">Manage listing</a><?php endif;?></div></div>
<article class="destination-owner-hero <?=!empty($d['hero_image_url'])?'has-image':''?>" style="min-height:430px;<?php if(!empty($d['hero_image_url'])):?>background-image:url('<?=e(media_url((string)$d['hero_image_url']))?>')<?php endif;?>"><div class="destination-owner-pills"><?php foreach($tripTypes as $type):?><span class="destination-owner-pill"><?=e($tripCatalog[$type['trip_type']]['label']??$type['trip_type'])?><?=$type['is_primary']?' · Primary':''?></span><?php endforeach;?></div><h2><?=e($d['name'])?></h2><p><?=e((string)($d['short_description']??''))?></p></article>
<div class="destination-owner-grid" style="margin-top:18px"><div class="destination-owner-stack">
<article class="dashboard-card"><span class="eyebrow">Official destination profile</span><h2>About <?=e($d['name'])?></h2><?php if(!empty($d['description'])):?><p><?=nl2br(e((string)$d['description']))?></p><?php else:?><p class="muted">The destination owner has not added a full description yet.</p><?php endif;?><?php if(!empty($d['official_highlights'])):?><h3>Official highlights</h3><p><?=nl2br(e((string)$d['official_highlights']))?></p><?php endif;?></article>
<?php if($gallery):?><article class="dashboard-card"><h2>Destination gallery</h2><div class="destination-report-gallery"><?php foreach($gallery as $img):?><figure><img src="<?=e(media_url((string)$img['image_url']))?>" alt="<?=e((string)($img['caption']?:$d['name']))?>" loading="lazy"><figcaption><?=e((string)($img['caption']??''))?></figcaption></figure><?php endforeach;?></div></article><?php endif;?>
<?php if($hasReport):?><article class="dashboard-card"><div class="eyebrow">Vacation Brain research</div><h2>Want the deeper trip intelligence?</h2><p class="muted">Weather, lodging, restaurants, things to do, upcoming events, review signals and research sources live in the Vacation Brain report rather than the owner-controlled listing.</p><a class="button primary" href="<?=e(app_url('destination-report.php?destination_id='.$destinationId))?>">Open destination research</a></article><?php endif;?>
</div><aside class="destination-owner-stack">
<article class="dashboard-card"><h2>Trip snapshot</h2><?php foreach([['Typical stay',$d['typical_duration']??''],['Best season',$d['best_season']??''],['Price range',$d['price_range']??''],['Best for',$d['best_for']??''],['Vibe',$d['vibe']??'']] as [$label,$value]):if(trim((string)$value)==='')continue;?><div class="destination-owner-team-row"><strong><?=e($label)?></strong><span><?=e((string)$value)?></span></div><?php endforeach;?></article>
<?php if(!empty($d['transportation_notes'])||!empty($d['address'])):?><article class="dashboard-card"><h2>Getting there</h2><?php if(!empty($d['address'])):?><p><strong>Visitor area / address</strong><br><?=e((string)$d['address'])?></p><?php endif;?><?php if(!empty($d['transportation_notes'])):?><p class="muted"><?=nl2br(e((string)$d['transportation_notes']))?></p><?php endif;?></article><?php endif;?>
<article class="dashboard-card"><h2>Official links</h2><div class="destination-owner-actions"><?php if(!empty($d['website_url'])):?><a class="button secondary small" href="<?=e(app_url('destination-go.php?destination_id='.$destinationId.'&type=website'))?>">Official website ↗</a><?php endif;?><?php if(!empty($d['booking_url'])):?><a class="button primary small" href="<?=e(app_url('destination-go.php?destination_id='.$destinationId.'&type=booking'))?>">Book / reserve ↗</a><?php endif;?></div><?php if(!empty($d['contact_email'])):?><p class="muted small">Contact: <a href="mailto:<?=e((string)$d['contact_email'])?>"><?=e((string)$d['contact_email'])?></a></p><?php endif;?><?php if(!empty($d['contact_phone'])):?><p class="muted small"><?=e((string)$d['contact_phone'])?></p><?php endif;?></article>
<article class="dashboard-card"><h2>Plan with Vacation Brain</h2><div class="destination-owner-actions"><a class="button primary small" href="<?=e(app_url('vacation-yourself.php?destination_id='.$destinationId))?>">Show Me There</a><a class="button secondary small" href="<?=e(app_url('agent.php'))?>">Ask the brain</a></div></article>
<?php if(!$service->canManage($userId,$destinationId)):?><article class="dashboard-card"><h2>Represent this destination?</h2><p class="muted small">Verified owners can maintain the official listing and assign destination managers.</p><a class="text-link" href="<?=e(app_url('destination-claim.php?destination_id='.$destinationId))?>">Claim this destination →</a></article><?php endif;?>
</aside></div></div></section>
<?php require __DIR__.'/partials/footer.php';
