<?php
require __DIR__.'/app/bootstrap.php';$userId=require_auth();$pdo=db();$service=new DreamService($pdo);$id=(int)($_GET['id']??0);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$action=(string)($_POST['action']??'update');if($action==='add_item')$service->addItem($userId,$id,$_POST);elseif($action==='delete_item')$service->deleteItem($userId,$id,(int)($_POST['item_id']??0));else $service->update($userId,$id,$_POST);flash('success','Dream updated. This is how it starts.');redirect('dream-trip.php?id='.$id);}catch(Throwable $e){$error=$e->getMessage();}}
$trip=$service->get($userId,$id,true);if(!$trip){http_response_code(404);exit('Dream trip not found.');}$success=flash('success');$title=$trip['name'].' — Vacation Brain';require __DIR__.'/partials/header.php';
?>
<section class="dashboard"><div class="shell narrow"><a class="back-link" href="<?=e(app_url('dream.php'))?>">← All dream trips</a><?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="dream-hero"><span><?=e($trip['status_label'])?></span><h1><?=e($trip['name'])?></h1><p><?=e($trip['destination_name']?:'Destination TBD')?></p><div class="dream-heat"><strong><?=e($trip['temperature'])?></strong><div class="trait-meter"><span style="width:<?=(int)$trip['booking_readiness']?>%"></span></div><small>Vacation Brain is quietly tracking how real this dream is getting.</small></div></div>
<div class="mini-grid"><article class="dashboard-card"><h2>Dream settings</h2><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="update"><label>Trip nickname<input name="name" value="<?=e($trip['name'])?>"></label><label>Destination<input name="destination" value="<?=e($trip['destination_name'])?>"></label><label>Status<select name="status"><?php foreach(['fantasy'=>'Daydreaming','maybe'=>'Maybe someday','considering'=>'Considering it','serious'=>'This is getting serious','planning'=>'Planning-ish','booked'=>'Booked','completed'=>'Been there'] as $v=>$l):?><option value="<?=$v?>" <?=$trip['status']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>Travelers<input type="number" min="1" max="30" name="travelers" value="<?=(int)$trip['travelers']?>"></label><label>Imaginary budget<input type="number" min="0" step="1" name="target_budget" value="<?=e($trip['target_budget']!==null?(string)$trip['target_budget']:'')?>" placeholder="2000"></label><label>Dream intensity<select name="dream_level"><?php for($n=1;$n<=5;$n++):?><option value="<?=$n?>" <?=(int)$trip['dream_level']===$n?'selected':''?>><?=$n?> / 5</option><?php endfor;?></select></label><label>Notes<textarea name="description" rows="4" placeholder="Why this keeps showing up in your head..."><?=e($trip['description'])?></textarea></label><button class="button secondary">Save dream</button></form></article>
<article class="dashboard-card"><h2>Add to the fantasy</h2><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add_item"><label>Type<select name="item_type"><option value="idea">Idea</option><option value="hotel">Hotel</option><option value="food">Food</option><option value="activity">Activity</option><option value="experience">Experience</option><option value="flight">Flight thought</option></select></label><label>What?<input name="title" placeholder="Pool with swim-up bar" required></label><label>Imaginary price<input type="number" min="0" step=".01" name="price" placeholder="0"></label><label>Notes<textarea name="notes" rows="3" placeholder="Important scientific observations"></textarea></label><button class="button primary">Save idea</button></form></article></div>
<div class="dashboard-card" style="margin-top:20px"><h2>Things currently living in this trip</h2><?php if(!$trip['items']):?><p class="muted">Nothing yet. The trip is still mostly vibes.</p><?php else:?><div class="dream-items"><?php foreach($trip['items'] as $item):?><div><span><?=e(strtoupper($item['item_type']))?></span><strong><?=e($item['title'])?></strong><?php if($item['price']!==null):?><small>$<?=number_format((float)$item['price'],2)?></small><?php endif;?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete_item"><input type="hidden" name="item_id" value="<?=(int)$item['id']?>"><button class="text-button">remove</button></form></div><?php endforeach;?></div><?php endif;?></div>
</div></section><?php require __DIR__.'/partials/footer.php';?>
