<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$service=new DreamService($pdo);$error='';
$selectedContext=[];try{$selectedContext=(new DashboardDestinationContextService($pdo))->selected($userId);}catch(Throwable){}
$memorySeed=[];$memoryId=(int)($_GET['memory_id']??0);if($memoryId>0){try{$graph=new TravelerMemoryGraphService($pdo);if($graph->ready())$memorySeed=$graph->nextTripSeed($userId,$memoryId);}catch(Throwable){} }
$prefillDestination=trim((string)($_GET['destination']??($memorySeed['destination']??'')));$prefillCatalogId=(int)($_GET['destination_id']??0);
if($prefillDestination===''&&$prefillCatalogId>0&&db_table_exists('destination_catalog')){$stmt=$pdo->prepare('SELECT name FROM destination_catalog WHERE id=? LIMIT 1');$stmt->execute([$prefillCatalogId]);$prefillDestination=(string)($stmt->fetchColumn()?:'');}
if($prefillDestination===''&&!empty($selectedContext[0]['destination_name']))$prefillDestination=(string)$selectedContext[0]['destination_name'];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$id=$service->create($userId,$_POST);redirect('dream-trip.php?id='.$id);}catch(Throwable $e){$error=$e->getMessage();}}
$pageStyles=['assets/trip-intelligence.css'];$title='New Trip — Vacation Brain';require __DIR__.'/partials/header.php';
?>
<section class="dashboard trip-new-page"><div class="shell narrow">
<a class="back-link" href="<?=e($memoryId>0?app_url('traveler-memory.php'):app_url('dream.php'))?>">← <?=$memoryId>0?'Traveler Memory':'All trips'?></a>
<div class="trip-new-head"><span class="eyebrow"><?=$memoryId>0?'Do this again, better':'New trip'?></span><h1><?=$memoryId>0?'Keep the good parts. Fix the annoying parts.':'Give the brain something to work with.'?></h1><p class="muted"><?=$memoryId>0?'Vacation Brain prefilled this plan from structured learning on a completed trip. Review everything before creating the new trip.':'Set the basic trip facts once. Weather, events, local places and flight intelligence will build around them on the trip dashboard.'?></p></div>
<?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<form class="dashboard-card trip-new-form" method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="status" value="planning">
<fieldset><legend>Where are we pretending this is definitely happening?</legend><div class="trip-form-grid two"><label>Trip nickname<input class="input" name="name" value="<?=e((string)($_POST['name']??($memorySeed['name']??'')))?>" placeholder="Cabo Eventually"></label><label>Destination<input class="input" name="destination" value="<?=e((string)($_POST['destination']??$prefillDestination))?>" placeholder="Cabo San Lucas" required></label></div>
<?php if($selectedContext):?><div class="trip-context-picks"><span>Selected on Dashboard:</span><?php foreach(array_slice($selectedContext,0,5) as $ctx):?><button type="button" data-trip-destination-pick="<?=e((string)$ctx['destination_name'])?>"><?=e((string)$ctx['destination_name'])?></button><?php endforeach;?></div><?php endif;?>
<div class="trip-form-grid two"><label>Starting from<input class="input" name="origin_name" value="<?=e((string)($_POST['origin_name']??''))?>" placeholder="Phoenix, AZ or PHX"></label><div class="trip-form-grid two compact"><label>Origin airport / city code<input class="input" name="origin_iata" maxlength="3" value="<?=e((string)($_POST['origin_iata']??''))?>" placeholder="PHX"></label><label>Destination airport / city code<input class="input" name="destination_iata" maxlength="3" value="<?=e((string)($_POST['destination_iata']??''))?>" placeholder="SJD"></label></div></div></fieldset>
<fieldset><legend>When and how serious?</legend><div class="trip-form-grid four"><label>Depart<input class="input" type="date" name="start_date" value="<?=e((string)($_POST['start_date']??''))?>"></label><label>Return<input class="input" type="date" name="end_date" value="<?=e((string)($_POST['end_date']??''))?>"></label><label>Travelers<input class="input" type="number" min="1" max="30" name="travelers" value="<?=e((string)($_POST['travelers']??($memorySeed['travelers']??2)))?>"></label><label>Target budget<input class="input" type="number" min="0" step="1" name="target_budget" value="<?=e((string)($_POST['target_budget']??($memorySeed['target_budget']??'')))?>" placeholder="3000"></label></div><div class="trip-form-grid two"><label>Trip intensity<select class="input" name="dream_level"><?php foreach([1=>'Passing thought',2=>'Definitely thinking about it',3=>'Screenshots exist',4=>'This is getting serious',5=>'Emotionally packed'] as $n=>$label):?><option value="<?=$n?>" <?=(int)($_POST['dream_level']??3)===$n?'selected':''?>><?=$n?> — <?=e($label)?></option><?php endforeach;?></select></label><label>Currency<select class="input" name="currency"><?php $selectedCurrency=(string)($_POST['currency']??($memorySeed['currency']??'USD'));foreach(['USD','CAD','EUR','GBP','MXN'] as $c):?><option value="<?=$c?>" <?=$selectedCurrency===$c?'selected':''?>><?=$c?></option><?php endforeach;?></select></label></div></fieldset>
<label>What matters about this trip?<textarea class="input" name="description" rows="4" placeholder="Beach, nightlife, food, quiet mornings, no rental car, whatever matters..."><?=e((string)($_POST['description']??($memorySeed['description']??'')))?></textarea></label>
<?php if($memorySeed):?><div class="alert success"><strong>Traveler Memory seed:</strong> This draft uses only structured completed-trip learning and your prior budget/traveler count. Private trip notes were not copied.</div><?php endif;?>
<div class="trip-new-actions"><a class="button secondary" href="<?=e($memoryId>0?app_url('traveler-memory.php'):app_url('dream.php'))?>">Cancel</a><button class="button primary" type="submit">Create trip dashboard →</button></div></form>
</div></section>
<script>document.querySelectorAll('[data-trip-destination-pick]').forEach(function(b){b.addEventListener('click',function(){var i=document.querySelector('input[name="destination"]');if(i){i.value=b.getAttribute('data-trip-destination-pick')||'';i.focus();}});});</script>
<?php require __DIR__.'/partials/footer.php';?>
