<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$service=new TravelMatchService($pdo);$profile=$service->profile($userId);$success=flash('success');$error=flash('error');
if($profile&&!empty($profile['enabled']))$service->touchActivity($userId);
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$postAction=(string)($_POST['action']??'');
    if($postAction==='invite'){$invite=$service->createInvite($userId);$_SESSION['last_match_invite']=$invite['url'];redirect('matching.php');}
    if($postAction==='feedback'){
        try{$service->recordQualityFeedback($userId,(int)($_POST['user']??0),'pass',(string)($_POST['reason']??'not_interested'));flash('success','Thanks. Vacation Brain will quietly learn from that.');}catch(Throwable $e){flash('error',$e->getMessage());}
        $qs=$_POST['return_query']??'';redirect('matching.php'.($qs!==''?'?'.$qs:''));
    }
    if(in_array($postAction,['like','pass'],true)){
        try{$target=(int)($_POST['user']??0);$result=$service->act($userId,$target,$postAction);if($postAction==='pass')$_SESSION['last_pass_target']=$target;flash('success',!empty($result['new_match'])?'It’s a Travel Match.':($postAction==='like'?'Travel Like sent.':'Passed. Your imaginary itinerary has been cancelled.'));}
        catch(Throwable $e){flash('error',$e->getMessage());}
        $qs=$_POST['return_query']??'';redirect('matching.php'.($qs!==''?'?'.$qs:''));
    }
}
$filters=[
    'age_min'=>(int)($_GET['age_min']??($profile['min_partner_age']??18)),
    'age_max'=>(int)($_GET['age_max']??($profile['max_partner_age']??99)),
    'scope'=>(string)($_GET['scope']??($profile['discovery_scope']??'anywhere')),
    'pace'=>(string)($_GET['pace']??'any'),
    'recent'=>!empty($_GET['recent']),
];
$returnQuery=http_build_query(array_filter(['age_min'=>$filters['age_min'],'age_max'=>$filters['age_max'],'scope'=>$filters['scope'],'pace'=>$filters['pace'],'recent'=>$filters['recent']?1:null],fn($v)=>$v!==null&&$v!==''));
$readiness=$profile?$service->profileReadiness($userId,true):['score'=>0,'ready'=>false,'missing'=>[]];
$candidates=$profile&&!empty($profile['enabled'])?$service->candidates($userId,30,$filters):[];
$dailyPicks=$profile&&!empty($profile['enabled'])?$service->dailyPicks($userId,$candidates,8):[];$dailyIds=array_map(fn($r)=>(int)$r['user_id'],$dailyPicks);$more=array_values(array_filter($candidates,fn($r)=>!in_array((int)$r['user_id'],$dailyIds,true)));
$matches=$profile&&!empty($profile['enabled'])?$service->matches($userId):[];$unseenMatch=$profile&&!empty($profile['enabled'])?$service->unseenMatch($userId):null;if($unseenMatch)$service->markMatchSeen((int)$unseenMatch['id'],$userId);
$inviteUrl=$_SESSION['last_match_invite']??null;unset($_SESSION['last_match_invite']);$lastPass=(int)($_SESSION['last_pass_target']??0);unset($_SESSION['last_pass_target']);$title='Travel Matching';require __DIR__.'/partials/header.php';
function render_match_card(array $c,string $returnQuery): void {$arch=$c['archetype']??null;$location=implode(', ',array_filter([$c['home_city']??'',$c['home_region']??'']));$cardPhotos=$c['photos']??[];if(!$cardPhotos&&!empty($c['photo_url']))$cardPhotos=[(string)$c['photo_url']];
?>
<article class="person-card discovery-person-card"><div class="person-photo card-photo-gallery" data-card-gallery data-index="0"><?php if($cardPhotos):?><div class="card-photo-stage"><?php foreach($cardPhotos as $photoIndex=>$photoUrl):?><img src="<?=e($photoUrl)?>" alt="<?=e(($c['display_name']?:'Vacation Brain').' profile photo '.($photoIndex+1))?>" data-card-photo <?= $photoIndex===0?'':'hidden' ?>><?php endforeach;?></div><?php if(count($cardPhotos)>1):?><button class="card-photo-nav prev" type="button" data-card-prev aria-label="Previous photo">‹</button><button class="card-photo-nav next" type="button" data-card-next aria-label="Next photo">›</button><div class="card-photo-progress"><span data-card-counter>1 / <?=count($cardPhotos)?></span><div class="card-photo-dots"><?php foreach($cardPhotos as $photoIndex=>$photoUrl):?><i class="<?= $photoIndex===0?'active':'' ?>" data-card-dot></i><?php endforeach;?></div></div><?php endif;?><?php else:?><div class="avatar-placeholder"><?=e(strtoupper(substr($c['display_name']??'V',0,1)))?></div><?php endif;?><?php if(!empty($c['activity_label'])):?><span class="activity-cue"><?=e($c['activity_label'])?></span><?php endif;?></div><div class="person-copy"><div class="person-kicker"><span><?=e(ucwords(str_replace('_',' ',$c['match_mode'])))?></span><b><?=(int)$c['age']?></b><?php if($location):?><em><?=e($location)?></em><?php endif;?></div><h3><?=e($c['display_name']?:'Vacation Brain')?></h3><div class="person-tags"><?php if($arch):?><b><?=e($arch['name'])?></b><?php endif;?><b><?=e(ucfirst($c['travel_pace']))?> pace</b><?php if($c['favorite_destination']):?><b>Dreaming: <?=e($c['favorite_destination'])?></b><?php endif;?></div><?php if(!empty($c['prompt_preview'])):?><div class="discovery-prompt"><span><?=e($c['prompt_preview']['label'])?></span><p>“<?=e($c['prompt_preview']['answer'])?>”</p></div><?php else:?><p class="discovery-bio"><?=e($c['bio']?:($arch['description']??'Vacation opinions available upon further investigation.'))?></p><?php endif;?><?php if(!empty($c['rank_reasons'])):?><div class="curation-reasons"><?php foreach(array_slice($c['rank_reasons'],0,2) as $why):?><span><?=e($why)?></span><?php endforeach;?></div><?php endif;?><button class="profile-reveal-link button-link" type="button" data-profile-modal-url="<?=e(app_url('match-user.php?user='.(int)$c['user_id'].'&modal=1'))?>">View Profile · See compatibility →</button><form method="post" class="person-card-actions"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="user" value="<?=(int)$c['user_id']?>"><input type="hidden" name="return_query" value="<?=e($returnQuery)?>"><button class="match-pass" name="action" value="pass" aria-label="Pass">×</button><button class="match-like" name="action" value="like" aria-label="Travel Like">♥</button></form></div></article>
<?php }
?>
<section class="match-page"><div class="shell">
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="match-hero"><div><span class="eyebrow">Travel Matching</span><h1>Find someone whose vacation opinions are worth investigating.</h1><p>Vacation Brain curates the people worth opening first. Compatibility stays hidden until you choose to look deeper.</p><div class="today-actions"><a class="button primary" href="<?=e(app_url($profile?'match-profile.php':'match-onboarding.php'))?>"><?=$profile?'Edit my Travel Match profile':'Start Travel Match onboarding'?></a><?php if($profile&&!empty($profile['enabled'])):?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="invite"><button class="button secondary">Invite someone to compare</button></form><?php endif;?></div></div><div class="match-hero-score"><span>PROFILE READINESS</span><strong><?= (int)$readiness['score'] ?>%</strong><small><?=!empty($readiness['ready'])?'Ready for discovery. Vacation Brain has enough evidence to be nosy.':'Finish a few basics before Vacation Brain puts you in circulation.'?></small></div></div>
<?php if($inviteUrl):?><div class="share-invite"><div><span class="eyebrow">Invite created</span><strong>Send this to someone whose vacation opinions need auditing.</strong></div><input value="<?=e($inviteUrl)?>" readonly onclick="this.select()"><button class="button secondary" data-copy="<?=e($inviteUrl)?>" type="button">Copy link</button></div><?php endif;?>
<?php if($lastPass>0):?><article class="pass-feedback"><div><span class="eyebrow">Tune your matches</span><strong>Why wasn’t that profile for you?</strong><small>Optional. Vacation Brain uses this only to improve future discovery.</small></div><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="feedback"><input type="hidden" name="user" value="<?=$lastPass?>"><input type="hidden" name="return_query" value="<?=e($returnQuery)?>"><?php foreach(['too_far'=>'Too far away','different_budget'=>'Different budget','different_pace'=>'Different trip pace','not_enough_common'=>'Not enough in common','not_interested'=>'Just not interested'] as $v=>$l):?><button name="reason" value="<?=$v?>"><?=e($l)?></button><?php endforeach;?></form></article><?php endif;?>
<?php if(!$profile):?><article class="match-empty"><span class="eyebrow">Opt-in feature</span><h2>Your dating profile is not secretly active.</h2><p>Complete the short Travel Matching setup, then Vacation Brain can start curating people based on the profile you already built through swiping.</p><a class="button primary" href="<?=e(app_url('match-onboarding.php'))?>">Start Travel Match Onboarding →</a></article>
<?php elseif(empty($profile['enabled'])):?><article class="match-empty"><span class="eyebrow">Currently unenrolled</span><h2>Your Travel Match profile is off the market.</h2><p>Your existing matches and messages are preserved. Re-enroll whenever you want new people to discover you.</p><div class="today-actions"><a class="button primary" href="<?=e(app_url('match-profile.php'))?>">Review & Re-enroll</a><a class="button secondary" href="<?=e(app_url('match-contacts.php'))?>">Existing Matches</a></div></article>
<?php else:?>
<?php if($matches):?><div class="section-head"><div><span class="eyebrow">Mutual</span><h2>Your Travel Matches</h2></div><a href="<?=e(app_url('match-contacts.php'))?>">Matches & Messages →</a></div><div class="mutual-strip"><?php foreach($matches as $m):$p=$m['partner'];if(!$p)continue;?><a href="<?=e(app_url('match-chat.php?match='.(int)$m['id']))?>"><div class="match-avatar small"><?php if($p['photo_url']):?><img src="<?=e($p['photo_url'])?>" alt=""><?php else:?><span><?=e(strtoupper(substr($p['display_name']??'V',0,1)))?></span><?php endif;?></div><strong><?=e($p['display_name']?:'Vacation Brain')?></strong><span class="mutual-status">Message</span></a><?php endforeach;?></div><?php endif;?>
<div class="section-head discovery-head"><div><span class="eyebrow">Today’s curated picks</span><h2>Vacation Brain found <?=count($dailyPicks)?> people worth investigating.</h2><p class="muted">A stable daily batch ranked from your travel profile and what you’ve passed on before.</p></div><a href="<?=e(app_url('match-profile.php'))?>">Matching settings →</a></div>
<form method="get" class="match-filter-bar"><div><label>Age</label><span><input type="number" name="age_min" min="18" max="99" value="<?=e((string)$filters['age_min'])?>"><i>to</i><input type="number" name="age_max" min="18" max="99" value="<?=e((string)$filters['age_max'])?>"></span></div><div><label>Location</label><select name="scope"><?php foreach(['anywhere'=>'Anywhere','country'=>'Same country','region'=>'Same region','city'=>'Same city'] as $v=>$l):?><option value="<?=$v?>" <?=$filters['scope']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><div><label>Travel pace</label><select name="pace"><?php foreach(['any'=>'Any pace','slow'=>'Slow','balanced'=>'Balanced','packed'=>'Packed'] as $v=>$l):?><option value="<?=$v?>" <?=$filters['pace']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><label class="filter-check"><input type="checkbox" name="recent" value="1" <?=$filters['recent']?'checked':''?>> Active this week</label><button class="button secondary" type="submit">Apply</button></form>
<?php if(!$dailyPicks):?><article class="match-empty"><h2>No curated profiles fit those filters today.</h2><p>Broaden discovery or invite somebody whose travel opinions deserve formal review.</p></article><?php else:?><div class="match-grid discovery-grid-cards"><?php foreach($dailyPicks as $c)render_match_card($c,$returnQuery);?></div><?php endif;?>
<?php if($more):?><details class="more-discovery"><summary>Keep exploring beyond today’s picks <span><?=count($more)?> more</span></summary><div class="match-grid discovery-grid-cards"><?php foreach($more as $c)render_match_card($c,$returnQuery);?></div></details><?php endif;?>
<div class="profile-full-modal" data-profile-full-modal aria-hidden="true"><div class="profile-full-modal-shell"><div class="profile-full-modal-bar"><strong>Travel Match Profile</strong><button type="button" data-profile-full-close aria-label="Close profile">×</button></div><iframe title="Travel Match extended profile" data-profile-full-frame></iframe></div></div>
<?php endif;?>
<?php if($unseenMatch && !empty($unseenMatch['partner'])):$up=$unseenMatch['partner'];$uc=$unseenMatch['compatibility'];?><div class="travel-match-modal" data-match-modal><div class="travel-match-modal-card"><button class="match-modal-close" type="button" data-match-modal-close aria-label="Close">×</button><span class="eyebrow">It’s a Travel Match</span><div class="match-modal-avatars"><div class="match-avatar"><?php if(!empty($profile['photo_url'])):?><img src="<?=e($profile['photo_url'])?>" alt=""><?php else:?><span><?=e(strtoupper(substr(current_user()['display_name']??'Y',0,1)))?></span><?php endif;?></div><div class="match-heart">♥</div><div class="match-avatar"><?php if($up['photo_url']):?><img src="<?=e($up['photo_url'])?>" alt=""><?php else:?><span><?=e(strtoupper(substr($up['display_name']??'V',0,1)))?></span><?php endif;?></div></div><h2>You matched with <?=e($up['display_name']?:'another Vacation Brain')?>.</h2><p><?=e($uc['warning'])?></p><small class="match-added-note">Added to Matches &amp; Messages. Open the profile when you want the compatibility score.</small><div class="match-modal-actions"><a class="button primary" href="<?=e(app_url('match-chat.php?match='.(int)$unseenMatch['id']))?>">Send a Message</a><button class="button secondary" type="button" data-match-modal-close>Keep Browsing</button></div></div></div><?php endif;?>
</div></section><?php require __DIR__.'/partials/footer.php';?>
