<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$service=new TravelMatchService($pdo);$users=new UserService($pdo);$upload=new UploadService(__DIR__);$profile=$service->extendedProfile($userId);$account=$users->account($userId);$error='';
if($profile&&!empty($profile['onboarding_completed']))redirect('match-profile.php');
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$_POST['enrollment_status']='enrolled';
    try{
        $beforeAvatar=(string)($account['avatar_url']??'');
        $file=$_FILES['primary_photo']??null;
        if($file && (int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){
            $newUrl=$upload->storeImage($file,$userId,'avatars');
            if($newUrl){$users->updateAvatar($userId,$newUrl);if($beforeAvatar!==''&&$beforeAvatar!==$newUrl)$upload->deleteLocal($beforeAvatar);$account=$users->account($userId);}
        }
        $primary=(string)($account['avatar_url']??'');
        if($primary==='')throw new InvalidArgumentException('Upload a profile picture to continue. This becomes your account and Travel Match primary photo.');
        $_POST['photo_1']=$primary;
        $service->saveProfile($userId,$_POST);$readiness=$service->profileReadiness($userId,true);if(!$readiness['ready'])throw new InvalidArgumentException('Your profile still needs: '.implode(', ',$readiness['missing']).'.');flash('success','Travel Matching is ready. Vacation Brain can now start investigating people for you.');redirect('matching.php');
    }
    catch(Throwable $e){$error=$e->getMessage();$profile=$service->extendedProfile($userId);$account=$users->account($userId);}
}
$p=$profile?:[];$photos=$p['photos']??[];$prompts=$p['prompts']??[];$catalog=$service->promptCatalog();$primaryPhoto=(string)($account['avatar_url']??($photos[0]['photo_url']??($p['photo_url']??'')));$title='Travel Match Onboarding';require __DIR__.'/partials/header.php';
?>
<section class="match-page onboarding-page"><div class="shell narrow-wide">
<div class="onboarding-hero"><span class="eyebrow">Travel Matching · 18+ · Opt-in</span><h1>Vacation Brain already knows your travel opinions. We just need the dating-profile parts.</h1><p>Four short steps. No match percentage yet. No profile goes live until you finish and enroll.</p><div class="onboarding-progress"><i data-onboard-progress></i></div></div>
<?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<form method="post" enctype="multipart/form-data" class="onboarding-form" data-onboarding-form><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>">
<section class="onboarding-step active" data-onboard-step="0"><span class="step-count">1 of 4</span><h2>Who should Vacation Brain introduce you to?</h2><div class="match-form-grid"><div class="field"><label>Your age</label><input type="number" name="age" min="18" max="99" value="<?=e(isset($p['age'])?(string)$p['age']:'')?>" required></div><div class="field"><label>My gender</label><select name="gender_identity" required><option value="prefer_not">Prefer not to say</option><option value="woman" <?=($p['gender_identity']??'')==='woman'?'selected':''?>>Woman</option><option value="man" <?=($p['gender_identity']??'')==='man'?'selected':''?>>Man</option><option value="nonbinary" <?=($p['gender_identity']??'')==='nonbinary'?'selected':''?>>Nonbinary</option></select></div><div class="field"><label>Preferred partner gender</label><select name="partner_gender"><option value="everyone">Everyone</option><option value="women" <?=($p['partner_gender']??'')==='women'?'selected':''?>>Women</option><option value="men" <?=($p['partner_gender']??'')==='men'?'selected':''?>>Men</option><option value="nonbinary" <?=($p['partner_gender']??'')==='nonbinary'?'selected':''?>>Nonbinary people</option></select></div><div class="field"><label>I’m here for</label><select name="match_mode"><option value="dating">Dating</option><option value="travel_buddy">Travel buddy</option><option value="either" selected>Either</option></select></div></div><div class="onboard-actions"><button class="button primary" type="button" data-onboard-next>Next →</button></div></section>
<section class="onboarding-step" data-onboard-step="1"><span class="step-count">2 of 4</span><h2>Give people a face and a destination.</h2><div class="shared-profile-photo"><div class="account-avatar match-onboard-avatar"><?php if($primaryPhoto!==''):?><img src="<?=e($primaryPhoto)?>" alt="Your profile picture"><?php else:?><span><?=e(user_initials(current_user()['display_name']??''))?></span><?php endif;?></div><div class="field grow"><label><?= $primaryPhoto!==''?'Change profile picture':'Upload profile picture' ?></label><input type="file" name="primary_photo" accept="image/jpeg,image/png,image/webp" <?= $primaryPhoto===''?'required':'' ?>><small>This is the same profile picture used in Account Settings and as your primary Travel Match photo. JPEG, PNG, or WebP · 8 MB max.</small></div></div><div class="match-form-grid"><div class="field"><label>City</label><input name="home_city" value="<?=e($p['home_city']??'')?>" placeholder="Phoenix" required></div><div class="field"><label>State / region</label><input name="home_region" value="<?=e($p['home_region']??'')?>" placeholder="Arizona"></div><div class="field"><label>Country</label><input name="home_country" value="<?=e($p['home_country']??'')?>" placeholder="United States" required></div><div class="field"><label>Dream destination</label><input name="favorite_destination" value="<?=e($p['favorite_destination']??'')?>" placeholder="Cabo, Maui, Rome..." required></div></div><div class="onboard-actions"><button class="button secondary" type="button" data-onboard-prev>← Back</button><button class="button primary" type="button" data-onboard-next>Next →</button></div></section>
<section class="onboarding-step" data-onboard-step="2"><span class="step-count">3 of 4</span><h2>Give somebody a reason to open your profile.</h2><div class="field"><label>Vacation prompt</label><select name="prompt_key_1" required><option value="">Choose one</option><?php foreach($catalog as $k=>$label):?><option value="<?=e($k)?>" <?=($prompts[0]['prompt_key']??'')===$k?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></div><div class="field"><label>Your answer</label><textarea name="prompt_answer_1" rows="3" maxlength="500" required><?=e($prompts[0]['answer_text']??'')?></textarea></div><div class="field"><label>Short bio <span class="muted">optional</span></label><textarea name="bio" rows="3" maxlength="500" placeholder="Direct flights are a form of self-respect."><?=e($p['bio']??'')?></textarea></div><div class="onboard-actions"><button class="button secondary" type="button" data-onboard-prev>← Back</button><button class="button primary" type="button" data-onboard-next>Next →</button></div></section>
<section class="onboarding-step" data-onboard-step="3"><span class="step-count">4 of 4</span><h2>Set the travel boundaries before somebody suggests sunrise kayaking.</h2><div class="match-form-grid"><div class="field"><label>Travel pace</label><select name="travel_pace"><option value="slow">Slow</option><option value="balanced" selected>Balanced</option><option value="packed">Packed</option></select></div><div class="field"><label>Budget style</label><select name="budget_style"><option value="budget">Budget-conscious</option><option value="comfortable" selected>Comfortable</option><option value="premium">Premium when it matters</option></select></div><div class="field"><label>Partner age minimum</label><input type="number" name="min_partner_age" min="18" max="99" value="<?=e((string)($p['min_partner_age']??18))?>"></div><div class="field"><label>Partner age maximum</label><input type="number" name="max_partner_age" min="18" max="99" value="<?=e((string)($p['max_partner_age']??99))?>"></div></div><div class="dealbreaker-grid"><label class="check-row"><input type="checkbox" name="no_sunrise" value="1"> No 6 AM excursion people</label><label class="check-row"><input type="checkbox" name="budget_matters" value="1"> Budget compatibility matters</label><label class="check-row"><input type="checkbox" name="nightlife_ok" value="1"> Nightlife matters</label><label class="check-row"><input type="checkbox" name="spontaneous_ok" value="1"> Must survive plan changes</label></div><input type="hidden" name="discovery_scope" value="anywhere"><input type="hidden" name="show_activity_status" value="1"><div class="onboard-actions"><button class="button secondary" type="button" data-onboard-prev>← Back</button><button class="button primary" type="submit">Enroll My Travel Match Profile</button></div><p class="microcopy">Travel Matching is optional. You can unenroll at any time without deleting your Vacation Brain account or existing matches.</p></section>
</form></div></section>
<?php require __DIR__.'/partials/footer.php';?>
