<?php
require __DIR__.'/app/bootstrap.php';$token=(string)($_GET['token']??$_POST['token']??'');if($token==='')redirect('matching.php');$service=new TravelMatchService(db());$game=$service->gameByToken($token);if(!$game){http_response_code(404);exit('Compatibility game not found.');}
if(!auth_user_id()){$_SESSION['pending_match_game']=$token;$_SESSION['after_login']=$_SERVER['REQUEST_URI']??app_url('match-game.php?token='.$token);redirect('diagnosis.php');}
$userId=require_auth();$creator=(int)$game['creator_user_id'];$partner=$game['partner_user_id']?(int)$game['partner_user_id']:null;if($partner!==null && $userId!==$creator && $userId!==$partner){http_response_code(403);exit('This compatibility game was sent to someone else.');}
$me=$service->profile($userId);if(!$me || (empty($me['enabled']) && empty($game['match_id']))){$_SESSION['pending_match_game']=$token;flash('success','Enroll in Travel Matching so we can compare the answers.');redirect('match-profile.php');}
$catalog=$service->gameCatalog();$definition=$catalog[$game['game_type']]??null;if(!$definition)exit('Unknown compatibility game.');$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$answers=$_POST['answer']??[];$service->answerGame($game,$userId,is_array($answers)?$answers:[]);redirect('match-game.php?token='.$token);}catch(Throwable $e){$error=$e instanceof InvalidArgumentException?$e->getMessage():'We could not save those answers.';}}
$game=$service->gameByToken($token);$result=$service->gameResult($game);$stmt=db()->prepare('SELECT answers_json FROM travel_match_game_answers WHERE game_id=? AND user_id=?');$stmt->execute([$game['id'],$userId]);$mine=$stmt->fetchColumn();$answered=(bool)$mine;$otherId=$userId===$creator?($game['partner_user_id']?(int)$game['partner_user_id']:null):$creator;$other=$otherId?$service->profile($otherId):null;$title=$definition['title'];require __DIR__.'/partials/header.php';
?>
<section class="match-page"><div class="shell game-shell"><a class="back-link" href="<?=e(app_url(!empty($game['match_id'])?('match-space.php?match='.(int)$game['match_id']):'matching.php'))?>">← <?=!empty($game['match_id'])?'Match Space':'Travel Matching'?></a><div class="game-hero"><span class="eyebrow">Compatibility Game</span><h1><?=e($definition['title'])?></h1><p><?=e($definition['description'])?></p></div><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if($result):?><div class="game-result"><span>COMPATIBILITY RESULT</span><strong><?=$result['score']?>%</strong><h2><?=e($result['line'])?></h2><p><?=$result['same']?> of <?=$result['total']?> answers matched exactly.</p><?php if($result['differences']):?><div class="difference-list"><span>Potential arguments</span><?php foreach($result['differences'] as $d):?><b><?=e($d)?></b><?php endforeach;?></div><?php endif;?><button class="button secondary" data-copy="<?=e('We scored '.$result['score'].'% on Vacation Brain\'s '.$definition['title'].'. '.$result['line'])?>" type="button">Copy result</button></div>
<?php elseif($answered):?><div class="game-wait"><span class="eyebrow">Your answers are locked in</span><h2><?= $other?'Waiting for '.e($other['display_name']?:'the other Vacation Brain'):'Send this game to someone' ?>.</h2><p>We do not reveal anything until both people answer. Vacation diplomacy requires suspense.</p><input value="<?=e(app_url('match-game.php?token='.$token))?>" readonly onclick="this.select()"><button class="button secondary" data-copy="<?=e(app_url('match-game.php?token='.$token))?>" type="button">Copy game link</button></div>
<?php else:?><form method="post" class="game-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="token" value="<?=e($token)?>"><?php foreach($definition['questions'] as $i=>$q):?><fieldset><legend><span><?=($i+1)?></span><?=e($q['q'])?></legend><div class="game-options"><?php foreach($q['options'] as $key=>$label):?><label><input type="radio" name="answer[<?=e($q['key'])?>]" value="<?=e($key)?>" required><span><?=e($label)?></span></label><?php endforeach;?></div></fieldset><?php endforeach;?><button class="button primary" type="submit">Lock In My Answers →</button></form><?php endif;?></div></section><?php require __DIR__.'/partials/footer.php';?>
