<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$messageService=new TravelMessageService($pdo);$matchService=new TravelMatchService($pdo);$mineProfile=$matchService->profile($userId);if($mineProfile&&!empty($mineProfile['enabled']))$matchService->touchActivity($userId);$matchId=(int)($_GET['match']??$_POST['match']??0);$match=$messageService->match($matchId,$userId);
if(!$match||($match['status']??'')!=='active'){http_response_code(404);exit('Travel Match conversation not available.');}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=(string)($_POST['action']??'');if($action==='block'){$matchService->act($userId,(int)$match['partner_id'],'block');flash('success','Travel Match blocked and the conversation has been closed.');redirect('match-contacts.php');}if($action==='unmatch'){$matchService->unmatch($userId,$matchId,(string)($_POST['unmatch_reason']??'not_interested'));flash('success','Travel Match ended. The conversation is closed, but no safety report was created.');redirect('match-contacts.php');}}
$partner=$matchService->profile((int)$match['partner_id']);if(!$partner){http_response_code(404);exit('Travel Match profile not available.');}
$messages=$messageService->messages($matchId,$userId,0,100);$lastId=$messages?(int)end($messages)['id']:0;$comp=$matchService->compatibility($userId,(int)$match['partner_id']);$engagement=new MatchEngagementService($pdo);$icebreakers=$engagement->icebreakers($matchId,$userId,4);$streak=$engagement->streak($matchId,$userId);$starter=trim((string)($_GET['starter']??''));if(strlen($starter)>500)$starter=substr($starter,0,500);$success=flash('success');$error=flash('error');$title='Message '.($partner['display_name']?:'Travel Match');require __DIR__.'/partials/header.php';
$reactionLabels=['same'=>'Same','laugh'=>'😂','love'=>'♥','red_flag'=>'Red flag'];
?>
<section class="match-chat-page"><div class="shell chat-shell">
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="chat-topbar"><a class="back-link" href="<?=e(app_url('match-contacts.php'))?>">← Matches</a><a class="chat-person" href="<?=e(app_url('match-user.php?user='.(int)$match['partner_id']))?>"><div class="match-avatar small"><?php if($partner['photo_url']):?><img src="<?=e($partner['photo_url'])?>" alt=""><?php else:?><span><?=e(strtoupper(substr($partner['display_name']??'V',0,1)))?></span><?php endif;?></div><div><strong><?=e($partner['display_name']?:'Vacation Brain')?></strong><span><?=$comp['score']?>% Vacation Compatible</span></div></a><details class="chat-menu"><summary>•••</summary><div><a href="<?=e(app_url('match-space.php?match='.$matchId))?>">Match Space</a><a href="<?=e(app_url('compare.php?user='.(int)$match['partner_id']))?>">Compare brains</a><form method="post" action="<?=e(app_url('match-chat.php'))?>" class="chat-unmatch-form" onsubmit="return confirm('End this Travel Match? This closes the conversation but does not report or block them.')"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="match" value="<?=$matchId?>"><select name="unmatch_reason"><option value="not_interested">Just not a match</option><option value="too_far">Too far away</option><option value="different_budget">Different budget</option><option value="different_pace">Different trip pace</option><option value="not_enough_common">Not enough in common</option></select><button name="action" value="unmatch">Unmatch</button></form><form method="post" action="<?=e(app_url('match-chat.php'))?>" onsubmit="return confirm('Block this match and close the conversation?')"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="match" value="<?=$matchId?>"><button name="action" value="block">Block match</button></form></div></details></div>
<div class="chat-match-tools"><a href="<?=e(app_url('match-space.php?match='.$matchId))?>"><strong><?=$streak['current']?>-day shared streak</strong><span>Daily question, discoveries & games →</span></a></div><div class="chat-icebreakers"><span>Vacation Brain icebreakers</span><div><?php foreach($icebreakers as $line):?><button type="button" data-chat-starter="<?=e($line)?>"><?=e($line)?></button><?php endforeach;?></div></div>
<div class="match-chat" data-match-chat data-match-id="<?=$matchId?>" data-last-id="<?=$lastId?>" data-api="<?=e(app_url('match-message-api.php'))?>">
<div class="message-stream" data-message-stream>
<?php if(!$messages):?><div class="chat-empty" data-chat-empty><strong>It’s a Travel Match.</strong><span>Say hello, compare dream destinations, or immediately negotiate the airport arrival time.</span></div><?php endif;?>
<?php foreach($messages as $m):?><article class="match-message <?=$m['mine']?'mine':'theirs'?>" data-message-id="<?=(int)$m['id']?>"><?php if(!empty($m['parent_message_id'])):?><div class="message-reply-preview"><span>Replying to <?=e($m['parent_sender_name']?:'message')?></span><p><?=e(strlen((string)$m['parent_body'])>120?substr((string)$m['parent_body'],0,117).'…':(string)$m['parent_body'])?></p></div><?php endif;?><div class="bubble"><?=nl2br(e($m['body']))?></div><div class="message-footer"><time><?=e(date('M j · g:i A',strtotime($m['created_at'])))?></time><div class="message-tools"><button type="button" data-reply-message="<?=(int)$m['id']?>" data-reply-copy="<?=e(strlen((string)$m['body'])>130?substr((string)$m['body'],0,127).'…':(string)$m['body'])?>">Reply</button><?php foreach($reactionLabels as $rk=>$rl):?><button type="button" class="message-reaction<?=!empty($m['reactions'][$rk]['mine'])?' active':''?>" data-react-message="<?=(int)$m['id']?>" data-reaction="<?=e($rk)?>"><?=e($rl)?><?php if(!empty($m['reactions'][$rk]['count'])):?><b><?=(int)$m['reactions'][$rk]['count']?></b><?php endif;?></button><?php endforeach;?><?php if(!$m['mine']):?><button class="message-report-link" type="button" data-report-message="<?=(int)$m['id']?>">Report</button><?php endif;?></div></div></article><?php endforeach;?>
</div>
<div class="reply-composer-preview" data-reply-preview hidden><div><span>Replying to message</span><p data-reply-preview-copy></p></div><button type="button" data-reply-cancel>×</button></div>
<form class="match-composer" data-match-composer><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="match_id" value="<?=$matchId?>"><input type="hidden" name="parent_message_id" value="0" data-parent-message><textarea name="body" rows="1" maxlength="2000" placeholder="Message <?=e($partner['display_name']?:'your Travel Match')?>…" required><?=e($starter)?></textarea><button type="submit" aria-label="Send message">↑</button></form><div class="chat-error" data-chat-error hidden></div></div>
<dialog class="report-message-modal" data-report-dialog><form method="dialog" class="report-message-card"><button class="dialog-close" value="cancel" aria-label="Close">×</button><span class="eyebrow">Conversation Safety</span><h2>Report this message?</h2><p class="muted">Reporting the message will also block this Travel Match and close the conversation.</p><input type="hidden" data-report-message-id><label>Reason<select data-report-reason><option value="harassment">Harassment</option><option value="spam">Spam</option><option value="fake_profile">Fake profile</option><option value="unsafe_behavior">Unsafe behavior</option><option value="underage_concern">Possible underage user</option><option value="other">Other</option></select></label><label>Details<textarea data-report-details rows="3" maxlength="1000" placeholder="Optional details"></textarea></label><button class="button primary" value="cancel" type="button" data-submit-report>Report & block</button></form></dialog>
</div></section>
<?php require __DIR__.'/partials/footer.php';?>
