<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$matchService=new TravelMatchService($pdo);$messageService=new TravelMessageService($pdo);$profile=$matchService->profile($userId);if($profile&&!empty($profile['enabled']))$matchService->touchActivity($userId);if(!$profile)redirect('match-profile.php');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$messageService->setContactPreference($userId,(int)($_POST['match_id']??0),(string)($_POST['action']??''));}catch(Throwable $e){flash('error',$e->getMessage());}redirect('match-contacts.php'.(!empty($_POST['archived'])?'?view=archived':''));}
$search=trim((string)($_GET['q']??''));$archived=($_GET['view']??'')==='archived';$contacts=$messageService->contacts($userId,$search,$archived);$error=flash('error');$title='Matches & Messages';require __DIR__.'/partials/header.php';
?>
<section class="match-page"><div class="shell narrow-wide">
<div class="section-head contact-head"><div><span class="eyebrow">Travel Matching</span><h1>Matches & Messages</h1><p class="muted">Your mutual matches, private conversations, and questionable vacation chemistry.</p></div><?php if(!empty($profile['enabled'])):?><a class="button secondary" href="<?=e(app_url('matching.php'))?>">Keep swiping →</a><?php else:?><a class="button secondary" href="<?=e(app_url('match-profile.php'))?>">Re-enroll in matching</a><?php endif;?></div>
<?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="inbox-toolbar"><form method="get" class="inbox-search"><input type="search" name="q" value="<?=e($search)?>" placeholder="Search matches"><input type="hidden" name="view" value="<?=$archived?'archived':''?>"><button>Search</button></form><div class="inbox-tabs"><a class="<?=$archived?'':'active'?>" href="<?=e(app_url('match-contacts.php'))?>">Active</a><a class="<?=$archived?'active':''?>" href="<?=e(app_url('match-contacts.php?view=archived'))?>">Archived</a></div></div>
<?php if(empty($profile['enabled'])):?><div class="alert success">You are currently unenrolled from new Travel Matching discovery. Existing matches and messages are preserved.</div><?php endif;?>
<?php if(!$contacts):?><article class="match-empty"><h2><?=$archived?'No archived matches.':'Your contact list is currently on vacation.'?></h2><p><?=$search!==''?'No matches fit that search.':'When you and another Vacation Brain both like each other, the match appears here automatically and messaging unlocks.'?></p><?php if(!$archived):?><a class="button primary" href="<?=e(app_url('matching.php'))?>">Find Travel Matches</a><?php endif;?></article>
<?php else:?><div class="contact-list">
<?php foreach($contacts as $c):$p=$c['partner'];if(!$p)continue;$preview=trim((string)($c['latest_message']??''));if(strlen($preview)>105)$preview=substr($preview,0,102).'…';?>
<article class="contact-row-wrap<?=((int)$c['unread_count']>0?' unread':'')?><?=!empty($c['pinned'])?' pinned':''?>"><a class="contact-row" href="<?=e(app_url('match-chat.php?match='.(int)$c['id']))?>"><div class="match-avatar small"><?php if($p['photo_url']):?><img src="<?=e($p['photo_url'])?>" alt=""><?php else:?><span><?=e(strtoupper(substr($p['display_name']??'V',0,1)))?></span><?php endif;?></div><div class="contact-copy"><div><strong><?=e($p['display_name']?:'Vacation Brain')?></strong><?php if(!empty($c['pinned'])):?><span>📌 Pinned</span><?php endif;?></div><p><?=e($preview!==''?(((int)$c['latest_sender_id']===$userId?'You: ':'').$preview):'You matched. Say hello before someone proposes a 6 AM excursion.')?></p></div><div class="contact-meta"><?php if($c['latest_message_at']):?><time><?=e(date('M j · g:i A',strtotime($c['latest_message_at'])))?></time><?php endif;?><?php if((int)$c['unread_count']>0):?><b><?=(int)$c['unread_count']?></b><?php endif;?></div></a><form method="post" class="contact-actions"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="match_id" value="<?=(int)$c['id']?>"><input type="hidden" name="archived" value="<?=$archived?'1':'0'?>"><?php if(!$archived):?><button name="action" value="<?=!empty($c['pinned'])?'unpin':'pin'?>"><?=!empty($c['pinned'])?'Unpin':'Pin'?></button><button name="action" value="archive">Archive</button><?php else:?><button name="action" value="unarchive">Restore</button><?php endif;?></form></article>
<?php endforeach;?></div><?php endif;?>
</div></section>
<?php require __DIR__.'/partials/footer.php';?>
