<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$service=new TravelMatchService($pdo);$users=new UserService($pdo);$upload=new UploadService(__DIR__);$profile=$service->extendedProfile($userId);$account=$users->account($userId);$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        $existingPhotos=$profile['photos']??[];
        $beforeAvatar=(string)($account['avatar_url']??'');
        $primaryFile=$_FILES['photo_1']??null;
        if($primaryFile && (int)($primaryFile['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){
            $newUrl=$upload->storeImage($primaryFile,$userId,'avatars');
            if($newUrl){$users->updateAvatar($userId,$newUrl);if($beforeAvatar!==''&&$beforeAvatar!==$newUrl)$upload->deleteLocal($beforeAvatar);$account=$users->account($userId);}
        }
        $_POST['photo_1']=(string)($account['avatar_url']??'');
        for($i=2;$i<=4;$i++){
            $existing=$existingPhotos[$i-1]['photo_url']??'';
            if(!empty($_POST['remove_photo_'.$i])){if($existing)$upload->deleteLocal($existing);$_POST['photo_'.$i]='';continue;}
            $file=$_FILES['photo_'.$i]??null;
            if($file && (int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){$newUrl=$upload->storeImage($file,$userId,'matching');if($newUrl){if($existing)$upload->deleteLocal($existing);$_POST['photo_'.$i]=$newUrl;continue;}}
            $_POST['photo_'.$i]=$existing;
        }
        $profile=$service->saveProfile($userId,$_POST);
        flash('success',!empty($profile['enabled'])?'You are enrolled in Travel Matching and discoverable to compatible profiles.':'You are unenrolled from Travel Matching. Existing matches and messages are preserved, but your profile is no longer discoverable.');
        if(!empty($_SESSION['pending_match_invite'])){$token=(string)$_SESSION['pending_match_invite'];unset($_SESSION['pending_match_invite']);redirect('match-invite.php?token='.urlencode($token));}
        if(!empty($_SESSION['pending_match_game'])){$token=(string)$_SESSION['pending_match_game'];unset($_SESSION['pending_match_game']);redirect('match-game.php?token='.urlencode($token));}
        redirect('matching.php');
    }catch(Throwable $e){$error=$e instanceof InvalidArgumentException?$e->getMessage():'We could not save your Travel Match profile.';$profile=$service->extendedProfile($userId);$account=$users->account($userId);}
}
$p=$profile?:[];$d=$p['dealbreakers']??[];$photos=$p['photos']??[];$prompts=$p['prompts']??[];$primaryPhoto=(string)($account['avatar_url']??($photos[0]['photo_url']??($p['photo_url']??'')));$promptCatalog=$service->promptCatalog();$readiness=$profile?$service->profileReadiness($userId,true):['score'=>0,'ready'=>false,'missing'=>[]];
$title='Travel Match Profile';require __DIR__.'/partials/header.php';
?>
<section class="match-page"><div class="shell narrow-wide">
<div class="match-hero compact"><div><span class="eyebrow">Travel Matching</span><h1>Make the profile about how you actually travel.</h1><p>Your Vacation Brain already supplies the personality data. Add only the details you want people to see.</p></div><div class="age-chip">18+ only</div></div>
<article class="profile-readiness-card"><div><span class="eyebrow">Travel Match readiness</span><strong><?= (int)$readiness['score'] ?>%</strong><p><?=!empty($readiness['ready'])?'Ready for discovery. Vacation Brain has enough evidence to work with.':'Complete a few more profile basics before enrolling.'?></p></div><div class="readiness-meter"><i style="width:<?= (int)$readiness['score'] ?>%"></i></div><?php if(!empty($readiness['missing'])):?><small>Next: <?=e(implode(' · ' ,array_slice($readiness['missing'],0,3)))?></small><?php endif;?></article>
<?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<form method="post" enctype="multipart/form-data" class="match-profile-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>">
<article class="dashboard-card enrollment-card"><span class="eyebrow">Enrollment</span><h2>Travel Matching is always opt-in.</h2><p class="muted">Enroll to appear in discovery. Unenroll at any time to disappear from new matching; your Vacation Brain account, existing matches and messages remain preserved.</p><div class="enrollment-options"><label><input type="radio" name="enrollment_status" value="enrolled" <?=!empty($p['enabled'])?'checked':''?>><span><strong>Enrolled</strong><small>Show my Travel Match profile to compatible users.</small></span></label><label><input type="radio" name="enrollment_status" value="unenrolled" <?=empty($p['enabled'])?'checked':''?>><span><strong>Unenrolled</strong><small>Hide me from discovery. Keep my existing matches and history.</small></span></label></div></article>
<div class="match-form-grid">
<article class="dashboard-card"><h2>Basics</h2><div class="field"><label>Age</label><input type="number" name="age" min="18" max="99" value="<?=e(isset($p['age'])?(string)$p['age']:'')?>" required></div><div class="field"><label>My gender</label><select name="gender_identity"><option value="prefer_not" <?=($p['gender_identity']??'prefer_not')==='prefer_not'?'selected':''?>>Prefer not to say</option><option value="woman" <?=($p['gender_identity']??'')==='woman'?'selected':''?>>Woman</option><option value="man" <?=($p['gender_identity']??'')==='man'?'selected':''?>>Man</option><option value="nonbinary" <?=($p['gender_identity']??'')==='nonbinary'?'selected':''?>>Nonbinary</option></select><small class="muted">Vacation Brain never guesses this from your answers.</small></div><div class="field"><label>Preferred partner gender</label><select name="partner_gender"><?php foreach(['everyone'=>'Everyone','women'=>'Women','men'=>'Men','nonbinary'=>'Nonbinary people'] as $v=>$l):?><option value="<?=$v?>" <?=($p['partner_gender']??$p['show_me']??'everyone')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select><small class="muted">A discovery filter only. It never changes compatibility.</small></div><div class="field"><label>I’m here for</label><select name="match_mode"><option value="dating" <?=($p['match_mode']??'either')==='dating'?'selected':''?>>Dating</option><option value="travel_buddy" <?=($p['match_mode']??'either')==='travel_buddy'?'selected':''?>>Travel buddy</option><option value="either" <?=($p['match_mode']??'either')==='either'?'selected':''?>>Either</option></select></div></article>
<article class="dashboard-card"><h2>Discovery preferences</h2><div class="inline-fields"><div class="field"><label>Min age</label><input type="number" name="min_partner_age" min="18" max="99" value="<?=e((string)($p['min_partner_age']??18))?>"></div><div class="field"><label>Max age</label><input type="number" name="max_partner_age" min="18" max="99" value="<?=e((string)($p['max_partner_age']??99))?>"></div></div><div class="field"><label>Location scope</label><select name="discovery_scope"><?php foreach(['anywhere'=>'Anywhere','country'=>'Same country','region'=>'Same state / region','city'=>'Same city'] as $v=>$l):?><option value="<?=$v?>" <?=($p['discovery_scope']??'anywhere')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><label class="check-row"><input type="checkbox" name="show_activity_status" value="1" <?=!isset($p['show_activity_status'])||!empty($p['show_activity_status'])?'checked':''?>> Show a broad activity cue such as “Active today”</label><small class="muted">We never show an exact last-seen timestamp.</small></article>
<article class="dashboard-card"><h2>Home base</h2><div class="field"><label>City</label><input name="home_city" maxlength="120" value="<?=e($p['home_city']??'')?>" placeholder="Phoenix"></div><div class="field"><label>State / region</label><input name="home_region" maxlength="120" value="<?=e($p['home_region']??'')?>" placeholder="Arizona"></div><div class="field"><label>Country</label><input name="home_country" maxlength="120" value="<?=e($p['home_country']??'')?>" placeholder="United States"></div><div class="field"><label>Favorite destination</label><input name="favorite_destination" maxlength="180" value="<?=e($p['favorite_destination']??'')?>" placeholder="Cabo, Maui, Rome..."></div></article>
<article class="dashboard-card"><h2>Travel style</h2><div class="field"><label>Pace</label><select name="travel_pace"><option value="slow" <?=($p['travel_pace']??'balanced')==='slow'?'selected':''?>>Slow — one real thing per day</option><option value="balanced" <?=($p['travel_pace']??'balanced')==='balanced'?'selected':''?>>Balanced</option><option value="packed" <?=($p['travel_pace']??'balanced')==='packed'?'selected':''?>>Packed — we came here to do things</option></select></div><div class="field"><label>Budget style</label><select name="budget_style"><option value="budget" <?=($p['budget_style']??'comfortable')==='budget'?'selected':''?>>Budget-conscious</option><option value="comfortable" <?=($p['budget_style']??'comfortable')==='comfortable'?'selected':''?>>Comfortable</option><option value="premium" <?=($p['budget_style']??'comfortable')==='premium'?'selected':''?>>Premium when it matters</option></select></div></article>
</div>
<article class="dashboard-card"><div class="section-head compact-head"><div><span class="eyebrow">Photos</span><h2>Your account photo leads the gallery.</h2><p>Your main Account Settings profile picture is always Photo 1. Add up to three extra Travel Match-only photos; people can click forward/back through them in discovery.</p></div></div><div class="matching-upload-grid"><?php for($i=1;$i<=4;$i++):$existing=$i===1?$primaryPhoto:($photos[$i-1]['photo_url']??'');?><div class="matching-upload-slot"><?php if($existing):?><img src="<?=e($existing)?>" alt="Travel Match photo <?=$i?>"><?php else:?><div class="matching-upload-placeholder"><span><?= $i===1?'Primary':'Photo '.$i ?></span></div><?php endif;?><div class="field"><label><?= $i===1?'Account / primary photo':'Photo '.$i ?></label><input name="photo_<?=$i?>" type="file" accept="image/jpeg,image/png,image/webp"><small class="muted"><?= $i===1?'Changing this also changes your Account Settings profile picture.':'Travel Match-only · JPEG, PNG, or WebP · 8 MB max.' ?></small></div><?php if($i>1&&$existing):?><label class="check-row compact"><input type="checkbox" name="remove_photo_<?=$i?>" value="1"> Remove this photo</label><?php endif;?></div><?php endfor;?></div></article>
<article class="dashboard-card"><h2>About your travel brain</h2><div class="field"><label>Short bio</label><textarea name="bio" maxlength="500" rows="4" placeholder="I believe direct flights are a form of self-respect and breakfast should happen after 9."><?=e($p['bio']??'')?></textarea></div></article>
<article class="dashboard-card"><div class="section-head compact-head"><div><span class="eyebrow">Profile prompts</span><h2>Give people something better than “hey.”</h2><p>Choose up to three. These are loaded only when someone opens your profile; one may be used as a lightweight discovery teaser.</p></div></div><div class="profile-prompt-editor"><?php for($i=1;$i<=3;$i++):$row=$prompts[$i-1]??[];?><div class="prompt-edit-row"><select name="prompt_key_<?=$i?>"><option value="">Choose a prompt</option><?php foreach($promptCatalog as $key=>$label):?><option value="<?=e($key)?>" <?=($row['prompt_key']??'')===$key?'selected':''?>><?=e($label)?></option><?php endforeach;?></select><textarea name="prompt_answer_<?=$i?>" maxlength="500" rows="2" placeholder="Your answer..."><?=e($row['answer_text']??'')?></textarea></div><?php endfor;?></div></article>
<article class="dashboard-card"><h2>Dealbreakers & strong opinions</h2><div class="dealbreaker-grid"><label class="check-row"><input type="checkbox" name="no_smoking" value="1" <?=!empty($d['no_smoking'])?'checked':''?>> No smoking on trips</label><label class="check-row"><input type="checkbox" name="no_sunrise" value="1" <?=!empty($d['no_sunrise'])?'checked':''?>> 6 AM excursions are vacation misconduct</label><label class="check-row"><input type="checkbox" name="nightlife_ok" value="1" <?=!empty($d['nightlife_ok'])?'checked':''?>> Nightlife matters</label><label class="check-row"><input type="checkbox" name="budget_matters" value="1" <?=!empty($d['budget_matters'])?'checked':''?>> Budget compatibility matters</label><label class="check-row"><input type="checkbox" name="spontaneous_ok" value="1" <?=!empty($d['spontaneous_ok'])?'checked':''?>> Must tolerate spontaneous changes</label></div></article>
<div class="form-actions"><button class="button primary" type="submit">Save Travel Match Profile</button><a class="button secondary" href="<?=e(app_url('matching.php'))?>">Cancel</a></div>
<p class="microcopy">Travel Matching is optional and 18+. Gender and partner preferences are user-entered discovery settings, not inferred characteristics.</p>
</form></div></section><?php require __DIR__.'/partials/footer.php';?>
