<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$engage=new MatchEngagementService($pdo);$matchService=new TravelMatchService($pdo);$mineProfile=$matchService->profile($userId);if($mineProfile&&!empty($mineProfile['enabled']))$matchService->touchActivity($userId);$messageService=new TravelMessageService($pdo);$matchId=(int)($_GET['match']??$_POST['match']??0);
try{$match=$engage->match($matchId,$userId);}catch(Throwable $e){http_response_code(404);exit('Travel Match not available.');}
$partner=$matchService->profile((int)$match['partner_id']);if(!$partner){http_response_code(404);exit('Travel Match profile not available.');}
$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='daily_answer'){$engage->answerDailyQuestion($matchId,$userId,(int)($_POST['choice_id']??0));flash('success','Answer locked in. The reveal waits for both Vacation Brains.');}
        elseif($action==='save_dream'){$engage->saveSharedDream($matchId,$userId,$_POST);flash('success','Shared dream updated. This hypothetical trip is becoming suspiciously specific.');}
        elseif($action==='add_dream_item'){$engage->addSharedDreamItem($matchId,$userId,(string)($_POST['item_type']??'idea'),(string)($_POST['title']??''),(string)($_POST['notes']??''));flash('success','Added to the shared dream.');}
        elseif($action==='start_game'){$game=$engage->startMatchedGame($matchId,$userId,(string)($_POST['game_type']??''));redirect('match-game.php?token='.urlencode($game['token']));}
        redirect('match-space.php?match='.$matchId);
    }catch(Throwable $e){$error=$e instanceof InvalidArgumentException?$e->getMessage():'Vacation Brain could not save that yet.';}
}
$daily=$engage->dailyQuestion($matchId,$userId);$streak=$engage->streak($matchId,$userId);$icebreakers=$engage->icebreakers($matchId,$userId,5);$discoveries=$engage->discoveries($matchId,$userId);$matchAchievements=$engage->achievements($matchId,$userId);$dream=$engage->sharedDream($matchId,$userId,true);$games=$matchService->gameCatalog();
$success=flash('success');$title='Match Space — '.($partner['display_name']?:'Travel Match');require __DIR__.'/partials/header.php';
?>
<section class="match-page"><div class="shell narrow-wide">
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="match-space-head"><div><a class="back-link" href="<?=e(app_url('match-chat.php?match='.$matchId))?>">← Conversation</a><span class="eyebrow">Your Match Space</span><h1>You + <?=e($partner['display_name']?:'another Vacation Brain')?></h1><p>Shared questions, discoveries, games and one completely hypothetical vacation.</p></div><div class="match-streak-card"><span>SHARED STREAK</span><strong><?=$streak['current']?> day<?=$streak['current']===1?'':'s'?></strong><small><?=$streak['shared_days']?> shared active day<?=$streak['shared_days']===1?'':'s'?> total</small></div></div>

<div class="match-space-grid">
<article class="dashboard-card daily-match-card"><span class="eyebrow">Daily Match Question · <?=e(date('M j'))?></span><h2><?=e((string)($daily['content']['body']?:$daily['content']['title']))?></h2>
<?php if(!$daily['mine']):?><form method="post" class="daily-match-options"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="match" value="<?=$matchId?>"><input type="hidden" name="action" value="daily_answer"><?php foreach($daily['choices'] as $choice):?><button name="choice_id" value="<?=(int)$choice['id']?>"><strong><?=e($choice['label'])?></strong><?php if($choice['description']):?><span><?=e($choice['description'])?></span><?php endif;?></button><?php endforeach;?></form>
<?php elseif(!$daily['revealed']):?><div class="daily-wait"><strong>Your answer is locked.</strong><p>We reveal both answers only after <?=e($partner['display_name']?:'your match')?> answers. Suspense is cheaper than a couples therapist.</p></div>
<?php else:?><div class="daily-reveal"><span class="eyebrow">The reveal</span><?php foreach($daily['answers'] as $answer):?><div class="daily-answer-row"><strong><?=e((int)$answer['user_id']===$userId?'You':($answer['display_name']?:'Your match'))?></strong><blockquote>“<?=e($answer['label'])?>”</blockquote></div><?php endforeach;?><?php $same=count($daily['answers'])===2 && (int)$daily['answers'][0]['choice_id']===(int)$daily['answers'][1]['choice_id'];?><p class="daily-verdict"><?= $same?'Same answer. Vacation Brain is taking notes.':'Different answers. Your first imaginary committee meeting may now begin.' ?></p></div><?php endif;?></article>

<article class="dashboard-card icebreaker-card"><span class="eyebrow">Vacation Brain Icebreakers</span><h2>Skip “hey.” You have data.</h2><div class="icebreaker-list"><?php foreach($icebreakers as $line):?><a href="<?=e(app_url('match-chat.php?match='.$matchId.'&starter='.urlencode($line)))?>"><span><?=e($line)?></span><b>Use this →</b></a><?php endforeach;?></div></article>
</div>

<div class="section-head"><div><span class="eyebrow">Match Discoveries</span><h2>Things Vacation Brain has noticed about you two</h2></div></div>
<?php if(!$discoveries):?><article class="match-empty compact"><p>Not enough shared evidence yet. Answer today’s question or play a mini-game and Vacation Brain will start making allegations.</p></article><?php else:?><div class="discovery-grid"><?php foreach(array_slice($discoveries,0,8) as $d):?><article class="discovery-card"><span><?=e(ucwords(str_replace('_',' ',$d['discovery_type'])))?></span><h3><?=e($d['title'])?></h3><p><?=e($d['body'])?></p></article><?php endforeach;?></div><?php endif;?>

<div class="section-head"><div><span class="eyebrow">Travel Match Achievements</span><h2>Badges you earned together</h2></div></div>
<?php if(!$matchAchievements):?><article class="match-empty compact"><p>No shared achievements yet. This is probably healthier than having six on day one.</p></article><?php else:?><div class="match-achievement-grid"><?php foreach($matchAchievements as $a):?><article><div class="achievement-dot">★</div><strong><?=e($a['name'])?></strong><p><?=e($a['description'])?></p></article><?php endforeach;?></div><?php endif;?>

<div class="section-head"><div><span class="eyebrow">Mini Games</span><h2>Create a small hypothetical problem</h2><p>Both answer independently. Nothing reveals until both are done.</p></div></div><div class="game-grid"><?php foreach($games as $slug=>$g):?><form method="post" class="game-card"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="match" value="<?=$matchId?>"><input type="hidden" name="action" value="start_game"><input type="hidden" name="game_type" value="<?=e($slug)?>"><h3><?=e($g['title'])?></h3><p><?=e($g['description'])?></p><button class="button secondary">Play together →</button></form><?php endforeach;?></div>

<div class="section-head"><div><span class="eyebrow">Shared Dream Trip</span><h2>Entirely hypothetical. Obviously.</h2><p>Keep it light: a place, a vibe and the ideas you would both want on the imaginary itinerary.</p></div></div>
<div class="shared-dream-layout"><form method="post" class="dashboard-card shared-dream-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="match" value="<?=$matchId?>"><input type="hidden" name="action" value="save_dream"><div class="field"><label>Trip nickname</label><input name="name" maxlength="180" value="<?=e($dream['name']??'Our Completely Hypothetical Trip')?>"></div><div class="field"><label>Where are we pretending to go?</label><input name="destination" maxlength="180" value="<?=e($dream['destination']??'')?>" placeholder="Cabo, Lisbon, somewhere with a pool..."></div><div class="field"><label>Vibe</label><input name="vibe" maxlength="120" value="<?=e($dream['vibe']??'')?>" placeholder="Food + beach + no alarms"></div><div class="field"><label>Budget energy</label><select name="budget_style"><?php foreach(['budget'=>'Keep it reasonable','comfortable'=>'Comfortable','premium'=>'Spend where it matters','ridiculous'=>'Lottery winner behavior'] as $v=>$l):?><option value="<?=$v?>" <?=($dream['budget_style']??'comfortable')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><div class="field"><label>How serious is this daydream?</label><input name="dream_level" type="range" min="1" max="5" value="<?=(int)($dream['dream_level']??2)?>"></div><div class="field"><label>Notes</label><textarea name="notes" rows="4" maxlength="5000" placeholder="No itinerary before breakfast. Find the ridiculous dinner."><?=e($dream['notes']??'')?></textarea></div><button class="button primary">Save Shared Dream</button></form>
<div class="dashboard-card shared-dream-items"><div><span class="eyebrow">Shared itinerary ideas</span><h2><?=e($dream['destination']?:'Destination TBD')?></h2></div><form method="post" class="dream-item-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="match" value="<?=$matchId?>"><input type="hidden" name="action" value="add_dream_item"><select name="item_type"><option value="idea">Idea</option><option value="hotel">Hotel</option><option value="food">Food</option><option value="activity">Activity</option><option value="flight">Flight</option><option value="splurge">Splurge</option></select><input name="title" maxlength="220" placeholder="Add something to the imaginary trip" required><input name="notes" maxlength="700" placeholder="Optional note"><button class="button secondary">Add</button></form><?php if(empty($dream['items'])):?><p class="muted">Nothing saved yet. This trip is still legally just a thought.</p><?php else:?><div class="shared-item-list"><?php foreach($dream['items'] as $item):?><div><span><?=e(ucfirst($item['item_type']))?></span><strong><?=e($item['title'])?></strong><p><?=e($item['notes']??'')?></p><small>Added by <?=e($item['display_name']?:'a Vacation Brain')?></small></div><?php endforeach;?></div><?php endif;?></div></div>
</div></section>
<?php require __DIR__.'/partials/footer.php';?>
