<?php
require __DIR__.'/app/bootstrap.php';$userId=require_auth();$target=(int)($_GET['user']??$_POST['user']??0);$isModal=!empty($_GET['modal'])||!empty($_POST['modal']);if(!$target||$target===$userId)redirect('matching.php');$pdo=db();$service=new TravelMatchService($pdo);$mine=$service->profile($userId);if($mine&&!empty($mine['enabled']))$service->touchActivity($userId);$other=$service->extendedProfile($target);$pair=$pdo->prepare('SELECT id FROM travel_matches WHERE status="active" AND ((user_a_id=? AND user_b_id=?) OR (user_a_id=? AND user_b_id=?)) LIMIT 1');$pair->execute([$userId,$target,$target,$userId]);$existingMatchId=(int)($pair->fetchColumn()?:0);if(!$mine)redirect('match-profile.php');if(empty($mine['enabled'])&&!$existingMatchId)redirect('match-profile.php');if(!$other||(empty($other['enabled'])&&!$existingMatchId)){http_response_code(404);exit('Travel Match profile not available.');}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{
    $action=(string)($_POST['action']??'');
    if($action==='react_response'){
        if(!$existingMatchId)throw new RuntimeException('Profile reactions unlock after you match.');
        (new TravelMessageService($pdo))->reactToProfileResponse($existingMatchId,$userId,$target,(int)($_POST['content_id']??0),(int)($_POST['choice_id']??0),(string)($_POST['reaction_type']??''));
        flash('success','Sent to your Travel Match conversation.');redirect('match-user.php?user='.$target.($isModal?'&modal=1':''));
    }
    if($action==='report'){ $service->report($userId,$target,(string)($_POST['reason']??'other'),(string)($_POST['details']??''));flash('success','Report received. This profile has also been blocked from your Travel Matching experience.');redirect('matching.php'); }
    $r=$service->act($userId,$target,$action);
    if($action==='block'){flash('success','Profile blocked. You will no longer see each other in Travel Matching.');redirect('matching.php');}
    if(!empty($r['new_match'])){$_SESSION['new_travel_match']=['match_id'=>(int)$r['match_id'],'target'=>$target];} flash('success',$r['matched']?'It’s a Travel Match. Your vacation opinions have achieved mutual consent.':($action==='like'?'Liked. Now we wait for their Vacation Brain to make a decision.':'Passed. The imaginary itinerary has been cancelled.'));redirect('match-user.php?user='.$target.($isModal?'&modal=1':''));
}catch(Throwable $e){flash('error',$e->getMessage());redirect('match-user.php?user='.$target.($isModal?'&modal=1':''));}}
$comp=$service->compatibility($userId,$target);$relevantResponses=$service->relevantResponses($userId,$target,8);$action=$service->actionFor($userId,$target);$matches=$service->matches($userId);$activeMatch=null;foreach($matches as $m){if((int)$m['partner_id']===$target){$activeMatch=$m;break;}}$newMatch=$_SESSION['new_travel_match']??null;unset($_SESSION['new_travel_match']);if($newMatch && !empty($newMatch['match_id']))$service->markMatchSeen((int)$newMatch['match_id'],$userId);$success=flash('success');$error=flash('error');$profile2=(new VacationProfileService($pdo))->snapshot($target);$catalog=$service->gameCatalog();$title='Travel Match — '.($other['display_name']?:'Vacation Brain');if(!$isModal)require __DIR__.'/partials/header.php';else{?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?></title><link rel="stylesheet" href="<?=e(app_url('assets/app.css'))?>"></head><body class="profile-modal-document"><?php }
?>
<section class="match-page <?= $isModal?'match-page-modal':'' ?>"><div class="shell narrow-wide"><?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(!$isModal):?><a class="back-link" href="<?=e(app_url('matching.php'))?>">← Travel Matching</a><?php endif;?><div class="extended-profile-top"><div class="profile-primary-photo"><?php $gallery=$other['photos']??[]; if($gallery):?><img src="<?=e($gallery[0]['photo_url'])?>" alt="<?=e(($other['display_name']?:'Vacation Brain').' primary profile photo')?>"><?php elseif(!empty($other['photo_url'])):?><img src="<?=e($other['photo_url'])?>" alt="<?=e(($other['display_name']?:'Vacation Brain').' primary profile photo')?>"><?php else:?><div class="avatar-placeholder"><?=e(strtoupper(substr($other['display_name']??'V',0,1)))?></div><?php endif;?></div><div class="match-detail"><div class="match-person"><div class="profile-heading-line"><span class="eyebrow"><?=e(ucwords(str_replace('_',' ',$other['match_mode'])))?> · <?= (int)$other['age'] ?></span><?php if(!empty($other['activity_label'])):?><span class="profile-activity"><?=e($other['activity_label'])?></span><?php endif;?></div><h1><?=e($other['display_name']?:'Vacation Brain')?></h1><p><?=e($other['bio']?:$profile2['archetype']['description'])?></p><div class="person-tags"><b><?=e($profile2['archetype']['name'])?></b><b><?=e(ucfirst($other['travel_pace']))?> pace</b><b><?=e(ucfirst($other['budget_style']))?> budget</b><?php if($other['home_city']):?><b><?=e($other['home_city'])?></b><?php endif;?><?php if($other['favorite_destination']):?><b>Dreaming: <?=e($other['favorite_destination'])?></b><?php endif;?></div></div><div class="compat-panel"><span>VACATION COMPATIBILITY</span><strong><?=$comp['score']?>%</strong><p><?=e($comp['warning'])?></p><a class="button secondary" target="_top" href="<?=e(app_url('compare.php?user='.$target))?>">Compare Vacation Brains</a><?php if($activeMatch):?><a class="button primary match-message-cta" target="_top" href="<?=e(app_url('match-chat.php?match='.(int)$activeMatch['id']))?>">Message <?=e($other['display_name']?:'Match')?> →</a><a class="button secondary" target="_top" href="<?=e(app_url('match-space.php?match='.(int)$activeMatch['id']))?>">Open Match Space</a><?php endif;?></div></div></div>
<div class="match-actions"><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="user" value="<?=$target?>"><?php if($isModal):?><input type="hidden" name="modal" value="1"><?php endif;?><button class="button <?= $action==='like'?'secondary':'primary' ?>" name="action" value="like"><?= $action==='like'?'✓ Liked':'♥ Travel Like' ?></button><button class="button text-button" name="action" value="pass">Pass</button><button class="button text-button" name="action" value="block" onclick="return confirm('Block this Travel Match profile?')">Block</button></form><details class="report-box"><summary>Report profile</summary><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="user" value="<?=$target?>"><?php if($isModal):?><input type="hidden" name="modal" value="1"><?php endif;?><input type="hidden" name="action" value="report"><select name="reason"><option value="harassment">Harassment</option><option value="spam">Spam</option><option value="fake_profile">Fake profile</option><option value="unsafe_behavior">Unsafe behavior</option><option value="underage_concern">Possible underage user</option><option value="other">Other</option></select><textarea name="details" rows="3" maxlength="1000" placeholder="Optional details"></textarea><button class="button secondary" type="submit">Send report & block</button></form></details></div>
<?php if(!empty($other['prompts'])):?><section class="profile-prompt-section"><div class="section-head"><div><span class="eyebrow">Vacation profile prompts</span><h2>The answers they chose to put on the record</h2></div></div><div class="profile-prompt-cards"><?php foreach($other['prompts'] as $prompt):?><article><span><?=e($prompt['prompt_label'])?></span><p>“<?=e($prompt['answer_text'])?>”</p></article><?php endforeach;?></div></section><?php endif;?>
<div class="compare-grid"><article class="dashboard-card"><span class="eyebrow">You agree on</span><h2>Promising signs</h2><?php foreach($comp['agreements'] as $x):?><div class="compare-trait"><strong><?=e($x['label'])?></strong><span><?=$x['a']?> / <?=$x['b']?></span><div class="trait-meter"><i style="width:<?=$x['similarity']?>%"></i></div></div><?php endforeach;?></article><article class="dashboard-card"><span class="eyebrow">Potential negotiations</span><h2>Things to settle before Gate B37</h2><?php if(!$comp['conflicts']):?><p class="muted">No major conflicts yet. Suspicious.</p><?php else:?><?php foreach($comp['conflicts'] as $x):?><div class="compare-trait conflict"><strong><?=e($x['label'])?></strong><span><?=$x['a']?> / <?=$x['b']?></span><div class="trait-meter"><i style="width:<?=$x['similarity']?>%"></i></div></div><?php endforeach;?><?php endif;?></article></div>
<?php if($relevantResponses):$primaryResponses=array_slice($relevantResponses,0,4);$moreResponses=array_slice($relevantResponses,4);?>
<section class="relevant-responses">
  <div class="section-head"><div><span class="eyebrow">Relevant to your Vacation Brain</span><h2><?=e($other['display_name']?:'Their')?> answers you should probably see</h2><p>These are not random highlights. Vacation Brain picked responses tied to traits you strongly share—or may eventually argue about.</p></div></div>
  <div class="response-reveal-grid">
    <?php foreach($primaryResponses as $response):?>
    <article class="response-reveal <?=e($response['relation'])?>">
      <div class="response-context"><span><?= $response['relation']==='agreement'?'Shared instinct':($response['relation']==='difference'?'Potential argument':'Relevant signal') ?></span><b><?=e($response['trait']['name'])?></b></div>
      <h3><?=e($response['body'])?></h3>
      <blockquote>“<?=e($response['choice_label'])?>”</blockquote>
      <?php if(!empty($response['viewer_choice_label'])):?><div class="viewer-answer"><span>You answered</span><strong>“<?=e($response['viewer_choice_label'])?>”</strong></div><?php endif;?>
      <p><?=e($response['context'])?></p>
      <?php if($activeMatch):?><form method="post" class="profile-response-reactions"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="user" value="<?=$target?>"><input type="hidden" name="action" value="react_response"><input type="hidden" name="content_id" value="<?=(int)$response['content_id']?>"><input type="hidden" name="choice_id" value="<?=(int)$response['choice_id']?>"><?php if($isModal):?><input type="hidden" name="modal" value="1"><?php endif;?><span>Send to chat:</span><button name="reaction_type" value="same">Same</button><button name="reaction_type" value="explain">Explain yourself</button><button name="reaction_type" value="red_flag">Red flag</button><button name="reaction_type" value="argue">We’re going to argue</button></form><?php endif;?>
    </article>
    <?php endforeach;?>
  </div>
  <?php if($moreResponses):?><details class="more-responses"><summary>Show more relevant vacation opinions</summary><div class="response-reveal-grid">
    <?php foreach($moreResponses as $response):?>
    <article class="response-reveal <?=e($response['relation'])?>">
      <div class="response-context"><span><?= $response['relation']==='agreement'?'Shared instinct':($response['relation']==='difference'?'Potential argument':'Relevant signal') ?></span><b><?=e($response['trait']['name'])?></b></div>
      <h3><?=e($response['body'])?></h3>
      <blockquote>“<?=e($response['choice_label'])?>”</blockquote>
      <?php if(!empty($response['viewer_choice_label'])):?><div class="viewer-answer"><span>You answered</span><strong>“<?=e($response['viewer_choice_label'])?>”</strong></div><?php endif;?>
      <p><?=e($response['context'])?></p>
      <?php if($activeMatch):?><form method="post" class="profile-response-reactions"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="user" value="<?=$target?>"><input type="hidden" name="action" value="react_response"><input type="hidden" name="content_id" value="<?=(int)$response['content_id']?>"><input type="hidden" name="choice_id" value="<?=(int)$response['choice_id']?>"><?php if($isModal):?><input type="hidden" name="modal" value="1"><?php endif;?><span>Send to chat:</span><button name="reaction_type" value="same">Same</button><button name="reaction_type" value="explain">Explain yourself</button><button name="reaction_type" value="red_flag">Red flag</button><button name="reaction_type" value="argue">We’re going to argue</button></form><?php endif;?>
    </article>
    <?php endforeach;?>
  </div></details><?php endif;?>
</section>
<?php endif;?>
<div class="section-head"><div><span class="eyebrow">Compatibility Games</span><h2>Stop looking at percentages. Create a hypothetical problem.</h2></div></div><div class="game-grid"><?php foreach($catalog as $slug=>$g):?><form method="post" action="<?=e(app_url('start-match-game.php'))?>" class="game-card"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="partner" value="<?=$target?>"><input type="hidden" name="game_type" value="<?=e($slug)?>"><h3><?=e($g['title'])?></h3><p><?=e($g['description'])?></p><button class="button secondary">Play →</button></form><?php endforeach;?></div>
<?php if($newMatch && (int)($newMatch['target']??0)===$target):?>
<div class="travel-match-modal" data-match-modal>
  <div class="travel-match-modal-card">
    <button class="match-modal-close" type="button" data-match-modal-close aria-label="Close">×</button>
    <span class="eyebrow">It’s a Travel Match</span>
    <div class="match-modal-avatars">
      <div class="match-avatar"><?php $meProfile=$service->profile($userId); if($meProfile && $meProfile['photo_url']):?><img src="<?=e($meProfile['photo_url'])?>" alt=""><?php else:?><span><?=e(strtoupper(substr(current_user()['display_name']??'Y',0,1)))?></span><?php endif;?></div>
      <div class="match-heart">♥</div>
      <div class="match-avatar"><?php if($other['photo_url']):?><img src="<?=e($other['photo_url'])?>" alt=""><?php else:?><span><?=e(strtoupper(substr($other['display_name']??'V',0,1)))?></span><?php endif;?></div>
    </div>
    <h2>You both said yes.</h2>
    <p><?=$comp['score']?>% Vacation Compatible. <?=e($comp['warning'])?></p>
    <small class="match-added-note">Added to Matches &amp; Messages. Private messaging is now unlocked.</small>
    <div class="match-modal-actions"><a class="button primary" href="<?=e(app_url('match-chat.php?match='.(int)$newMatch['match_id']))?>">Send a Message</a><a class="button secondary" href="<?=e(app_url('matching.php'))?>">Keep Browsing</a></div>
  </div>
</div>
<?php endif;?>
</div></section><?php if(!$isModal)require __DIR__.'/partials/footer.php';else{?><script src="<?=e(app_url('assets/app.js'))?>"></script></body></html><?php }?>
