<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$tripId=(int)($_GET['id']??$_POST['trip_id']??0);$service=new ProactiveTravelService($pdo);$error='';
$trip=(new DreamService($pdo))->get($userId,$tripId,false);if(!$trip){http_response_code(404);exit('Trip not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();try{$action=(string)($_POST['action']??'assess');if($action==='dismiss'){$service->dismissIssue($userId,$tripId,(int)($_POST['issue_id']??0));flash('success','That proactive issue was dismissed. A materially different future issue can still surface.');}elseif($action==='assess'){$service->assessTrip($userId,$tripId,true,'worker');flash('success','Vacation Brain reassessed the saved trip data. No external provider refresh was triggered.');}else throw new InvalidArgumentException('Unknown proactive action.');redirect('proactive-trip.php?id='.$tripId);}catch(Throwable $e){$error=$e->getMessage();}
}
$assessment=$service->ready()?$service->assessTrip($userId,$tripId,true,'worker'):['ready'=>false,'enabled'=>false,'issues'=>[],'risk_score'=>0,'risk_label'=>'Upgrade required','health'=>[],'preferences'=>$service->preferences($userId)];$issues=$assessment['issues']??[];$briefings=$service->recentBriefings($userId,$tripId,7);$success=flash('success');$title='Proactive Vacation Brain — '.(string)$trip['name'];$pageStyles=['assets/proactive-travel.css','assets/live-travel-data.css'];require __DIR__.'/partials/header.php';
?>
<section class="dashboard vb-proactive-page"><div class="shell">
<div class="trip-intelligence-head"><div><a class="back-link" href="<?=e(app_url('dream-trip.php?id='.$tripId.'&tab=overview'))?>">← Trip dashboard</a><span class="eyebrow">Proactive Vacation Brain</span><h1>What needs attention before you ask?</h1><p><?=e((string)$trip['name'])?> · risk, conflicts, opportunities and approval-safe Next Moves derived from saved trip data.</p></div><div class="trip-intelligence-head-actions"><a class="button secondary small" href="<?=e(app_url('proactive-settings.php'))?>">Proactive settings</a><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="assess"><button class="button primary small" type="submit">Reassess saved data</button></form></div></div>
<?php if(!$service->ready()):?><div class="alert warning"><strong>Migration 047 / app v1.39 is required.</strong> <?php if(is_admin()):?><a href="<?=e(app_url('upgrade.php'))?>">Run System Upgrade →</a><?php endif;?></div><?php endif;?><?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="vb-proactive-hero dashboard-card"><div><span class="eyebrow">Current trip risk</span><div class="vb-proactive-score-row"><strong class="vb-proactive-score"><?=(int)($assessment['risk_score']??0)?></strong><div><h2><?=e((string)($assessment['risk_label']??'Under control'))?></h2><p><?=count($issues)?> open signal<?=count($issues)===1?'':'s'?> · automatic research <?=!empty($assessment['preferences']['auto_research'])?'on':'off'?> · changes still require approval.</p></div></div></div><div class="vb-proactive-scale" aria-label="Risk score"><span style="width:<?=max(0,min(100,(int)($assessment['risk_score']??0)))?>%"></span></div></div>
<?php if(empty($assessment['enabled'])):?><div class="alert warning"><strong>Proactive monitoring is off.</strong> Existing issues remain visible, but Vacation Brain is not creating new proactive issues. <a href="<?=e(app_url('proactive-settings.php'))?>">Change settings →</a></div><?php endif;?>
<div class="vb-proactive-grid">
<section class="dashboard-card"><div class="admin-table-head"><div><span class="eyebrow">Open issues</span><h2>Risks, conflicts & opportunities</h2></div><strong><?=count($issues)?></strong></div>
<?php if(!$issues):?><div class="vb-proactive-empty"><strong>No meaningful issue is open.</strong><p>That means the saved data looks calm, not that airlines, weather, hotels or reality have signed a contract with Vacation Brain.</p></div><?php else:?><div class="vb-proactive-issue-list"><?php foreach($issues as $issue):$actions=is_array($issue['actions']??null)?$issue['actions']:[];?><article class="vb-proactive-issue <?=e((string)$issue['severity'])?>" id="issue-<?=(int)$issue['id']?>"><div class="vb-proactive-issue-top"><div><span class="vb-proactive-badge <?=e((string)$issue['severity'])?>"><?=e(ucfirst((string)$issue['severity']))?></span><span class="vb-proactive-type"><?=e(ucfirst((string)$issue['issue_type']))?></span></div><span class="vb-proactive-source"><?=e(ucfirst((string)$issue['source_state']))?> · <?=(int)$issue['confidence']?>% confidence</span></div><h3><?=e((string)$issue['title'])?></h3><p><?=e((string)$issue['body'])?></p><?php if($actions):?><div class="vb-proactive-moves"><strong>Recommended next move<?=count($actions)===1?'':'s'?></strong><?php foreach($actions as $move):?><span><?=e((string)($move['label']??'Research options'))?></span><?php endforeach;?></div><?php endif;?><div class="vb-proactive-issue-actions"><a class="button primary small" href="<?=e((string)$issue['url'])?>">Open Next Move</a><?php if(!empty($issue['auto_research_started_at'])):?><span class="vb-proactive-agent-state">Agent research started</span><?php endif;?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="issue_id" value="<?=(int)$issue['id']?>"><button class="button secondary small" type="submit" name="action" value="dismiss">Dismiss</button></form></div></article><?php endforeach;?></div><?php endif;?>
</section>
<aside class="dashboard-card"><div class="admin-table-head"><div><span class="eyebrow">Source health</span><h2>What this is based on</h2></div></div><div class="vb-proactive-health"><?php foreach(['flights'=>'Flights','weather'=>'Weather','lodging'=>'Lodging','events'=>'Events','places'=>'Places'] as $type=>$label):$h=$assessment['health'][$type]??[];?><div><span><?=$label?></span><strong><?=e((string)($h['label']??'Waiting'))?></strong><small><?=e((string)($h['freshness']??'No snapshot'))?></small></div><?php endforeach;?></div><div class="vb-proactive-privacy"><strong>Decision boundary</strong><p>Live/cached data can trigger research and recommendations. Vacation Brain does not silently change bookings, purchases, reservations or itinerary data. Specialist proposals flow through the existing approval queue.</p></div></aside>
</div>
<section class="dashboard-card vb-proactive-briefings" id="briefings"><div class="admin-table-head"><div><span class="eyebrow">Daily operations</span><h2>Morning & travel-day briefings</h2><p class="muted">One concise operational summary per trip/day when the trip is close or underway.</p></div></div><?php if(!$briefings):?><div class="vb-proactive-empty">No briefing has been generated yet.</div><?php else:?><div class="vb-proactive-brief-list"><?php foreach($briefings as $brief):?><article><div><strong><?=e((string)$brief['headline'])?></strong><span><?=e(date('M j, Y',strtotime((string)$brief['briefing_date'])))?> · <?=e(str_replace('_',' ',(string)$brief['briefing_kind']))?></span></div><p><?=nl2br(e((string)$brief['body']))?></p></article><?php endforeach;?></div><?php endif;?></section>
</div></section>
<?php require __DIR__.'/partials/footer.php';?>
