<?php
require __DIR__.'/app/bootstrap.php';$userId=require_auth();$pdo=db();$user=current_user();$profile=(new VacationProfileService($pdo))->snapshot($userId);$summary=$profile['summary'];$traits=array_values($profile['traits']);
$stmt=$pdo->prepare('SELECT diagnosis_title,diagnosis_score,vacation_brain_score,summary_text,created_at FROM diagnosis_results WHERE user_id=? ORDER BY created_at DESC');$stmt->execute([$userId]);$diagnoses=$stmt->fetchAll();
$stmt=$pdo->prepare('SELECT a.id,a.name,a.description,a.rarity,ua.unlocked_at FROM user_achievements ua JOIN achievements a ON a.id=ua.achievement_id WHERE ua.user_id=? AND ua.completed=1 ORDER BY ua.unlocked_at DESC');$stmt->execute([$userId]);$achievements=$stmt->fetchAll();$merch=(new MerchService($pdo))->recommendations($userId);
$title='My Vacation Brain';require __DIR__.'/partials/header.php';
?>
<section class="dashboard profile-v2"><div class="shell"><div class="profile-hero"><div><span class="eyebrow">My Vacation Brain</span><h1><?=e($profile['archetype']['name'])?></h1><p><?=e($profile['archetype']['description'])?></p><div class="share-row"><a class="button primary" href="<?=e(app_url('share.php'))?>">Share my diagnosis</a><a class="button secondary" href="<?=e(app_url('roast.php'))?>">Roast this profile</a></div></div><div class="profile-score"><span>CURRENT SCORE</span><strong><?=$profile['score']?></strong><em><?=e($profile['level']['label'])?></em><small><?=e($profile['level']['line'])?></small></div></div>
<div class="section-head"><div><span class="eyebrow">Personality Map</span><h2>The profile underneath the jokes</h2></div></div><div class="profile-traits compact"><?php foreach($traits as $trait):?><article class="info-card"><div class="trait-top"><strong><?=e($trait['name'])?></strong><span><?=(int)$trait['score']?>%</span></div><div class="trait-meter"><i style="width:<?=(int)$trait['score']?>%"></i></div><p class="small">Confidence <?=(int)$trait['confidence']?>% · <?=e($trait['trait_group'])?></p></article><?php endforeach;?></div>
<div class="mini-grid" style="margin-top:22px"><article class="dashboard-card"><h2>Diagnosis progression</h2><div class="progression"><div><span>NOW</span><strong><?=e($profile['level']['title'])?></strong><small><?=$profile['score']?> Vacation Brain points</small></div><?php foreach(array_slice($diagnoses,0,3) as $d):?><div><span><?=e(date('M j',strtotime($d['created_at'])))?></span><strong><?=e($d['diagnosis_title'])?></strong><small>Self-diagnosis <?= (int)$d['diagnosis_score'] ?>/100</small></div><?php endforeach;?></div></article><article class="dashboard-card"><h2>Evidence locker</h2><?php if(!$achievements):?><p class="muted">Nothing unlocked yet. Disturbingly responsible.</p><?php else:?><?php foreach(array_slice($achievements,0,8) as $a):?><div class="achievement"><strong><?=e($a['name'])?></strong><div class="muted small"><?=e($a['description'])?></div></div><?php endforeach;?><?php endif;?></article></div>
<div class="section-head"><div><span class="eyebrow">Merch Generated From You</span><h2>Wear your behavioral evidence</h2></div><a href="<?=e(app_url('merch.php'))?>">See all merch →</a></div><div class="merch-mini-grid"><?php foreach(array_slice($merch,0,3) as $item):?><a href="<?=e(app_url('merch.php'))?>"><span><?=e(strtoupper($item['product_type']??'SHIRT'))?></span><strong><?=e($item['headline']??$item['name'])?></strong><small><?=e($item['subheadline']??'Built from your Vacation Brain')?></small></a><?php endforeach;?></div>
</div></section><?php require __DIR__.'/partials/footer.php';?>
