<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$service=new TripCollaborationService($pdo);$tripId=(int)($_GET['id']??$_POST['trip_id']??0);$error='';
if(!$service->ready()){http_response_code(503);exit('Run System Upgrade to enable Collaborative Trips & Travelers.');}
$access=$service->access($userId,$tripId);if(!$access){http_response_code(404);exit('Shared trip not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        $command=strtolower(trim((string)($_POST['command']??'')));
        if($command==='vote')$service->setVote($userId,$tripId,(int)($_POST['item_id']??0),(string)($_POST['vote']??''),(string)($_POST['comment']??''));
        elseif($command==='add_item')$service->addItem($userId,$tripId,$_POST);
        elseif($command==='remove_item')$service->removeItem($userId,$tripId,(int)($_POST['item_id']??0));
        elseif($command==='rsvp')$service->setRsvp($userId,$tripId,(string)($_POST['rsvp']??'unknown'));
        else throw new InvalidArgumentException('Unknown shared-trip action.');
        flash('success','Shared trip updated.');redirect('shared-trip.php?id='.$tripId);
    }catch(Throwable $e){$error=$e->getMessage();}
}
$snapshot=$service->snapshot($userId,$tripId);$trip=$snapshot['trip'];$members=$snapshot['members'];$items=$snapshot['items'];$bookings=$snapshot['bookings'];$events=$snapshot['events'];$success=flash('success');
$pageStyles=['assets/trip-collaboration.css'];$title='Shared Trip — '.(string)$trip['name'];require __DIR__.'/partials/header.php';
$roleLabels=['owner'=>'Owner','co_planner'=>'Co-planner','traveler'=>'Traveler','viewer'=>'Viewer'];$rsvpLabels=['unknown'=>'No RSVP','going'=>'Going','maybe'=>'Maybe','not_going'=>'Not going'];
$mine=null;foreach($members as $m)if((int)$m['user_id']===$userId)$mine=$m;$localConciergeReady=false;try{$localConciergeReady=class_exists('LocalConciergeService')&&(new LocalConciergeService($pdo))->ready();}catch(Throwable){}
?>
<section class="dashboard vb-shared-trip"><div class="shell">
  <div class="vb-collab-head"><div><a class="back-link" href="<?=e(app_url('dream.php'))?>">← Trips</a><div class="eyebrow">Shared Trip Workspace · <?=e($roleLabels[(string)$access['role']]??ucfirst((string)$access['role']))?></div><h1><?=e((string)$trip['name'])?></h1><p class="muted"><?=e((string)($trip['destination_name']?:'Destination TBD'))?><?php if(!empty($trip['start_date'])):?> · <?=e(date('M j',strtotime((string)$trip['start_date'])))?><?php if(!empty($trip['end_date'])):?>–<?=e(date('M j, Y',strtotime((string)$trip['end_date'])))?><?php endif;?><?php endif;?></p></div><div class="vb-shared-actions"><?php if($localConciergeReady):?><a class="button secondary" href="<?=e(app_url('local-concierge.php?id='.$tripId))?>">Local Concierge</a><?php endif;?><a class="button secondary" href="<?=e(app_url('trip-collaboration.php?id='.$tripId))?>">Travelers & access</a><?php if(!empty($access['is_owner'])):?><a class="button primary" href="<?=e(app_url('dream-trip.php?id='.$tripId))?>">Owner dashboard</a><?php endif;?></div></div>
  <?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>

  <article class="dashboard-card vb-shared-privacy"><strong>Shared workspace, narrow data boundary.</strong><span>Collaborators see the itinerary and role-appropriate trip logistics—not confirmation codes, booking notes, payment state, private Traveler Memory, provider operational references, or Booking & Action Execution controls.</span></article>

  <div class="vb-shared-summary">
    <article class="dashboard-card"><span class="eyebrow">Travelers</span><strong><?=count($members)?></strong><small><?=count(array_filter($members,fn($m)=>(string)$m['rsvp']==='going'))?> going</small></article>
    <article class="dashboard-card"><span class="eyebrow">Plan items</span><strong><?=count($items)?></strong><small><?=count(array_filter($items,fn($i)=>!empty($i['scheduled_date'])))?> scheduled</small></article>
    <article class="dashboard-card"><span class="eyebrow">Safe bookings</span><strong><?=count($bookings)?></strong><small><?=!empty($access['can_view_bookings'])?'Operational summary only':'Hidden for this role'?></small></article>
    <?php if(!empty($access['can_view_budget'])):?><article class="dashboard-card"><span class="eyebrow">Target budget</span><strong><?=isset($trip['target_budget'])&&$trip['target_budget']!==null?e(((string)($trip['currency']??'USD')).' '.number_format((float)$trip['target_budget'],0)):'—'?></strong><small>Co-planner / owner only</small></article><?php endif;?>
  </div>

  <div class="vb-shared-grid">
    <section class="dashboard-card"><div class="vb-panel-head"><div><span class="eyebrow">Itinerary decisions</span><h2>Plan together.</h2><p>Travelers can vote. Co-planners can add or remove shared itinerary items.</p></div></div>
      <?php if($items):?><div class="vb-itinerary-list"><?php foreach($items as $item):?><article class="vb-itinerary-item"><div class="vb-itinerary-copy"><span class="vb-item-type"><?=e(ucfirst((string)$item['item_type']))?></span><h3><?=e((string)$item['title'])?></h3><p><?=e(!empty($item['scheduled_date'])?date('D, M j',strtotime((string)$item['scheduled_date'])).(!empty($item['daypart'])?' · '.ucfirst((string)$item['daypart']):''):'Unscheduled')?><?php if(!empty($item['notes'])):?> · <?=e((string)$item['notes'])?><?php endif;?></p><?php if(!empty($access['can_view_budget'])&&isset($item['price'])&&$item['price']!==null):?><small><?=e((string)($trip['currency']??'USD'))?> <?=number_format((float)$item['price'],0)?></small><?php endif;?></div><div class="vb-vote-summary"><?php foreach(['love'=>'♥','yes'=>'Yes','maybe'=>'Maybe','no'=>'No'] as $vote=>$label):?><span><?=$label?> <?=isset($item['votes'][$vote])?(int)$item['votes'][$vote]:0?></span><?php endforeach;?></div><?php if(!empty($access['can_vote'])):?><form class="vb-vote-form" method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="command" value="vote"><input type="hidden" name="item_id" value="<?=(int)$item['id']?>"><select class="input small" name="vote"><option value="love">Love it</option><option value="yes">Yes</option><option value="maybe">Maybe</option><option value="no">No</option></select><input class="input small" name="comment" maxlength="280" placeholder="Optional note"><button class="button secondary small" type="submit">Vote</button></form><?php endif;?><?php if(!empty($access['can_plan'])):?><form method="post" onsubmit="return confirm('Remove this shared itinerary item?')"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="command" value="remove_item"><input type="hidden" name="item_id" value="<?=(int)$item['id']?>"><button class="vb-text-button" type="submit">Remove</button></form><?php endif;?></article><?php endforeach;?></div><?php else:?><div class="trip-empty-state"><strong>No shared itinerary items yet.</strong>Co-planners can start the plan below.</div><?php endif;?>
      <?php if(!empty($access['can_plan'])):?><form class="vb-add-item" method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="command" value="add_item"><h3>Add to the shared plan</h3><div class="vb-add-item-grid"><label>Name<input class="input" required name="title" placeholder="Sunset dinner"></label><label>Type<select class="input" name="item_type"><option value="idea">Idea</option><option value="food">Food</option><option value="activity">Activity</option><option value="experience">Experience</option><option value="hotel">Hotel</option><option value="flight">Flight</option></select></label><label>Date<input class="input" type="date" name="scheduled_date"></label><label>Daypart<select class="input" name="daypart"><option value="anytime">Anytime</option><option value="morning">Morning</option><option value="afternoon">Afternoon</option><option value="evening">Evening</option></select></label><?php if(!empty($access['can_view_budget'])):?><label>Estimate<input class="input" type="number" min="0" step="0.01" name="price"></label><?php endif;?><label class="wide">Note<input class="input" name="notes" maxlength="1000" placeholder="Shared planning note"></label></div><button class="button primary small" type="submit">Add item</button></form><?php endif;?>
    </section>

    <aside class="vb-shared-side">
      <article class="dashboard-card"><div class="eyebrow">Traveler board</div><h2>Who’s in?</h2><div class="vb-mini-members"><?php foreach($members as $member):?><div><strong><?=e((string)$member['display_name'])?></strong><span><?=e($roleLabels[(string)$member['role']]??'Traveler')?> · <?=e($rsvpLabels[(string)$member['rsvp']]??'No RSVP')?></span></div><?php endforeach;?></div><?php if($mine&&empty($access['is_owner'])&&!empty($access['can_vote'])):?><form class="vb-rsvp-inline" method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="command" value="rsvp"><select class="input" name="rsvp"><?php foreach($rsvpLabels as $value=>$label):?><option value="<?=$value?>" <?=((string)$mine['rsvp']===$value)?'selected':''?>><?=e($label)?></option><?php endforeach;?></select><button class="button secondary small" type="submit">Update RSVP</button></form><?php elseif($mine&&((string)$access['role']==='viewer')):?><p class="muted">Viewer access is read-only. The owner can change your role if you need to RSVP or vote.</p><?php endif;?></article>

      <article class="dashboard-card"><div class="eyebrow">Trip logistics</div><h2>Safe booking summary</h2><?php if(!empty($access['can_view_bookings'])):?><?php if($bookings):?><div class="vb-booking-list"><?php foreach($bookings as $booking):?><div><strong><?=e((string)$booking['title'])?></strong><span><?=e(ucfirst((string)$booking['booking_type']))?> · <?=e((string)($booking['provider_name']?:'Provider'))?> · <?=e(ucwords(str_replace('_',' ',(string)$booking['status'])))?></span><?php if(!empty($booking['starts_at'])):?><small><?=e(date('M j · g:i A',strtotime((string)$booking['starts_at'])))?><?php if(!empty($booking['location_name'])):?> · <?=e((string)$booking['location_name'])?><?php endif;?></small><?php endif;?></div><?php endforeach;?></div><?php else:?><p class="muted">No active booking summaries yet.</p><?php endif;?><?php else:?><p class="muted">Booking logistics are hidden for Viewer access.</p><?php endif;?></article>

      <article class="dashboard-card"><div class="eyebrow">Group activity</div><h2>Recent changes</h2><?php if($events):?><div class="vb-event-list"><?php foreach(array_slice($events,0,10) as $event):?><div><strong><?=e(ucwords(str_replace('_',' ',(string)$event['event_type'])))?></strong><span><?=e((string)($event['actor_name']?:$event['actor_username']?:'Vacation Brain'))?> · <?=e(date('M j · g:i A',strtotime((string)$event['created_at'])))?></span></div><?php endforeach;?></div><?php else:?><p class="muted">No collaboration changes yet.</p><?php endif;?></article>
    </aside>
  </div>
</div></section>
<?php require __DIR__.'/partials/footer.php';?>
