<?php
require __DIR__.'/app/bootstrap.php';$userId=require_auth();$pdo=db();$service=new SwipeService($pdo);
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$r=$service->answer($userId,(int)($_POST['content_id']??0),(int)($_POST['choice_id']??0));$p=(new VacationProfileService($pdo))->snapshot($userId);$msg='Profile updated. +'.$r['points'].' Vacation Brain points. Current type: '.$p['archetype']['name'].'.';if($r['unlocked'])$msg.=' Achievement unlocked: '.$r['unlocked'][0]['name'].'.';flash('success',$msg);}catch(Throwable $e){flash('error',$e->getMessage());}redirect('swipe.php');}
$card=$service->nextCard($userId);$stats=$service->stats($userId);$profile=(new VacationProfileService($pdo))->snapshot($userId);$success=flash('success');$error=flash('error');$title='Swipe — Vacation Brain';require __DIR__.'/partials/header.php';
?>
<section class="dashboard"><div class="shell narrow"><div class="dashboard-head"><div><div class="eyebrow">Vacation Swipe</div><h1>Make bad hypothetical decisions.</h1><p class="muted">The jokes are the onboarding. Every choice sharpens your Vacation Brain profile.</p></div><div class="swipe-stats"><strong><?=$stats['answered']?></strong><span>answered</span><em><?=e($profile['archetype']['name'])?></em></div></div>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(!$card):?><article class="dashboard-card center"><h2>No cards installed yet.</h2><p class="muted">The launch seed library has not been imported.</p></article><?php else:?>
<article class="quiz-card feed-card"><div class="kicker"><?=e(str_replace('_',' ',$card['content_type']))?></div><h1><?=e($card['title'])?></h1><p class="sub"><?=e($card['body'])?></p><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="content_id" value="<?=(int)$card['id']?>"><div class="choice-grid"><?php foreach($card['choices'] as $choice):?><button class="choice" name="choice_id" value="<?=(int)$choice['id']?>"><?=e($choice['label'])?></button><?php endforeach;?></div></form><div class="swipe-foot"><span><?=$stats['total']>0?number_format(min(100,($stats['answered']/$stats['total'])*100),0):0?>% of the launch feed investigated</span><a href="<?=e(app_url('swipe.php'))?>">Skip this card →</a></div></article>
<div class="swipe-insight"><span>VACATION BRAIN IS LEARNING</span><strong><?=e($profile['archetype']['description'])?></strong><a href="<?=e(app_url('profile.php'))?>">See what else it thinks it knows →</a></div><?php endif;?></div></section><?php require __DIR__.'/partials/footer.php';?>
