<?php
require __DIR__ . '/app/bootstrap.php';
$userId=require_auth();$pdo=db();
if ($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='checkin') {verify_csrf();try{$r=(new CheckinService($pdo))->checkIn($userId,(string)($_POST['response']??'yes'));flash('success',$r['message']);}catch(Throwable $e){flash('error','The check-in did not save.');}redirect('today.php');}
$user=current_user();$profile=(new VacationProfileService($pdo))->snapshot($userId);$summary=$profile['summary'];$score=$profile['score'];$streak=(int)($summary['current_streak']??0);
$stmt=$pdo->prepare('SELECT a.id,a.name,a.description,ua.unlocked_at FROM user_achievements ua JOIN achievements a ON a.id=ua.achievement_id WHERE ua.user_id=? AND ua.completed=1 ORDER BY ua.unlocked_at DESC LIMIT 3');$stmt->execute([$userId]);$achievements=$stmt->fetchAll();
$stmt=$pdo->prepare('SELECT id FROM daily_checkins WHERE user_id=? AND checkin_date=?');$stmt->execute([$userId,date('Y-m-d')]);$checkedToday=(bool)$stmt->fetch();
$seedComment=(new FunContentService($pdo))->random('agent_comment',$userId);$agentLine=$seedComment?(string)$seedComment['body']:($checkedToday?'Today is counted. The condition remains aggressively vacation-related.':'Have you thought about vacation today, or do I need to open a beach tab for you?');
$dreams=(new DreamService($pdo))->all($userId);$latestDream=$dreams[0]??null;$success=flash('success');$error=flash('error');$title='Today — Vacation Brain';require __DIR__.'/partials/header.php';
?>
<section class="dashboard today-v2"><div class="shell">
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="today-hero"><div><div class="eyebrow">Today</div><h1>Hi, <?=e($user['display_name']?:'Vacation Brain')?>.</h1><p><?=e($agentLine)?></p><div class="today-actions"><a class="button primary" href="<?=e(app_url('swipe.php'))?>">Answer one ridiculous question</a><a class="button secondary" href="<?=e(app_url('escape.php'))?>">Escape for a minute</a></div></div><div class="brain-score-panel"><span>VACATION BRAIN SCORE</span><strong><?=$score?></strong><em><?=e($profile['level']['title'])?></em><div class="level-track"><i style="width:<?=round($profile['level']['progress'])?>%"></i></div><?php if($profile['level']['next']):?><small><?=$profile['level']['remaining']?> points until <?=e($profile['level']['next']['title'])?></small><?php else:?><small>There is no higher administrative classification.</small><?php endif;?></div></div>
<div class="today-grid"><article class="daily-card"><span>DAILY CHECK-IN</span><h2><?=$checkedToday?'Day '.$streak.' is officially on the record.':'Did you think about vacation today?'?></h2><p><?=$checkedToday?'You may continue your daydreaming without additional paperwork.':'This is a highly scientific measure of how mentally unavailable you are becoming.'?></p><?php if(!$checkedToday):?><form method="post" class="checkin-actions"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="checkin"><button class="button primary" name="response" value="obviously">Obviously</button><button class="button secondary" name="response" value="now_i_am">No, but now I am</button></form><?php else:?><div class="streak-chip">🔥 <?=$streak?> day streak</div><?php endif;?></article>
<article class="archetype-card"><span>YOUR CURRENT TYPE</span><h2><?=e($profile['archetype']['name'])?></h2><p><?=e($profile['archetype']['description'])?></p><a href="<?=e(app_url('profile.php'))?>">Why Vacation Brain thinks this →</a></article>
<article class="roast-mini"><span>TODAY'S FINDING</span><p>“<?=e($profile['roasts'][0]??'You appear to remain interested in not being here.')?>”</p><a href="<?=e(app_url('roast.php'))?>">Roast me properly →</a></article></div>
<div class="section-head"><div><span class="eyebrow">Your Brain</span><h2>What it has learned so far</h2></div><a href="<?=e(app_url('profile.php'))?>">Full profile →</a></div><div class="signal-grid"><?php foreach(array_slice($profile['signals'],0,4) as $signal):?><div><strong><?=e($signal['label'])?></strong><span><?=$signal['value']?>%</span><div class="trait-meter"><i style="width:<?=$signal['value']?>%"></i></div></div><?php endforeach;?></div>
<div class="section-head"><div><span class="eyebrow">Keep Feeding It</span><h2>Pick your form of procrastination</h2></div></div><div class="fun-strip"><a href="<?=e(app_url('weather-envy.php'))?>"><b>Weather Envy</b><span>Compare your reality to somewhere better.</span></a><a href="<?=e(app_url('breaks.php'))?>"><b>Vacation Break</b><span>Disappear mentally for 1–5 minutes.</span></a><a href="<?=e(app_url('dream.php'))?>"><b><?= $latestDream?'Reopen '.$latestDream['name']:'Start a Dream Trip' ?></b><span><?= $latestDream?e($latestDream['temperature']):'No dates. No pressure. Just vibes.' ?></span></a><a href="<?=e(app_url('matching.php'))?>"><b>Travel Matching</b><span>Find someone who can survive your vacation opinions.</span></a></div>
<?php if($achievements):?><div class="section-head"><div><span class="eyebrow">Recent Evidence</span><h2>Achievements unlocked</h2></div></div><div class="achievement-strip"><?php foreach($achievements as $a):?><div><strong><?=e($a['name'])?></strong><span><?=e($a['description'])?></span></div><?php endforeach;?></div><?php endif;?>
</div></section><?php require __DIR__.'/partials/footer.php';?>
