<?php
require __DIR__.'/app/bootstrap.php';

$userId=require_auth();$tripId=(int)($_GET['id']??$_POST['trip_id']??0);if($tripId<1){http_response_code(400);exit('Trip is required.');}
$service=new TripAffordabilityService(db());$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        if(!$service->ready())throw new RuntimeException('Run System Upgrade for Budget-Aware Trip Planning + Affordability Intelligence.');
        $action=(string)($_POST['action']??'');
        if($action==='save_settings'){$service->saveSettings($userId,$tripId,$_POST);flash('success','Affordability assumptions updated.');}
        elseif($action==='save_scenario'){$service->saveScenario($userId,$tripId,$_POST);flash('success','Comparison scenario saved.');}
        elseif($action==='delete_scenario'){$service->deleteScenario($userId,$tripId,(int)($_POST['scenario_id']??0));flash('success','Comparison scenario removed.');}
        else throw new InvalidArgumentException('Unknown affordability action.');
        redirect('trip-affordability.php?id='.$tripId);
    }catch(InvalidArgumentException|DomainException|OutOfBoundsException $e){$error=$e->getMessage();}
    catch(Throwable $e){error_log('Affordability update failed: '.$e->getMessage());$error='Vacation Brain could not update affordability planning safely.';}
}
try{$snapshot=$service->snapshot($userId,$tripId);}catch(OutOfBoundsException){http_response_code(404);exit('Trip not found.');}
$trip=$snapshot['trip'];$forecast=$snapshot['forecast']??[];$owner=!empty($snapshot['can_manage']);$canView=!empty($snapshot['can_view']);$success=flash('success');$title='Affordability — '.$trip['name'];$pageStyles=['assets/trip-affordability.css'];$currency=(string)($trip['currency']??'USD');
function vb_aff_money(mixed $v,string $currency):string{if($v===null||$v==='')return '—';return ($currency==='USD'?'$':$currency.' ').number_format((float)$v,2);}
function vb_aff_label(string $v):string{return ucwords(str_replace('_',' ',$v));}
require __DIR__.'/partials/header.php';
?>
<section class="vb-aff-page"><div class="shell vb-aff-shell">
<header class="vb-aff-head"><div><a class="back-link" href="<?=e(app_url('dream-trip.php?id='.$tripId.'&workspace=affordability'))?>">← Trip workspace</a><span class="eyebrow">Budget-Aware Trip Planning</span><h1>Can this trip fit the budget without ruining the trip?</h1><p>Vacation Brain combines saved booking values, category plans, saved provider estimates and role-appropriate cost history into a planning forecast. It never treats an estimate as a quote or a booking value as bank settlement.</p></div><div class="vb-aff-head-actions"><a class="button secondary" href="<?=e(app_url('trip-cost.php?id='.$tripId))?>">True Trip Economics</a><a class="button secondary" href="<?=e(app_url('dream-trip.php?id='.$tripId))?>">Trip Plan</a></div></header>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(!$snapshot['ready']):?><div class="alert error"><strong>Affordability Intelligence needs migration 060 / app v1.52.</strong> <?php if(is_admin()):?><a href="<?=e(app_url('upgrade.php'))?>">Run System Upgrade</a><?php endif;?></div><?php endif;?>
<div class="vb-aff-notice"><strong>No hidden FX and no financial execution.</strong> Currency buckets never convert implicitly. This page cannot pay, book, cancel, modify reservations, submit claims, request refunds, redeem credits, open checkout or mutate a provider.</div>
<?php if(!$canView):?>
<section class="vb-aff-card"><span class="eyebrow">Role-aware privacy</span><h2>Budget projections are not available to this trip role.</h2><p>Owner and Co-planner roles can work with shared affordability planning. Traveler and Viewer roles stay outside the trip budget model.</p></section>
<?php else:$risk=(string)($forecast['risk_status']??'unknown');$headroom=$forecast['headroom']??null;?>
<section class="vb-aff-scoreboard" data-risk="<?=e($risk)?>">
<article><span>Budget status</span><strong><?=e(vb_aff_label($risk))?></strong><small><?=e(ucfirst((string)($forecast['confidence']??'low')))?> confidence</small></article>
<article><span>Target budget</span><strong><?=e(vb_aff_money($forecast['target_budget']??null,$currency))?></strong><small><?=$forecast['target_budget']===null?'Set a trip budget to score risk':'Trip currency only'?></small></article>
<article><span>Saved booking value</span><strong><?=e(vb_aff_money($forecast['booked_value']??0,$currency))?></strong><small>Not verified bank settlement</small></article>
<article><span>Expected final cost</span><strong><?=e(vb_aff_money($forecast['expected_final']??0,$currency))?></strong><small>Planning forecast, not quote</small></article>
<article><span>Expected remaining</span><strong><?=e(vb_aff_money($forecast['expected_remaining']??0,$currency))?></strong><small>Beyond saved booking value</small></article>
<article><span><?=$headroom!==null&&$headroom<0?'Over target':'Forecast headroom'?></span><strong><?=e(vb_aff_money($headroom===null?null:abs((float)$headroom),$currency))?></strong><small><?=$forecast['budget_ratio_pct']!==null?e((string)$forecast['budget_ratio_pct']).'% of target':'No target yet'?></small></article>
</section>
<div class="vb-aff-grid"><main>
<section class="vb-aff-card"><span class="eyebrow">Forecast anatomy</span><h2>What is driving the expected cost?</h2><p>Each category uses the strongest available signal: saved booking value, explicit category plan, saved live-provider estimate, or owner-only learned history. A scenario override can never reduce below a value already represented by a saved booking.</p><div class="vb-aff-table-wrap"><table class="vb-aff-table"><thead><tr><th>Category</th><th>Booked</th><th>Plan</th><th>Live</th><th>History</th><th>Expected</th><th>Source</th></tr></thead><tbody><?php foreach((array)($forecast['categories']??[]) as $cat=>$row):?><tr><td><?=e((string)$row['label'])?></td><td><?=e(vb_aff_money($row['booked'],$currency))?></td><td><?=e(vb_aff_money($row['planned'],$currency))?></td><td><?=e(vb_aff_money($row['live_estimate'],$currency))?></td><td><?=$owner?e(vb_aff_money($row['history_estimate'],$currency)):'Private'?></td><td><strong><?=e(vb_aff_money($row['expected'],$currency))?></strong></td><td><?=e(vb_aff_label((string)$row['source']))?></td></tr><?php endforeach;?></tbody></table></div><div class="vb-aff-reserves"><div><span>Forecast subtotal</span><strong><?=e(vb_aff_money($forecast['forecast_subtotal']??0,$currency))?></strong></div><div><span>Contingency · <?=e((string)$forecast['contingency_pct'])?>%</span><strong><?=e(vb_aff_money($forecast['contingency']??0,$currency))?></strong></div><div><span>Disruption reserve · <?=e((string)$forecast['disruption_reserve_pct'])?>%</span><strong><?=e(vb_aff_money($forecast['disruption_reserve']??0,$currency))?></strong></div></div></section>
<section class="vb-aff-card"><span class="eyebrow">Make this trip fit my budget</span><h2>Non-destructive options first.</h2><?php if(empty($snapshot['fit_suggestions'])):?><p><?=($forecast['target_budget']??null)===null?'Set a target budget to generate budget-fit options.':'The current forecast is within the target. Vacation Brain will keep the reserve visible instead of inventing cuts.'?></p><?php else:?><div class="vb-aff-fit-list"><?php foreach($snapshot['fit_suggestions'] as $suggestion):?><article><div><strong><?=e((string)$suggestion['title'])?></strong><p><?=e((string)$suggestion['body'])?></p><small>Tradeoff: <?=e((string)$suggestion['tradeoff'])?></small></div><b>~<?=e(vb_aff_money($suggestion['estimated_savings'],$currency))?></b></article><?php endforeach;?></div><p class="vb-aff-fineprint">Savings are scenario estimates, not current provider quotes. No reservation is changed by these options.</p><?php endif;?></section>
<?php if($owner):?><section class="vb-aff-card"><span class="eyebrow">Scenario lab</span><h2>Compare a different trip shape before changing the real plan.</h2><form method="post" class="vb-aff-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="save_scenario"><input type="hidden" name="currency" value="<?=e($currency)?>"><div class="vb-aff-form-grid"><label>Scenario name<input required name="label" maxlength="120" placeholder="4 nights + cheaper hotel"></label><label>Travelers<input type="number" min="1" max="30" name="travelers" placeholder="<?=(int)$trip['travelers']?>"></label><label>Duration days<input type="number" min="1" max="120" name="duration_days" placeholder="<?=(int)($forecast['duration_days']??1)?>"></label><label>Target budget<input type="number" min="0" step="0.01" name="target_budget" placeholder="<?=e((string)($forecast['target_budget']??''))?>"></label><label>Flights<input type="number" min="0" step="0.01" name="flight_override" placeholder="Optional"></label><label>Lodging<input type="number" min="0" step="0.01" name="lodging_override" placeholder="Optional"></label><label>Transportation<input type="number" min="0" step="0.01" name="transport_override" placeholder="Optional"></label><label>Food<input type="number" min="0" step="0.01" name="food_override" placeholder="Optional"></label><label>Activities<input type="number" min="0" step="0.01" name="activity_override" placeholder="Optional"></label><label>Events<input type="number" min="0" step="0.01" name="event_override" placeholder="Optional"></label><label>Shopping<input type="number" min="0" step="0.01" name="shopping_override" placeholder="Optional"></label><label>Fees<input type="number" min="0" step="0.01" name="fees_override" placeholder="Optional"></label></div><button class="button primary" type="submit">Save comparison scenario</button></form>
<?php if(!empty($snapshot['scenarios'])):?><div class="vb-aff-scenarios"><?php foreach($snapshot['scenarios'] as $scenario):?><article><div class="vb-aff-scenario-head"><div><span class="eyebrow">Value score <?=(int)$scenario['value_score']?>/100</span><strong><?=e((string)$scenario['label'])?></strong></div><b><?=e(vb_aff_money($scenario['expected_final'],$currency))?></b></div><div class="vb-aff-scenario-meta"><span><?=e(vb_aff_label((string)$scenario['risk_status']))?></span><span><?=(int)$scenario['duration_days']?> days</span><span><?=(int)$scenario['travelers']?> traveler<?=((int)$scenario['travelers']===1?'':'s')?></span><?php if((float)$scenario['estimated_savings']>0):?><span>~<?=e(vb_aff_money($scenario['estimated_savings'],$currency))?> savings</span><?php endif;?></div><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="delete_scenario"><input type="hidden" name="scenario_id" value="<?=(int)$scenario['scenario_id']?>"><button class="button secondary small" type="submit">Remove scenario</button></form></article><?php endforeach;?></div><?php endif;?></section><?php endif;?>
</main><aside>
<section class="vb-aff-card"><span class="eyebrow">Trip shape</span><h2><?=e((string)$forecast['duration_days'])?> days · <?=e((string)$forecast['travelers'])?> traveler<?=((int)$forecast['travelers']===1?'':'s')?></h2><p><?=e((string)$forecast['semantics'])?></p><?php if(!empty($forecast['live_observed_at'])):?><small>Saved provider estimate observed <?=e((string)$forecast['live_observed_at'])?>. Refresh live trip intelligence if you need a newer market signal.</small><?php endif;?></section>
<?php if($owner):$settings=$snapshot['settings'];?><section class="vb-aff-card"><span class="eyebrow">Forecast policy</span><h2>How conservative should planning be?</h2><form method="post" class="vb-aff-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="save_settings"><label>Risk tolerance<select name="risk_tolerance"><?php foreach(['comfortable'=>'Comfortable','balanced'=>'Balanced','stretch'=>'Stretch'] as $v=>$l):?><option value="<?=$v?>" <?=$settings['risk_tolerance']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>Contingency %<input type="number" min="0" max="50" step="0.5" name="contingency_pct" value="<?=e((string)$settings['contingency_pct'])?>"></label><label>Disruption reserve %<input type="number" min="0" max="50" step="0.5" name="disruption_reserve_pct" value="<?=e((string)$settings['disruption_reserve_pct'])?>"></label><label>Inbox overage alert %<input type="number" min="0" max="100" step="0.5" name="alert_overage_pct" value="<?=e((string)$settings['alert_overage_pct'])?>"></label><label class="vb-aff-check"><input type="checkbox" name="include_learned_history" value="1" <?=!empty($settings['include_learned_history'])?'checked':''?>> Use aggregate completed-trip cost history</label><button class="button primary" type="submit">Save forecast policy</button></form><small>Learned history is owner-only and reduced to aggregate cost baselines before use.</small></section><?php endif;?>
<section class="vb-aff-card"><span class="eyebrow">Privacy & execution boundary</span><p><?=e((string)$snapshot['privacy_note'])?></p><p><?=e((string)$snapshot['safety_note'])?></p></section>
</aside></div>
<?php endif;?>
</div></section>
<?php require __DIR__.'/partials/footer.php';?>
