<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$service=new TripItineraryIntelligenceService($pdo);$tripId=(int)($_GET['id']??$_POST['trip_id']??0);$date=(string)($_GET['date']??$_POST['date']??'');$error='';
if($tripId<1){http_response_code(400);exit('Trip is required.');}
try{$access=$service->access($userId,$tripId);}catch(Throwable){http_response_code(404);exit('Trip not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        if(!$service->ready())throw new RuntimeException('Run System Upgrade before editing Complete Itinerary Intelligence.');$action=(string)($_POST['action']??'');
        if($action==='save_item_timing'){$service->saveItemTiming($userId,$tripId,(int)($_POST['item_id']??0),$_POST);flash('success','Itinerary timing saved and the trip was rechecked for downstream conflicts.');}
        elseif($action==='apply_order'){$count=$service->applySuggestedOrder($userId,$tripId,$date);flash('success',$count.' flexible itinerary item'.($count===1?'':'s').' sequenced. Fixed reservations were not moved.');}
        elseif($action==='save_preferences'){$service->savePreferences($userId,$tripId,$_POST);flash('success','Timing and buffer preferences saved.');}
        elseif($action==='refresh'){$service->snapshot($userId,$tripId,$date?:null,true);flash('success','Itinerary intelligence recalculated from saved trip facts. No provider was contacted.');}
        else throw new InvalidArgumentException('Unknown itinerary action.');
        redirect('trip-itinerary.php?id='.$tripId.($date!==''?'&date='.rawurlencode($date):''));
    }catch(Throwable $e){$error=$e->getMessage();}
}
try{$snapshot=$service->snapshot($userId,$tripId,$date?:null,true);}catch(Throwable $e){$error=$e->getMessage();$snapshot=['ready'=>false,'trip'=>['name'=>'Trip','destination_name'=>''],'access'=>$access,'selected_date'=>$date?:date('Y-m-d'),'dates'=>[],'timeline'=>[],'issues'=>[],'gaps'=>[],'unscheduled'=>[],'summary'=>[],'preferences'=>$service->preferences($tripId),'map_points'=>[]];}
$trip=$snapshot['trip'];$access=$snapshot['access']??$access;$canPlan=!empty($access['can_plan']);$date=(string)$snapshot['selected_date'];$success=flash('success');$title='Itinerary — '.(string)$trip['name'];$pageStyles=['assets/trip-itinerary-intelligence.css'];
function iti_time(?string $value): string{return $value&&strtotime($value)?date('H:i',strtotime($value)):'';}
function iti_type(string $type): string{return ucwords(str_replace('_',' ',$type));}
require __DIR__.'/partials/header.php';
?>
<section class="trip-itinerary-page"><div class="shell trip-itinerary-shell">
<header class="trip-intelligence-head"><div><a class="back-link" href="<?=e(app_url('dream-trip.php?id='.$tripId.'&workspace=timeline&itinerary_date='.rawurlencode($date)))?>">← Trip timeline workspace</a><div class="eyebrow">Complete Itinerary Intelligence · <?=e(ucwords(str_replace('_',' ',(string)$access['role'])))?></div><h1><?=e((string)$trip['name'])?></h1><p><?=e((string)($trip['destination_name']?:'Destination TBD'))?> · fixed bookings + flexible plan + transfer intelligence</p></div><div class="trip-intelligence-head-actions"><a class="button secondary small" href="<?=e(app_url('travel-mode.php?id='.$tripId.'&date='.rawurlencode($date)))?>">Travel Mode</a><a class="button secondary small" href="<?=e(app_url('trip-inbox.php?trip='.$tripId))?>">Trip Inbox</a><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="date" value="<?=e($date)?>"><input type="hidden" name="action" value="refresh"><button class="button primary small" type="submit">Recalculate</button></form></div></header>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(empty($snapshot['ready'])):?><div class="trip-intel-alert"><strong>Complete Itinerary Intelligence needs migration 055 / app v1.47.</strong> <?php if(is_admin()):?><a href="<?=e(app_url('upgrade.php'))?>">Run System Upgrade</a><?php endif;?></div><?php else:?>
<section class="vb-itinerary-intelligence-wrap">
<div class="vb-itinerary-head"><div><span class="eyebrow">Door-to-door timing</span><h2><?=e(date('l, F j',strtotime($date)))?></h2><p>Preparation buffers and transfer estimates are derived from saved trip facts. They do not represent live traffic, security-line or provider guarantees.</p></div><?php if($canPlan):?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="date" value="<?=e($date)?>"><input type="hidden" name="action" value="apply_order"><button class="button secondary small" type="submit">Apply suggested flexible order</button></form><?php endif;?></div>
<div class="vb-itinerary-stats"><article><strong><?=(int)($snapshot['summary']['fixed']??0)?></strong><span>Fixed anchors</span></article><article><strong><?=(int)($snapshot['summary']['flexible']??0)?></strong><span>Flexible plans</span></article><article class="<?=((int)($snapshot['summary']['high_issues']??0)>0)?'danger':''?>"><strong><?=(int)($snapshot['summary']['high_issues']??0)?></strong><span>High conflicts</span></article><article><strong><?=(int)($snapshot['summary']['open_gaps']??0)?></strong><span>Open gaps</span></article></div>
<nav class="vb-itinerary-days" aria-label="Itinerary days"><?php foreach((array)$snapshot['dates'] as $d):?><a class="<?=$d===$date?'active':''?>" href="<?=e(app_url('trip-itinerary.php?id='.$tripId.'&date='.$d))?>"><strong><?=e(date('D',strtotime($d)))?></strong><span><?=e(date('M j',strtotime($d)))?></span></a><?php endforeach;?></nav>
<?php if(!empty($snapshot['issues'])):?><div class="vb-itinerary-issues"><?php foreach($snapshot['issues'] as $issue):?><article class="severity-<?=e((string)$issue['severity'])?>"><span><?=e(strtoupper((string)$issue['severity']))?></span><div><strong><?=e((string)$issue['title'])?></strong><p><?=e((string)$issue['body'])?></p></div></article><?php endforeach;?></div><?php endif;?>
<div class="vb-itinerary-timeline"><?php foreach($snapshot['timeline'] as $entry):?><article class="vb-itinerary-row <?=!empty($entry['fixed'])?'fixed':'flexible'?>"><div class="vb-itinerary-time"><strong><?=e((string)$entry['time_label'])?></strong><span><?=!empty($entry['fixed'])?'Fixed':'Flexible'?></span></div><div class="vb-itinerary-marker"><i></i></div><div class="vb-itinerary-copy"><div class="vb-itinerary-title"><strong><?=e((string)$entry['title'])?></strong><span><?=e(iti_type((string)$entry['type']))?></span></div><?php $loc=trim((string)$entry['location']);$addr=trim((string)$entry['address']);if($loc||$addr):?><p><?=e($loc.($loc&&$addr?' · ':'').$addr)?></p><?php endif;?><?php if(!empty($entry['transition'])):?><small><?=e((string)$entry['transition']['label'])?><?php if($entry['leave_by']):?> · Leave by <?=e(date('g:i A',strtotime((string)$entry['leave_by'])) )?><?php endif;?><?php if($entry['arrive_by']):?> · Target arrival <?=e(date('g:i A',strtotime((string)$entry['arrive_by'])))?><?php endif;?></small><?php elseif($entry['arrive_by']):?><small>Target arrival <?=e(date('g:i A',strtotime((string)$entry['arrive_by'])))?></small><?php endif;?></div></article><?php endforeach;?><?php if(empty($snapshot['timeline'])):?><div class="vb-itinerary-empty"><strong>No timed plan for this day.</strong><span>Assign itinerary ideas to <?=e(date('M j',strtotime($date)))?> or import a confirmed reservation.</span></div><?php endif;?></div>
<?php if(!empty($snapshot['gaps'])):?><div class="vb-itinerary-gap-row"><?php foreach($snapshot['gaps'] as $gap):?><a href="<?=e(app_url('local-concierge.php?id='.$tripId))?>"><strong><?=e((string)$gap['title'])?> · <?=round((int)$gap['minutes']/60,1)?>h</strong><span><?=e((string)$gap['body'])?> Ask Local Agent for ideas.</span></a><?php endforeach;?></div><?php endif;?>
</section>
<div class="trip-itinerary-editor"><main class="trip-itinerary-editor-main">
<?php if($canPlan):?><section class="trip-itinerary-edit-card"><span class="eyebrow">Flexible plan editor</span><h2>Set exact times, places and flexibility.</h2><p class="muted small">Only shared itinerary rows are editable here. Confirmed bookings remain fixed in Bookings & Wallet.</p></section><?php endif;?>
<?php $editable=array_merge(array_values(array_filter($snapshot['timeline'],fn($e)=>($e['source']??'')==='itinerary')),array_values(array_filter($snapshot['unscheduled'],fn($e)=>($e['source']??'')==='itinerary')));foreach($editable as $entry):?>
<article class="trip-itinerary-edit-card"><h3><?=e((string)$entry['title'])?> <span class="muted small">· <?=e(iti_type((string)$entry['type']))?></span></h3><?php if($canPlan):?><form class="trip-itinerary-edit-form" method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="date" value="<?=e($date)?>"><input type="hidden" name="action" value="save_item_timing"><input type="hidden" name="item_id" value="<?=(int)$entry['item_id']?>"><label>Date<input class="input" type="date" name="scheduled_date" value="<?=e((string)($entry['date']??''))?>"></label><label>Start<input class="input" type="time" name="start_time" value="<?=e(iti_time($entry['starts_at']))?>"></label><label>End<input class="input" type="time" name="end_time" value="<?=e(iti_time($entry['ends_at']))?>"></label><label>Timing<select class="input" name="timing_mode"><?php foreach(['fixed'=>'Fixed','flexible'=>'Flexible','anytime'=>'Anytime'] as $v=>$l):?><option value="<?=$v?>" <?=$entry['timing_mode']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>Daypart<select class="input" name="daypart"><?php foreach(['morning'=>'Morning','afternoon'=>'Afternoon','evening'=>'Evening','anytime'=>'Anytime'] as $v=>$l):?><option value="<?=$v?>" <?=$entry['daypart']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>Duration<input class="input" type="number" min="15" max="1440" name="duration_minutes" value="<?=($entry['start_ts']&&$entry['end_ts'])?(int)(($entry['end_ts']-$entry['start_ts'])/60):''?>"></label><label>Buffer before<input class="input" type="number" min="0" max="480" name="buffer_before_minutes" value="<?=(int)$entry['buffer_before']?>"></label><label>Buffer after<input class="input" type="number" min="0" max="480" name="buffer_after_minutes" value="<?=(int)$entry['buffer_after']?>"></label><label class="wide">Location<input class="input" name="location_name" value="<?=e((string)$entry['location'])?>" placeholder="Museum, restaurant, hotel…"></label><label class="wide">Address<input class="input" name="location_address" value="<?=e((string)$entry['address'])?>"></label><label>Latitude<input class="input" inputmode="decimal" name="latitude" value="<?=e($entry['latitude']!==null?(string)$entry['latitude']:'')?>"></label><label>Longitude<input class="input" inputmode="decimal" name="longitude" value="<?=e($entry['longitude']!==null?(string)$entry['longitude']:'')?>"></label><div class="form-actions"><button class="button primary small" type="submit">Save & recheck</button></div></form><?php else:?><p class="muted">Your <?=e(ucwords(str_replace('_',' ',(string)$access['role'])))?> role can view this timing plan but cannot edit the shared itinerary.</p><?php endif;?></article>
<?php endforeach;?>
</main><aside class="trip-itinerary-editor-side">
<section class="trip-itinerary-edit-card"><span class="eyebrow">Route order</span><h3>Stops with saved coordinates</h3><div class="trip-itinerary-route"><?php $n=0;foreach($snapshot['timeline'] as $entry){if($entry['latitude']===null||$entry['longitude']===null)continue;$n++;?><article><b><?=$n?></b><div><strong><?=e((string)$entry['title'])?></strong><span><?=e((string)($entry['location']?:$entry['address']))?></span></div></article><?php }?><?php if($n===0):?><p class="muted small">Add public venue coordinates to flexible itinerary items to enable geographic sequencing. Current-device coordinates are never used here.</p><?php endif;?></div></section>
<?php if($canPlan):?><section class="trip-itinerary-edit-card"><span class="eyebrow">Timing policy</span><h3>Default planning buffers</h3><form class="trip-itinerary-pref-form" method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="date" value="<?=e($date)?>"><input type="hidden" name="action" value="save_preferences"><?php $p=$snapshot['preferences'];?><label>Domestic airport min<input class="input" type="number" name="airport_domestic_minutes" value="<?=(int)$p['airport_domestic_minutes']?>"></label><label>International airport min<input class="input" type="number" name="airport_international_minutes" value="<?=(int)$p['airport_international_minutes']?>"></label><label>Station buffer<input class="input" type="number" name="station_buffer_minutes" value="<?=(int)$p['station_buffer_minutes']?>"></label><label>Venue buffer<input class="input" type="number" name="venue_buffer_minutes" value="<?=(int)$p['venue_buffer_minutes']?>"></label><label>Default transfer<input class="input" type="number" name="default_transfer_minutes" value="<?=(int)$p['default_transfer_minutes']?>"></label><label>Hotel check-in hour<input class="input" type="number" min="0" max="23" name="hotel_checkin_hour" value="<?=(int)$p['hotel_checkin_hour']?>"></label><label>Hotel checkout hour<input class="input" type="number" min="0" max="23" name="hotel_checkout_hour" value="<?=(int)$p['hotel_checkout_hour']?>"></label><button class="button secondary small" type="submit">Save timing policy</button></form></section><?php endif;?>
<section class="trip-itinerary-edit-card"><span class="eyebrow">Safety boundary</span><h3>Planning math is not a provider action.</h3><p class="muted small">Vacation Brain can recalculate timing, conflicts and flexible ordering automatically. Booking, cancellation, checkout, purchase, refund and destructive provider changes still require their existing explicit transaction approval and verification flows.</p></section>
</aside></div>
<?php endif;?>
</div></section>
<?php require __DIR__.'/partials/footer.php';?>