<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$tripId=(int)($_GET['id']??$_POST['trip_id']??0);$intel=new TripIntelligenceService($pdo);$error='';
$trip=(new DreamService($pdo))->get($userId,$tripId,false);if(!$trip){http_response_code(404);exit('Trip not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();try{$action=(string)($_POST['action']??'refresh');if($action==='refresh'){$intel->refresh($userId,$tripId,['lodging'],true);flash('success','Live lodging refreshed.');}elseif($action==='add'){$intel->addFromSnapshot($userId,$tripId,'lodging',(string)($_POST['external_id']??''));flash('success','Lodging option added to the trip plan.');}else throw new InvalidArgumentException('Unknown lodging action.');redirect('trip-lodging.php?id='.$tripId);}catch(Throwable $e){$error=$e->getMessage();}
}
$dashboard=$intel->dashboard($userId,$tripId);$trip=$dashboard['trip'];$snapshot=$dashboard['snapshots']['lodging']??null;$lodging=$snapshot['payload']??[];$provider=$dashboard['providers']['lodging']??[];$health=(new TripLiveIntelligenceService($pdo))->health($dashboard)['lodging']??[];$success=flash('success');$title='Live Lodging — '.(string)$trip['name'];$pageStyles=['assets/trip-intelligence.css','assets/live-travel-data.css'];
function vb_lodging_money(mixed $value,string $currency): string{return $value===null||$value===''?'—':($currency==='USD'?'$':$currency.' ').number_format((float)$value,2);}
require __DIR__.'/partials/header.php';
?>
<section class="dashboard"><div class="shell">
<div class="trip-intelligence-head"><div><a class="back-link" href="<?=e(app_url('dream-trip.php?id='.$tripId.'&tab=overview'))?>">← Trip dashboard</a><span class="eyebrow">Live lodging</span><h1>Where are we actually sleeping?</h1><p><?=e((string)$trip['destination_name'])?> · <?=e((string)$trip['date_label'])?> · availability and pricing from the connected lodging provider.</p></div><div class="trip-intelligence-head-actions"><a class="button secondary small" href="<?=e(app_url('trip-bookings.php?id='.$tripId))?>">Booking & readiness</a><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="refresh"><button class="button primary small" type="submit">Refresh lodging</button></form></div></div>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="vb-live-data-panel" style="margin:18px 0"><div class="vb-live-data-head"><div><span class="eyebrow">Provider state</span><h2><?=e((string)($health['label']??'Waiting'))?></h2><p><?=e((string)($health['provider']??$provider['provider']??'Booking.com Demand API'))?> · <?=e((string)($health['freshness']??'No snapshot'))?></p></div><span class="vb-live-data-state <?=e((string)($health['state']??'waiting'))?>"><?=e((string)($health['label']??'Waiting'))?></span></div></div>
<?php if(empty($provider['configured'])):?><div class="alert warning"><strong>Live lodging provider setup is required.</strong> <?php if(is_admin()):?><a href="<?=e(app_url('admin/travel-providers.php'))?>">Configure Booking.com Demand API →</a><?php else:?>An administrator needs to connect the lodging provider.<?php endif;?></div><?php elseif(!empty($lodging['error'])):?><div class="alert warning"><strong>Lodging refresh unavailable.</strong> <?=e((string)$lodging['error'])?></div><?php endif;?>
<?php if(!empty($lodging['ok'])):?><div class="dashboard-card" style="margin-top:18px"><div class="admin-table-head"><div><h2>Current accommodation results</h2><p class="muted"><?=e((string)($lodging['accuracy_note']??''))?></p></div><strong><?=isset($lodging['min_price'])?e('From '.vb_lodging_money($lodging['min_price'],(string)($lodging['currency']??$trip['currency']??'USD'))):''?></strong></div><div class="vb-lodging-grid">
<?php foreach($lodging['items']??[] as $hotel):?><article class="dashboard-card"><span class="eyebrow">Available now</span><h3><?=e((string)$hotel['name'])?></h3><p class="muted"><?=e((string)($hotel['address']??''))?></p><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:12px"><strong><?=e(vb_lodging_money($hotel['price_display']??$hotel['price_total']??null,(string)($hotel['currency']??$lodging['currency']??'USD')))?></strong><span class="muted small"><?=e((string)($hotel['checkin']??''))?> → <?=e((string)($hotel['checkout']??''))?></span></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:13px"><?php if(!empty($hotel['url'])):?><a class="button secondary small" href="<?=e((string)$hotel['url'])?>" target="_blank" rel="noopener">Open provider ↗</a><?php endif;?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="add"><input type="hidden" name="external_id" value="<?=e((string)$hotel['id'])?>"><button class="button primary small" type="submit">Add to trip plan</button></form></div></article><?php endforeach;?>
</div><?php if(empty($lodging['items'])):?><div class="muted" style="padding:16px 0">The provider returned no matching accommodation inventory for these dates and destination.</div><?php endif;?></div><?php else:?><div class="dashboard-card" style="margin-top:18px"><h2>Live lodging is waiting.</h2><p class="muted">Set future trip dates and destination coordinates, connect Booking.com Demand API, then refresh. Saved hotels remain separate from confirmed reservations until you explicitly record the booking.</p></div><?php endif;?>
</div></section>
<style>.vb-lodging-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:16px}.vb-lodging-grid .dashboard-card{margin:0;box-shadow:none}.vb-lodging-grid h3{font-size:20px;margin:6px 0}@media(max-width:980px){.vb-lodging-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.vb-lodging-grid{grid-template-columns:1fr}}</style>
<?php require __DIR__.'/partials/footer.php';?>
