<?php
require __DIR__.'/app/bootstrap.php';

$userId=require_auth();$pdo=db();$tripId=(int)($_GET['id']??$_POST['trip_id']??0);$service=new TripMemoryService($pdo);$error='';
if($tripId<1){http_response_code(400);exit('Trip is required.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{$action=(string)($_POST['action']??'save_draft');if(!in_array($action,['save_draft','complete_memory'],true))throw new InvalidArgumentException('Unknown Trip Memory action.');$service->save($userId,$tripId,$_POST,$action==='complete_memory');flash('success',$action==='complete_memory'?'Trip Memory completed. Vacation Brain can now use the structured feedback in future recommendations.':'Trip Memory draft saved.');redirect('trip-memory.php?id='.$tripId);}catch(Throwable $e){$error=$e->getMessage();}
}
try{$snapshot=$service->snapshot($userId,$tripId);}catch(OutOfBoundsException $e){http_response_code(404);exit('Trip not found.');}
$trip=$snapshot['trip'];$memory=$snapshot['memory'];$stats=$snapshot['stats'];$signals=$snapshot['signals'];$learning=$snapshot['learning'];$success=flash('success');$resolution=[];
try{if(class_exists('TripDisruptionResolutionService')){$resolutionService=new TripDisruptionResolutionService($pdo);if($resolutionService->ready())$resolution=$resolutionService->tripFinancialSummary($userId,$tripId);}}catch(Throwable $e){error_log('Trip Memory resolution summary unavailable: '.$e->getMessage());}
$title='Trip Memory — '.($trip['destination_name']?:$trip['name']);$pageStyles=['assets/trip-memory.css'];
require __DIR__.'/partials/header.php';
?>
<section class="trip-memory-page"><div class="shell trip-memory-shell">
<header class="memory-hero"><div><a class="back-link" href="<?=e(app_url('dream-trip.php?id='.$tripId.'&tab=overview'))?>">← Trip dashboard</a><span class="eyebrow">Post-trip intelligence</span><h1><?=e($trip['destination_name']?:$trip['name'])?> is now part of your Vacation Brain.</h1><p>Capture what actually happened, what was worth it, and what you never want repeated. Structured feedback improves future recommendations; private notes stay private.</p></div><div style="display:flex;gap:8px;flex-wrap:wrap"><a class="button secondary small" href="<?=e(app_url('travel-mode.php?id='.$tripId))?>">Travel Mode archive</a><?php if($resolution):?><a class="button secondary small" href="<?=e(app_url('trip-resolution.php?id='.$tripId))?>">Resolution outcome</a><?php endif;?></div></header>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(!$snapshot['ready']):?><div class="alert error"><strong>Post-Trip Memory needs migration 044 / app v1.36.</strong> <?php if(is_admin()):?><a href="<?=e(app_url('upgrade.php'))?>">Run System Upgrade</a><?php endif;?></div><?php endif;?>
<?php if(!$snapshot['eligible']):?><div class="alert"><strong>This trip is still active.</strong> Trip Memory opens when the trip is completed or its end date has passed.</div><?php endif;?>
<section class="memory-stats"><article><span>Planned budget</span><strong><?=e(($trip['currency']??'USD').' '.number_format((float)($stats['planned_budget']??0),2))?></strong></article><article><span>Confirmed bookings</span><strong><?=(int)($stats['confirmed_bookings']??0)?></strong></article><article><span>Planned moments</span><strong><?=(int)($stats['planned_items']??0)?></strong></article><article><span>Trip rating</span><strong><?=($memory['overall_rating']??null)!==null?(int)$memory['overall_rating'].'/5':'Not rated'?></strong></article></section>
<?php if(!empty($resolution['by_currency'])):?><section class="memory-card"><div class="memory-section-head"><div><span class="eyebrow">Disruption resolution outcome</span><h2>What the recovery actually cost.</h2></div><a class="button secondary small" href="<?=e(app_url('trip-resolution.php?id='.$tripId))?>">Open Resolution Center</a></div><p>Trip Memory keeps this structured resolution outcome beside your recap. It is factual trip history, not an automatic preference signal. Cash recovery and provider credits remain separate.</p><div class="learned-grid"><?php foreach($resolution['by_currency'] as $currency=>$r):?><article><span><?=e((string)$currency)?> disruption outcome</span><strong>Net cash impact <?=e(($currency==='USD'?'$':$currency.' ').number_format((float)($r['net_cash_impact']??0),2))?></strong><small>Costs <?=e(($currency==='USD'?'$':$currency.' ').number_format((float)($r['costs']??0),2))?> · cash recovered <?=e(($currency==='USD'?'$':$currency.' ').number_format((float)($r['cash_received']??0),2))?> · credits received <?=e(($currency==='USD'?'$':$currency.' ').number_format((float)($r['credits_received']??0),2))?><?php if(($r['cash_outstanding']??0)>0):?> · cash still expected <?=e(($currency==='USD'?'$':$currency.' ').number_format((float)$r['cash_outstanding'],2))?><?php endif;?></small></article><?php endforeach;?></div></section><?php endif;?>
<form method="post" class="memory-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>">
<section class="memory-card"><div class="memory-section-head"><div><span class="eyebrow">The recap</span><h2>How did the trip actually go?</h2></div></div><div class="memory-field-grid">
<label>Overall trip rating<select name="overall_rating"><option value="">Choose 1–5</option><?php for($i=5;$i>=1;$i--):?><option value="<?=$i?>" <?=(int)($memory['overall_rating']??0)===$i?'selected':''?>><?=$i?> / 5</option><?php endfor;?></select></label>
<label>Value rating<select name="value_rating"><option value="">Not rated</option><?php for($i=5;$i>=1;$i--):?><option value="<?=$i?>" <?=(int)($memory['value_rating']??0)===$i?'selected':''?>><?=$i?> / 5</option><?php endfor;?></select></label>
<label>Trip pace<select name="pace_fit"><option value="">Not rated</option><?php foreach(['too_slow'=>'Too slow','just_right'=>'Just right','too_packed'=>'Too packed'] as $v=>$l):?><option value="<?=$v?>" <?=($memory['pace_fit']??'')===$v?'selected':''?>><?=e($l)?></option><?php endforeach;?></select></label>
<label>Would you return?<select name="would_return"><option value="">Not sure yet</option><?php foreach(['yes'=>'Yes','maybe'=>'Maybe','no'=>'No'] as $v=>$l):?><option value="<?=$v?>" <?=($memory['would_return']??'')===$v?'selected':''?>><?=e($l)?></option><?php endforeach;?></select></label>
<label>Actual spend<input name="actual_spend" inputmode="decimal" value="<?=e($memory['actual_spend']!==null?(string)$memory['actual_spend']:'')?>" placeholder="0.00"></label><label>Currency<input name="currency" maxlength="3" value="<?=e((string)($memory['currency']??$trip['currency']??'USD'))?>"></label>
</div><label>Favorite moment<input name="favorite_moment" maxlength="700" value="<?=e((string)($memory['favorite_moment']??''))?>"></label><label>What worked<textarea name="summary_text" rows="4" maxlength="1400"><?=e((string)($memory['summary_text']??''))?></textarea></label><label>What missed<textarea name="biggest_miss" rows="3" maxlength="700"><?=e((string)($memory['biggest_miss']??''))?></textarea></label><label>Private notes<textarea name="private_notes" rows="4" maxlength="8000"><?=e((string)($memory['private_notes']??''))?></textarea><small>Private notes are excluded from recommendation and agent context.</small></label></section>
<section class="memory-card"><div class="memory-section-head"><div><span class="eyebrow">Preference learning</span><h2>Teach Vacation Brain what this trip proved.</h2></div></div><input type="hidden" name="learning_enabled" value="0"><label class="learning-toggle"><input type="checkbox" name="learning_enabled" value="1" <?=!empty($memory['learning_enabled'])?'checked':''?>><span>Use this trip to improve future recommendations</span></label><div class="signal-grid"><?php foreach($snapshot['signal_catalog'] as $key=>$label):$value=(int)($signals[$key]??0);?><label><span><?=e($label)?></span><select name="signal_<?=e($key)?>"><option value="-2" <?=$value===-2?'selected':''?>>Avoid</option><option value="-1" <?=$value===-1?'selected':''?>>Less</option><option value="0" <?=$value===0?'selected':''?>>Neutral</option><option value="1" <?=$value===1?'selected':''?>>More</option><option value="2" <?=$value===2?'selected':''?>>Love it</option></select></label><?php endforeach;?></div></section>
<section class="memory-card"><div class="memory-section-head"><div><span class="eyebrow">Actual vs. planned</span><h2>Rate the parts of the trip.</h2></div></div><div class="memory-item-list"><?php foreach($snapshot['items'] as $item):$fb=$item['feedback']??[];$sent=(string)($fb['sentiment']??'neutral');?><article class="memory-item-row"><div><strong><?=e((string)$item['title'])?></strong><small><?=e(ucwords(str_replace('_',' ',(string)$item['item_type'])))?></small></div><select name="item_sentiment[<?=e((string)$item['source_key'])?>]"><?php foreach(['favorite'=>'Favorite','good'=>'Good','neutral'=>'Neutral','skip'=>'Skip next time'] as $v=>$l):?><option value="<?=$v?>" <?=$sent===$v?'selected':''?>><?=e($l)?></option><?php endforeach;?></select><select name="item_rating[<?=e((string)$item['source_key'])?>]"><option value="">—</option><?php for($i=5;$i>=1;$i--):?><option value="<?=$i?>" <?=(int)($fb['rating']??0)===$i?'selected':''?>><?=$i?> / 5</option><?php endfor;?></select><input name="item_note[<?=e((string)$item['source_key'])?>]" maxlength="500" value="<?=e((string)($fb['note']??''))?>" placeholder="Optional note"></article><?php endforeach;?></div></section>
<section class="memory-card learned-card"><div class="memory-section-head"><div><span class="eyebrow">What the brain has learned</span><h2>Your post-trip signal history.</h2></div><strong><?=(int)($learning['completed_trips']??0)?> completed</strong></div><div class="learned-grid"><article><span>Average rating</span><strong><?=($learning['average_rating']??null)!==null?e((string)$learning['average_rating']).'/5':'Not enough data'?></strong></article><article><span>More of this</span><div class="memory-chips"><?php foreach($learning['positive']??[] as $s):?><span><?=e((string)$s['label'])?></span><?php endforeach;?></div></article><article><span>Less of this</span><div class="memory-chips caution"><?php foreach($learning['negative']??[] as $s):?><span><?=e((string)$s['label'])?></span><?php endforeach;?></div></article></div></section>
<div class="memory-submit-bar"><button class="button secondary" type="submit" name="action" value="save_draft" <?=!$snapshot['ready']||!$snapshot['eligible']?'disabled':''?>>Save draft</button><button class="button primary" type="submit" name="action" value="complete_memory" <?=!$snapshot['ready']||!$snapshot['eligible']?'disabled':''?>>Complete Trip Memory</button></div>
</form></div></section><?php require __DIR__.'/partials/footer.php'; ?>
