<?php
require __DIR__.'/app/bootstrap.php';

$userId=require_auth();$tripId=(int)($_GET['id']??$_POST['trip_id']??0);if($tripId<1){http_response_code(400);exit('Trip is required.');}
$service=new TripCostIntelligenceService(db());$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        if(!$service->ready())throw new RuntimeException('Run System Upgrade for Trip Cost Intelligence + True Trip Economics.');
        $action=(string)($_POST['action']??'');
        if($action==='save_plan'){$service->saveCategoryPlan($userId,$tripId,$_POST);flash('success','Category budget updated.');}
        elseif($action==='add_expense'){$service->addExpense($userId,$tripId,$_POST);flash('success','Actual expense added to the owner ledger.');}
        elseif($action==='void_expense'){$service->voidExpense($userId,$tripId,(int)($_POST['entry_id']??0),(string)($_POST['void_reason']??''));flash('success','Expense correction recorded. The original ledger row remains auditable.');}
        else throw new InvalidArgumentException('Unknown cost action.');
        redirect('trip-cost.php?id='.$tripId);
    }catch(InvalidArgumentException|DomainException|OutOfBoundsException $e){$error=$e->getMessage();}
    catch(Throwable $e){error_log('Trip Cost Intelligence update failed: '.$e->getMessage());$error='Vacation Brain could not update trip costs safely. '.$e->getMessage();}
}
try{$snapshot=$service->snapshot($userId,$tripId);}catch(OutOfBoundsException $e){http_response_code(404);exit('Trip not found.');}
$trip=$snapshot['trip'];$success=flash('success');$title='True Trip Economics — '.$trip['name'];$pageStyles=['assets/trip-cost-intelligence.css'];
function vb_cost_label(string $v):string{return ucwords(str_replace('_',' ',$v));}
function vb_cost_money(mixed $v,string $c):string{return $v===null||$v===''?'—':($c==='USD'?'$':$c.' ').number_format((float)$v,2);}
function vb_cost_dt(mixed $v):string{$s=trim((string)$v);if($s==='')return ''; $t=strtotime($s);return $t?date('M j, Y g:i A',$t):$s;}
$tripCurrency=(string)($trip['currency']??'USD');$owner=!empty($snapshot['can_manage']);$econ=$snapshot['economics']['by_currency'][$tripCurrency]??null;$bookingTrip=(float)($snapshot['shared']['bookings']['by_currency'][$tripCurrency]??0);$model=$snapshot['history_model']['currencies'][$tripCurrency]??null;
require __DIR__.'/partials/header.php';
?>
<section class="vb-cost-page"><div class="shell vb-cost-shell">
<header class="vb-cost-head"><div><a class="back-link" href="<?=e(app_url('dream-trip.php?id='.$tripId.'&workspace=costs'))?>">← Trip workspace</a><span class="eyebrow">Trip Cost Intelligence · True Trip Economics</span><h1>What the trip really costs — before, during and after disruption.</h1><p>Vacation Brain separates planned budget, booked spend, actual expenses, disruption costs, recovered cash and provider credits so one number does not hide what actually happened.</p></div><div class="vb-cost-head-actions"><a class="button secondary" href="<?=e(app_url('trip-bookings.php?id='.$tripId))?>">Bookings</a><a class="button secondary" href="<?=e(app_url('trip-resolution.php?id='.$tripId))?>">Resolution</a><a class="button secondary" href="<?=e(app_url('trip-memory.php?id='.$tripId))?>">Trip Memory</a></div></header>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(!$snapshot['ready']):?><div class="alert error"><strong>Trip Cost Intelligence needs migration 059 / app v1.51.</strong> <?php if(is_admin()):?><a href="<?=e(app_url('upgrade.php'))?>">Run System Upgrade</a><?php endif;?></div><?php endif;?>
<div class="vb-cost-notice"><strong>No hidden exchange rate.</strong> Every currency is kept separate. Provider credits are shown separately from cash recovered and do not reduce net cash cost. Cost Intelligence never charges, refunds, books, cancels or performs a provider transaction.</div>
<section class="vb-cost-summary">
<article><span>Target budget</span><strong><?=!empty($snapshot['can_view_shared_budget'])?e(vb_cost_money($snapshot['shared']['target_budget']??null,$tripCurrency)):'Private'?></strong><small><?=!empty($snapshot['can_view_shared_budget'])?'Shared trip budget':'Not visible to this role'?></small></article>
<article><span>Saved booked spend</span><strong><?=e(vb_cost_money($bookingTrip,$tripCurrency))?></strong><small>Booked / confirmed / changed records only</small></article>
<article><span>Net cash cost</span><strong><?=$owner&&$econ?e(vb_cost_money($econ['net_cash_cost'],$tripCurrency)):'Owner only'?></strong><small><?=$owner&&$econ?'Structured outflow minus received cash recovery':'Private economics ledger'?></small></article>
<article><span>Reported actual</span><strong><?=$owner&&$econ&&$econ['reported_actual']!==null?e(vb_cost_money($econ['reported_actual'],$tripCurrency)):'—'?></strong><small><?=$owner?'Trip Memory traveler-reported total':'Owner only'?></small></article>
</section>
<?php if(!$owner):?>
<section class="vb-cost-card vb-cost-shared-only"><span class="vb-cost-kicker">Shared cost view</span><h2><?=e(vb_cost_label((string)$snapshot['role']))?> access</h2><p>You can see the canonical booking totals allowed by your trip role<?php if($snapshot['can_view_shared_budget']):?> and the shared trip/category budget<?php endif;?>. Manual expenses, Trip Memory actual spend, disruption reimbursements, credits and learned cost history remain owner-only.</p>
<?php if($snapshot['can_view_shared_budget']&&!empty($snapshot['shared']['plans'])):?><div class="vb-cost-table-wrap"><table class="vb-cost-table"><thead><tr><th>Category</th><th>Currency</th><th>Planned</th></tr></thead><tbody><?php foreach($snapshot['shared']['plans'] as $plan):?><tr><td><?=e($snapshot['categories'][$plan['cost_category']]??vb_cost_label((string)$plan['cost_category']))?></td><td><?=e((string)$plan['currency'])?></td><td><?=e(vb_cost_money($plan['amount'],(string)$plan['currency']))?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php else:?>
<div class="vb-cost-grid"><main class="vb-cost-shell">
<section class="vb-cost-card"><span class="vb-cost-kicker">True economics</span><h2>Trip ledger by currency</h2><p>The comparison basis uses Trip Memory actual spend when you entered it; otherwise Vacation Brain uses structured net cash cost.</p><div class="vb-cost-currency">
<?php foreach((array)($snapshot['economics']['by_currency']??[]) as $currency=>$row):$variance=$row['budget_variance']??null;?>
<article class="vb-cost-currency-card"><div class="vb-cost-currency-head"><div><span class="vb-cost-kicker"><?=e($currency)?></span><strong><?=e(vb_cost_money($row['comparison_basis'],$currency))?></strong></div><small><?=e(vb_cost_label((string)$row['comparison_basis_source']))?></small></div><div class="vb-cost-metrics">
<div><span>Structured gross</span><b><?=e(vb_cost_money($row['structured_gross_cash_outflow'],$currency))?></b></div><div><span>Cash recovered</span><b><?=e(vb_cost_money($row['cash_recovered'],$currency))?></b></div><div><span>Provider credits</span><b><?=e(vb_cost_money($row['credits_received'],$currency))?></b></div><div><span>Cash still expected</span><b><?=e(vb_cost_money($row['cash_outstanding'],$currency))?></b></div><div><span>Per traveler / day</span><b><?=e(vb_cost_money($row['per_traveler_day'],$currency))?></b></div><div><span>Budget variance</span><b class="<?=($variance??0)>0?'vb-cost-danger':'vb-cost-good'?>"><?=e($variance===null?'—':vb_cost_money($variance,$currency))?></b></div>
</div></article><?php endforeach;?>
</div></section>
<section class="vb-cost-card"><span class="vb-cost-kicker">Category economics</span><h2>Where the money actually went</h2><p>Booking totals, owner-entered actual expenses and disruption costs are combined without counting a linked booking twice. Recoveries and credits stay visible as separate columns.</p>
<?php foreach((array)($snapshot['economics']['categories']??[]) as $currency=>$categories):?><div class="vb-cost-table-wrap"><table class="vb-cost-table"><thead><tr><th><?=e($currency)?> category</th><th>Plan</th><th>Bookings</th><th>Actual extras</th><th>Disruption</th><th>Cash recovered</th><th>Net cash</th><th>Credits</th></tr></thead><tbody><?php foreach($categories as $cat=>$r):?><tr><td><?=e($snapshot['categories'][$cat]??vb_cost_label($cat))?></td><td><?=e(vb_cost_money($r['planned'],$currency))?></td><td><?=e(vb_cost_money($r['booking_cost'],$currency))?></td><td><?=e(vb_cost_money($r['manual_cost'],$currency))?></td><td><?=e(vb_cost_money($r['disruption_cost'],$currency))?></td><td><?=e(vb_cost_money($r['cash_recovered'],$currency))?></td><td><?=e(vb_cost_money($r['net_cash_cost'],$currency))?></td><td><?=e(vb_cost_money($r['credits_received'],$currency))?></td></tr><?php endforeach;?></tbody></table></div><?php endforeach;?>
</section>
<section class="vb-cost-card"><span class="vb-cost-kicker">Actual expense ledger</span><h2>Capture costs that bookings do not explain.</h2><p>Use this for meals, local transport, shopping, fees and other real expenses that are not already represented by a canonical booking. Corrections are voided, never silently deleted.</p>
<form method="post" class="vb-cost-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="add_expense"><div class="vb-cost-form-grid"><label>Category<select name="cost_category"><?php foreach($snapshot['categories'] as $key=>$label):?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach;?></select></label><label>Amount<input required name="amount" inputmode="decimal" placeholder="0.00"></label><label>Currency<input required name="currency" maxlength="3" value="<?=e($tripCurrency)?>"></label><label>Date / time<input type="datetime-local" name="occurred_at"></label><label>Merchant / provider<input name="merchant_name" maxlength="180" placeholder="Optional — owner only"></label><label>Private ledger note<input name="note" maxlength="1200" placeholder="Optional — excluded from agent context"></label></div><button class="button primary" type="submit">Add actual expense</button></form>
<div class="vb-cost-ledger"><?php if(!$snapshot['manual_entries']):?><p>No owner-entered actual expenses yet.</p><?php endif;?><?php foreach($snapshot['manual_entries'] as $entry):?><article class="vb-cost-entry <?=!empty($entry['voided_at'])?'is-void':''?>"><div class="vb-cost-entry-head"><div><strong><?=e($snapshot['categories'][$entry['cost_category']]??vb_cost_label((string)$entry['cost_category']))?> · <?=e(vb_cost_money($entry['amount'],(string)$entry['currency']))?></strong><small><?=e((string)($entry['merchant_name']?:'Unspecified merchant'))?><?php if($entry['occurred_at']):?> · <?=e(vb_cost_dt($entry['occurred_at']))?><?php endif;?></small></div><span><?=!empty($entry['voided_at'])?'Voided':'Active'?></span></div><?php if($entry['note']):?><small><?=e((string)$entry['note'])?></small><?php endif;?><?php if(!empty($entry['voided_at'])):?><small>Correction: <?=e((string)$entry['void_reason'])?></small><?php else:?><form method="post" class="vb-cost-void"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="void_expense"><input type="hidden" name="entry_id" value="<?=(int)$entry['id']?>"><input required name="void_reason" maxlength="500" placeholder="Reason for correction"><button class="button secondary small" type="submit">Void entry</button></form><?php endif;?></article><?php endforeach;?></div>
</section></main>
<aside class="vb-cost-shell"><section class="vb-cost-card"><span class="vb-cost-kicker">Category budget</span><h2>Plan the budget before the receipts happen.</h2><p>Set or replace one category amount at a time. Enter 0 to clear that category/currency plan.</p><form method="post" class="vb-cost-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="save_plan"><label>Category<select name="cost_category"><?php foreach($snapshot['categories'] as $key=>$label):?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach;?></select></label><label>Planned amount<input required name="amount" inputmode="decimal" placeholder="0.00"></label><label>Currency<input required name="currency" maxlength="3" value="<?=e($tripCurrency)?>"></label><button class="button primary" type="submit">Save category budget</button></form><?php if(!empty($snapshot['shared']['plans'])):?><div class="vb-cost-ledger"><?php foreach($snapshot['shared']['plans'] as $plan):?><article class="vb-cost-entry"><strong><?=e($snapshot['categories'][$plan['cost_category']]??vb_cost_label((string)$plan['cost_category']))?></strong><small><?=e(vb_cost_money($plan['amount'],(string)$plan['currency']))?></small></article><?php endforeach;?></div><?php endif;?></section>
<section class="vb-cost-card"><span class="vb-cost-kicker">Learned trip-cost model</span><h2>Your completed trips are becoming a cost baseline.</h2><?php if(!$model):?><p>Complete Trip Memory with actual spend and learning enabled to start building a currency-specific cost model.</p><?php else:?><div class="vb-cost-model"><article><span>Samples</span><strong><?=(int)$model['samples']?> completed trips</strong></article><article><span>Average trip cost</span><strong><?=e(vb_cost_money($model['average_trip_cost'],$tripCurrency))?></strong></article><article><span>Average / traveler / day</span><strong><?=e(vb_cost_money($model['average_per_traveler_day'],$tripCurrency))?></strong></article><article><span>Average budget variance</span><strong><?=($model['average_budget_variance_pct']??null)===null?'—':e((string)$model['average_budget_variance_pct']).'%'?></strong></article><article><span>Disruption overhead</span><strong><?=e((string)$model['disruption_overhead_pct'])?>%</strong></article><article><span>Cash recovery rate</span><strong><?=e((string)$model['cash_recovery_rate_pct'])?>%</strong></article></div><div class="vb-cost-chips"><?php foreach($model['top_categories']??[] as $cat):?><span><?=e((string)$cat['label'])?> · <?=e((string)$cat['share_pct'])?>%</span><?php endforeach;?></div><?php endif;?><?php if(!empty($snapshot['economics']['forecast'])):$f=$snapshot['economics']['forecast'];?><div class="vb-cost-notice"><strong>Historical estimate:</strong> <?=e(vb_cost_money($f['estimated_trip_cost'],$f['currency']))?> for this trip shape, based on <?=(int)$f['samples']?> prior sample<?=((int)$f['samples']===1?'':'s')?>. This is not a quote.</div><?php endif;?></section>
<section class="vb-cost-card"><span class="vb-cost-kicker">Accounting boundaries</span><p class="vb-cost-private">Trip Memory actual spend is traveler-reported. Bookings are canonical saved records. Disruption Resolution tracks user-recorded refunds, insurance reimbursement and credits. Cost Intelligence reconciles those facts but does not verify bank settlement or provider payment rails.</p></section></aside></div>
<?php endif;?>
</div></section><?php require __DIR__.'/partials/footer.php'; ?>
