<?php
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/Services/TripSpendExecutionService.php';

$userId=require_auth();$tripId=(int)($_GET['id']??$_POST['trip_id']??0);if($tripId<1){http_response_code(400);exit('Trip is required.');}
$service=new TripSpendExecutionService(db());$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        if(!$service->ready())throw new RuntimeException('Run System Upgrade through migration 061 for Live Trip Spend + Budget Execution.');
        $action=(string)($_POST['action']??'');
        if($action==='capture_expense'){$service->captureExpense($userId,$tripId,$_POST);flash('success','Actual spend captured in the private trip ledger.');}
        elseif($action==='save_settings'){$service->saveSettings($userId,$tripId,$_POST);flash('success','Live-spend pacing settings updated.');}
        elseif($action==='update_meta'){$service->updateEntryMeta($userId,$tripId,(int)($_POST['entry_id']??0),$_POST);flash('success','Receipt, reconciliation and attribution details updated.');}
        elseif($action==='void_expense'){$service->voidExpense($userId,$tripId,(int)($_POST['entry_id']??0),(string)($_POST['void_reason']??''));flash('success','Expense correction recorded without deleting the audit trail.');}
        else throw new InvalidArgumentException('Unknown live-spend action.');
        redirect('trip-spend.php?id='.$tripId);
    }catch(InvalidArgumentException|DomainException|OutOfBoundsException $e){$error=$e->getMessage();}
    catch(Throwable $e){error_log('Live Trip Spend update failed: '.$e->getMessage());$error='Vacation Brain could not update live trip spend safely. Check the server log or try again.';}
}
try{$snapshot=$service->snapshot($userId,$tripId);}catch(OutOfBoundsException $e){http_response_code(404);exit('Trip not found.');}
$trip=$snapshot['trip'];$owner=!empty($snapshot['can_manage']);$execution=$snapshot['execution']??[];$settings=$snapshot['settings']??[];$success=flash('success');$title='Live Trip Spend — '.$trip['name'];$pageStyles=['assets/trip-spend.css'];
function vb_spend_money(mixed $v,string $c):string{return $v===null||$v===''?'—':($c==='USD'?'$':$c.' ').number_format((float)$v,2);}
function vb_spend_label(string $v):string{return ucwords(str_replace('_',' ',$v));}
$currency=(string)($execution['currency']??$trip['currency']??'USD');
require __DIR__.'/partials/header.php';
?>
<section class="vb-spend-page"><div class="shell vb-spend-shell">
<header class="vb-spend-head"><div><a class="back-link" href="<?=e(app_url('dream-trip.php?id='.$tripId.'&workspace=spend'))?>">← Trip workspace</a><span class="eyebrow">Live Trip Spend · Budget Execution</span><h1>Stay on budget while the trip is actually happening.</h1><p>Track owner-entered actual spend, reconcile receipts and bookings, watch daily pace, and get non-destructive ways to recover before a small overage becomes the trip budget.</p></div><div class="vb-spend-actions"><a class="button secondary" href="<?=e(app_url('trip-cost.php?id='.$tripId))?>">True Trip Economics</a><a class="button secondary" href="<?=e(app_url('trip-affordability.php?id='.$tripId))?>">Affordability</a><?php if(($trip['operational_state']??'')==='traveling'):?><a class="button primary" href="<?=e(app_url('travel-mode.php?id='.$tripId))?>">Travel Mode</a><?php endif;?></div></header>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(!$snapshot['ready']):?><div class="alert error"><strong>Live Trip Spend needs migration 061 / app v1.53.</strong> <?php if(is_admin()):?><a href="<?=e(app_url('upgrade.php'))?>">Run System Upgrade</a><?php endif;?></div><?php endif;?>
<div class="vb-spend-boundary"><strong>Private owner ledger.</strong> Recorded actual spend is not a bank feed or proof of settlement. Vacation Brain does not store card credentials, move money, guess exchange rates, or automatically change a reservation. Receipt references are private labels only.</div>
<?php if(!$owner):?>
<section class="vb-spend-card"><span class="eyebrow">Shared trip privacy</span><h2>Expense details stay with the trip owner.</h2><p>Shared attribution can identify that private expense records were associated with trip participants, but collaborators do not receive amounts, merchants, notes, receipts, reconciliation status, or owner budget pacing.</p><?php if(!empty($snapshot['attribution'])):?><div class="vb-spend-shared-counts"><?php foreach($snapshot['attribution'] as $r):?><article><strong><?=(int)$r['entry_count']?> shared-attributed record<?=((int)$r['entry_count']===1?'':'s')?></strong><small>Traveler #<?=(int)$r['user_id']?> · financial detail private</small></article><?php endforeach;?></div><?php endif;?></section>
<?php else:?>
<section class="vb-spend-scoreboard">
<article><span>Recorded actual</span><strong><?=e(vb_spend_money($execution['actual_spend']??0,$currency))?></strong><small>Owner-entered, non-void ledger</small></article>
<article><span>Target budget</span><strong><?=e(vb_spend_money($execution['target_budget']??null,$currency))?></strong><small><?=($execution['spend_pct']??null)!==null?e(number_format((float)$execution['spend_pct'],1)).'% used':'Set a target budget to activate pacing'?></small></article>
<article class="pace-<?=e((string)($execution['pace_status']??'unknown'))?>"><span>Budget pace</span><strong><?=e(vb_spend_label((string)($execution['pace_status']??'unknown')))?></strong><small><?=($execution['remaining_budget']??null)!==null?e(vb_spend_money($execution['remaining_budget'],$currency)).' remaining':'Target required'?></small></article>
<article><span>Daily allowance left</span><strong><?=e(vb_spend_money($execution['remaining_daily_allowance']??null,$currency))?></strong><small><?=(int)($execution['days_remaining']??0)?> trip day<?=((int)($execution['days_remaining']??0)===1?'':'s')?> remaining</small></article>
<article><span>Planning expected final</span><strong><?=e(vb_spend_money($execution['planning_expected_final']??null,$currency))?></strong><small>Forecast, not settled spend</small></article>
<article><span>Needs reconciliation</span><strong><?=(int)($execution['unreconciled_count']??0)?></strong><small><?=(int)($execution['receipt_count']??0)?> receipt reference<?=((int)($execution['receipt_count']??0)===1?'':'s')?> captured</small></article>
</section>
<div class="vb-spend-grid"><main>
<section class="vb-spend-card"><span class="eyebrow">Quick capture</span><h2>Record what you actually spent.</h2><p>Use this for real trip expenses. Link a canonical booking only when the expense refers to that saved booking; Trip Cost Intelligence will avoid counting the linked booking twice.</p>
<form method="post" class="vb-spend-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="capture_expense"><div class="vb-spend-form-grid">
<label>Category<select name="cost_category"><?php foreach($snapshot['categories'] as $key=>$label):?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach;?></select></label><label>Amount<input required name="amount" inputmode="decimal" placeholder="0.00"></label><label>Currency<input readonly name="currency" maxlength="3" value="<?=e($currency)?>"></label><label>Date / time<input type="datetime-local" name="occurred_at"></label><label>Merchant / provider<input name="merchant_name" maxlength="180" placeholder="Owner only"></label><label>Private note<input name="note" maxlength="1200" placeholder="Excluded from agent context"></label>
<label>Related booking<select name="source_booking_id"><option value="0">Not linked</option><?php foreach($snapshot['bookings'] as $b):?><option value="<?=(int)$b['id']?>"><?=e((string)$b['title'])?><?=($b['amount']??null)!==null?' · '.e(vb_spend_money($b['amount'],(string)($b['currency']?:$currency))):''?></option><?php endforeach;?></select></label><label>Reconciliation<select name="reconciliation_status"><option value="unreconciled">Unreconciled</option><option value="booking_linked">Booking linked</option><option value="owner_confirmed">Owner confirmed</option><option value="cash_confirmed">Cash confirmed</option><option value="other_confirmed">Other confirmed</option></select></label><label>Receipt status<select name="receipt_status"><option value="none">No receipt reference</option><option value="captured">Receipt captured</option><option value="missing">Receipt missing</option></select></label><label>Receipt reference<input name="receipt_reference" maxlength="255" placeholder="Private filename / URL / note"></label><label>Trip attribution<select name="shared_scope"><option value="private">Private / no shared attribution</option><option value="trip_shared">Attribute within shared trip</option></select></label><label>Attributed traveler<select name="attributed_user_id"><option value="0">None</option><?php foreach($snapshot['attribution'] as $person):?><option value="<?=(int)$person['user_id']?>"><?=e((string)$person['display_name'])?> · <?=e(vb_spend_label((string)$person['role']))?></option><?php endforeach;?></select></label>
</div><button class="button primary" type="submit">Capture actual spend</button></form></section>
<section class="vb-spend-card"><span class="eyebrow">Actual vs category plan</span><h2>Where the live budget is moving.</h2><div class="vb-spend-table-wrap"><table class="vb-spend-table"><thead><tr><th>Category</th><th>Planned</th><th>Actual</th><th>Remaining</th><th>Status</th></tr></thead><tbody><?php foreach((array)($execution['categories']??[]) as $key=>$r):?><tr class="<?=$r['over']?'is-over':''?>"><td><?=e((string)$r['label'])?></td><td><?=e(vb_spend_money($r['planned'],$currency))?></td><td><?=e(vb_spend_money($r['actual'],$currency))?></td><td><?=e(vb_spend_money($r['remaining'],$currency))?></td><td><?=$r['over']?'Over plan':'Tracking'?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="vb-spend-card"><span class="eyebrow">Private spend ledger</span><h2>Receipts, reconciliation and corrections.</h2><div class="vb-spend-ledger"><?php if(empty($snapshot['entries'])):?><p>No actual expenses recorded yet.</p><?php endif;?><?php foreach($snapshot['entries'] as $entry):?><article class="vb-spend-entry <?=!empty($entry['voided_at'])?'is-void':''?>"><div class="vb-spend-entry-head"><div><strong><?=e($snapshot['categories'][$entry['cost_category']]??vb_spend_label((string)$entry['cost_category']))?> · <?=e(vb_spend_money($entry['amount'],(string)$entry['currency']))?></strong><small><?=e((string)($entry['merchant_name']?:'Merchant not recorded'))?><?php if($entry['occurred_at']):?> · <?=e(date('M j, Y g:i A',strtotime((string)$entry['occurred_at'])))?><?php endif;?></small></div><span><?=!empty($entry['voided_at'])?'Voided':e(vb_spend_label((string)$entry['reconciliation_status']))?></span></div><?php if($entry['note']):?><p><?=e((string)$entry['note'])?></p><?php endif;?><?php if($entry['receipt_reference']):?><small>Receipt reference: <?=e((string)$entry['receipt_reference'])?></small><?php endif;?>
<?php if(empty($entry['voided_at'])):?><details><summary>Edit execution details</summary><form method="post" class="vb-spend-inline-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="update_meta"><input type="hidden" name="entry_id" value="<?=(int)$entry['id']?>"><label>Receipt<select name="receipt_status"><?php foreach(['none'=>'None','captured'=>'Captured','missing'=>'Missing'] as $v=>$l):?><option value="<?=$v?>" <?=$entry['receipt_status']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>Receipt reference<input name="receipt_reference" maxlength="255" value="<?=e((string)$entry['receipt_reference'])?>"></label><label>Reconciliation<select name="reconciliation_status"><?php foreach(['unreconciled'=>'Unreconciled','booking_linked'=>'Booking linked','owner_confirmed'=>'Owner confirmed','cash_confirmed'=>'Cash confirmed','other_confirmed'=>'Other confirmed'] as $v=>$l):?><option value="<?=$v?>" <?=$entry['reconciliation_status']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>Sharing<select name="shared_scope"><option value="private" <?=$entry['shared_scope']==='private'?'selected':''?>>Private</option><option value="trip_shared" <?=$entry['shared_scope']==='trip_shared'?'selected':''?>>Trip attribution</option></select></label><label>Traveler<select name="attributed_user_id"><option value="0">None</option><?php foreach($snapshot['attribution'] as $person):?><option value="<?=(int)$person['user_id']?>" <?=(int)$entry['attributed_user_id']===(int)$person['user_id']?'selected':''?>><?=e((string)$person['display_name'])?></option><?php endforeach;?></select></label><button class="button secondary small" type="submit">Save details</button></form></details><form method="post" class="vb-spend-void"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="void_expense"><input type="hidden" name="entry_id" value="<?=(int)$entry['id']?>"><input required name="void_reason" maxlength="500" placeholder="Reason for correction"><button class="button secondary small" type="submit">Void entry</button></form><?php else:?><small>Correction: <?=e((string)$entry['void_reason'])?></small><?php endif;?></article><?php endforeach;?></div></section>
</main><aside>
<section class="vb-spend-card"><span class="eyebrow">Pacing policy</span><h2>When should Vacation Brain warn you?</h2><form method="post" class="vb-spend-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="trip_id" value="<?=$tripId?>"><input type="hidden" name="action" value="save_settings"><input type="hidden" name="currency" value="<?=e($currency)?>"><label>Budget-used alert %<input required type="number" step="0.1" min="25" max="100" name="alert_spend_pct" value="<?=e((string)($settings['alert_spend_pct']??85))?>"></label><label>Daily allowance override<input type="number" step="0.01" min="0" name="daily_allowance_override" value="<?=e((string)($settings['daily_allowance_override']??''))?>" placeholder="Automatic if blank"></label><button class="button primary" type="submit">Save pacing policy</button></form></section>
<section class="vb-spend-card"><span class="eyebrow">Budget recovery</span><h2>Non-destructive ways to get back on pace.</h2><?php if(empty($snapshot['suggestions'])):?><p>No budget recovery action is indicated by the recorded ledger right now.</p><?php else:?><div class="vb-spend-suggestions"><?php foreach($snapshot['suggestions'] as $s):?><article><strong><?=e((string)$s['title'])?></strong><p><?=e((string)$s['body'])?></p><?php if((float)$s['estimated_savings']>0):?><small>Potential reduction: <?=e(vb_spend_money($s['estimated_savings'],$currency))?></small><?php endif;?></article><?php endforeach;?></div><?php endif;?></section>
<section class="vb-spend-card"><span class="eyebrow">Execution semantics</span><p><?=e((string)($execution['semantics']??''))?></p><p><?=e((string)($snapshot['safety_note']??''))?></p></section>
</aside></div>
<?php endif;?>
</div></section>
<?php require __DIR__.'/partials/footer.php'; ?>
