<?php
require __DIR__.'/app/bootstrap.php';
$userId=require_auth();$pdo=db();$galleryService=new VacationPhotoGalleryService($pdo,__DIR__);$error=null;$success=flash('success');
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        $action=(string)($_POST['action']??'');$id=(int)($_POST['generation_id']??0);
        if($action==='favorite'){$on=$galleryService->toggleFavorite($userId,$id);flash('success',$on?'Added to favorites.':'Removed from favorites.');}
        elseif($action==='archive'){$galleryService->setArchived($userId,$id,true);flash('success','Vacation photo archived.');}
        elseif($action==='restore'){$galleryService->setArchived($userId,$id,false);flash('success','Vacation photo restored.');}
        elseif($action==='delete'){$galleryService->delete($userId,$id);flash('success','Vacation photo deleted.');}
        elseif($action==='share'){$token=$galleryService->enableShare($userId,$id);$_SESSION['vacation_share_url']=app_url('vacation-photo-share.php?token='.$token);flash('success','Share link created.');}
        elseif($action==='unshare'){$galleryService->disableShare($userId,$id);flash('success','Public share link disabled.');}
        elseif($action==='dream_cover'){$galleryService->setDreamCover($userId,$id,(int)($_POST['dream_trip_id']??0));flash('success','Dream Trip cover updated.');}
        elseif($action==='regenerate'){$created=$galleryService->regenerate($userId,$id);flash('success','A fresh version was generated.');}
        redirect('vacation-gallery.php'.(!empty($_GET['favorites'])?'?favorites=1':''));
    }catch(Throwable $e){$error=$e instanceof InvalidArgumentException?$e->getMessage():$e->getMessage();}
}
$filters=['favorites'=>!empty($_GET['favorites']),'archived'=>!empty($_GET['archived']),'destination_id'=>(int)($_GET['destination_id']??0)];$items=$galleryService->gallery($userId,$filters);$destinations=$galleryService->destinations($userId);$dreamStmt=$pdo->prepare('SELECT id,name FROM dream_trips WHERE user_id=? AND status<>"abandoned" ORDER BY updated_at DESC,id DESC LIMIT 30');$dreamStmt->execute([$userId]);$dreams=$dreamStmt->fetchAll()?:[];$shareUrl=$_SESSION['vacation_share_url']??null;unset($_SESSION['vacation_share_url']);$success=flash('success')??$success;
$groups=[];foreach($items as $item){$key=(string)((int)($item['destination_catalog_id']??0)).'|'.(string)$item['destination'];$groups[$key]['name']=$item['catalog_destination_name']?:$item['destination'];$groups[$key]['destination_id']=(int)($item['destination_catalog_id']??0);$groups[$key]['items'][]=$item;}
$title='My Fake Vacations';require __DIR__.'/partials/header.php';
?>
<style>
.vg-page{padding:36px 0 90px}.vg-head{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:20px}.vg-head h1{font-size:clamp(34px,5vw,60px);margin:4px 0}.vg-filters{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0 28px}.vg-filters a{padding:8px 12px;border:1px solid #ddd;border-radius:999px;text-decoration:none;color:inherit;background:#fff}.vg-filters a.active{background:#111;color:#fff;border-color:#111}.vg-group{margin:0 0 34px}.vg-group-head{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:12px}.vg-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.vg-card{background:#fff;border:1px solid #e7e7e7;border-radius:20px;overflow:hidden}.vg-card-media{position:relative}.vg-card img{width:100%;aspect-ratio:1/1;object-fit:cover;display:block}.vg-heart{position:absolute;top:10px;right:10px;border:0;border-radius:999px;background:rgba(255,255,255,.9);width:38px;height:38px;cursor:pointer;font-size:18px}.vg-copy{padding:14px}.vg-copy h3{margin:0 0 4px}.vg-meta{font-size:12px;color:#666}.vg-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.vg-actions form{margin:0}.vg-actions button,.vg-actions a{font:inherit;font-size:12px;border:1px solid #ddd;background:#fff;color:#111;border-radius:999px;padding:7px 10px;text-decoration:none;cursor:pointer}.vg-actions .danger{color:#9b2f2f}.vg-dream{display:flex;gap:6px;margin-top:10px}.vg-dream select{min-width:0;flex:1}.vg-share{padding:14px 16px;border-radius:16px;background:#f1f7f4;margin-bottom:18px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}.vg-share code{overflow-wrap:anywhere}.vg-empty{padding:50px 20px;text-align:center;border:1px dashed #ccc;border-radius:20px;background:#fff}.vg-origin{display:inline-block;margin-top:7px;padding:3px 7px;border-radius:999px;background:#f0f0f0;font-size:11px}@media(max-width:900px){.vg-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.vg-head{display:block}.vg-grid{grid-template-columns:1fr}}
</style>
<section class="vg-page"><div class="shell"><div class="vg-head"><div><span class="eyebrow">Vacation Yourself</span><h1>My Fake Vacations</h1><p class="muted">Every imaginary trip Vacation Brain has manufactured on your behalf.</p></div><a class="button primary" href="<?=e(app_url('vacation-yourself.php'))?>">Create another</a></div>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><?php if($shareUrl):?><div class="vg-share"><strong>Share link:</strong><code><?=e($shareUrl)?></code><button class="button secondary small" type="button" data-copy="<?=e($shareUrl)?>">Copy</button></div><?php endif;?>
<div class="vg-filters"><a class="<?=empty($filters['favorites'])&&empty($filters['archived'])&&!$filters['destination_id']?'active':''?>" href="<?=e(app_url('vacation-gallery.php'))?>">All</a><a class="<?=$filters['favorites']?'active':''?>" href="<?=e(app_url('vacation-gallery.php?favorites=1'))?>">Favorites</a><a class="<?=$filters['archived']?'active':''?>" href="<?=e(app_url('vacation-gallery.php?archived=1'))?>">Archived</a><?php foreach(array_slice($destinations,0,8) as $d):?><?php if((int)$d['destination_id']>0):?><a class="<?=$filters['destination_id']===(int)$d['destination_id']?'active':''?>" href="<?=e(app_url('vacation-gallery.php?destination_id='.(int)$d['destination_id']))?>"><?=e($d['destination'])?> <small><?= (int)$d['image_count'] ?></small></a><?php endif;?><?php endforeach;?></div>
<?php if(!$items):?><div class="vg-empty"><h2>No fake vacations in this view.</h2><p class="muted">Reality appears to be winning temporarily.</p><a class="button primary" href="<?=e(app_url('vacation-yourself.php'))?>">Fix that</a></div><?php endif;?>
<?php foreach($groups as $group):?><section class="vg-group"><div class="vg-group-head"><div><span class="eyebrow">Destination</span><h2><?=e($group['name'])?></h2></div><?php if($group['destination_id']):?><a class="button secondary small" href="<?=e(app_url('vacation-yourself.php?destination_id='.$group['destination_id']))?>">Show Me There again</a><?php endif;?></div><div class="vg-grid"><?php foreach($group['items'] as $item):?><article class="vg-card"><div class="vg-card-media"><img src="<?=e($item['image_url'])?>" alt="AI-generated fictional vacation in <?=e($item['destination'])?>"><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="favorite"><input type="hidden" name="generation_id" value="<?=(int)$item['id']?>"><button class="vg-heart" type="submit" title="Favorite"><?=!empty($item['favorite'])?'♥':'♡'?></button></form></div><div class="vg-copy"><h3><?=e($item['scene']?:$item['destination'])?></h3><div class="vg-meta"><?=e(ucfirst((string)$item['vibe']))?> · Over the Top <?=(int)$item['over_the_top_strength']?>/100 · <?=e((string)$item['created_at'])?></div><span class="vg-origin"><?=e(ucwords(str_replace('_',' ',(string)($item['origin']??'manual'))))?></span>
<div class="vg-actions"><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="regenerate"><input type="hidden" name="generation_id" value="<?=(int)$item['id']?>"><button type="submit">Regenerate</button></form><?php if(empty($item['share_enabled'])):?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="share"><input type="hidden" name="generation_id" value="<?=(int)$item['id']?>"><button type="submit">Share</button></form><?php else:?><a href="<?=e(app_url('vacation-photo-share.php?token='.$item['share_token']))?>" target="_blank">Open share</a><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="unshare"><input type="hidden" name="generation_id" value="<?=(int)$item['id']?>"><button type="submit">Unshare</button></form><?php endif;?><?php if(!$filters['archived']):?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="archive"><input type="hidden" name="generation_id" value="<?=(int)$item['id']?>"><button type="submit">Archive</button></form><?php else:?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="restore"><input type="hidden" name="generation_id" value="<?=(int)$item['id']?>"><button type="submit">Restore</button></form><?php endif;?><form method="post" onsubmit="return confirm('Permanently delete this generated image?')"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="generation_id" value="<?=(int)$item['id']?>"><button class="danger" type="submit">Delete</button></form></div>
<?php if($dreams):?><form method="post" class="vg-dream"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="dream_cover"><input type="hidden" name="generation_id" value="<?=(int)$item['id']?>"><select class="input" name="dream_trip_id" required><option value="">Use as Dream Trip cover…</option><?php foreach($dreams as $dream):?><option value="<?=(int)$dream['id']?>" <?=((int)($item['dream_trip_id']??0)===(int)$dream['id'])?'selected':''?>><?=e($dream['name'])?></option><?php endforeach;?></select><button class="button secondary small" type="submit">Set</button></form><?php endif;?></div></article><?php endforeach;?></div></section><?php endforeach;?>
</div></section>
<?php require __DIR__.'/partials/footer.php';?>
