<?php
require __DIR__.'/app/bootstrap.php';
$token=strtolower(trim((string)($_GET['token']??'')));
$style=strtolower(trim((string)($_GET['style']??'diagnosis')));if(!in_array($style,['diagnosis','postcard','clean'],true))$style='diagnosis';
$item=(new VacationPhotoGalleryService(db(),__DIR__))->publicShared($token);
if(!$item){
    http_response_code(404);$title='Vacation photo not found';$metaDescription='This Vacation Brain share is no longer public.';require __DIR__.'/partials/header.php';?>
    <section class="form-page"><div class="shell"><div class="form-card"><h1>This fake vacation is no longer public.</h1><p class="muted">The owner may have disabled the share link or deleted the image.</p><a class="button primary" href="<?=e(app_url('index.php'))?>">Vacation Brain</a></div></div></section>
    <?php require __DIR__.'/partials/footer.php';exit;
}
$baseUrl=app_url('vacation-photo-share.php?token='.urlencode($token));
$canonicalUrl=$baseUrl.'&style='.$style;
$diagnosisHeadline=(string)$item['diagnosis_headline'];$postcardHeadline=(string)$item['postcard_headline'];$postcardSubhead=(string)$item['postcard_subhead'];
$shareText=(string)$item['share_text'];
$title=match($style){'postcard'=>$item['destination'].' postcard — Vacation Brain','clean'=>$item['destination'].' — Vacation Brain',default=>$diagnosisHeadline};
$metaDescription=match($style){'postcard'=>$postcardHeadline.' '.$postcardSubhead,'clean'=>'An AI-generated imaginary Vacation Brain trip to '.$item['destination'].'.',default=>$diagnosisHeadline.' '.$postcardSubhead};
$ogTitle=$title;$ogDescription=$metaDescription;$ogImage=(string)$item['image_url'];
require __DIR__.'/partials/header.php';
?>
<style>
.shared-vacation{padding:42px 0 90px}.share-wrap{max-width:940px;margin:auto}.share-mode-nav{display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-bottom:16px}.share-mode-nav a{padding:8px 12px;border:1px solid #ddd;border-radius:999px;text-decoration:none;color:#222;background:#fff}.share-mode-nav a.active{background:#111;color:#fff;border-color:#111}.shared-vacation-card{background:#fff;border:1px solid #e5e5e5;border-radius:30px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,.08)}.shared-vacation-card img{width:100%;display:block;object-fit:cover}.share-photo{position:relative}.share-photo .share-ai-badge{position:absolute;left:16px;bottom:16px;padding:6px 9px;border-radius:999px;background:rgba(255,255,255,.92);font-size:11px;font-weight:700}.shared-vacation-copy{padding:28px}.shared-vacation-copy h1{font-size:clamp(34px,6vw,68px);line-height:1;margin:6px 0 14px;letter-spacing:-.035em}.shared-vacation-copy .lead{font-size:clamp(18px,2.4vw,25px);line-height:1.35;max-width:760px}.share-facts{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.share-facts span{padding:7px 10px;border-radius:999px;background:#f3f3f3;font-size:12px}.share-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:20px}.share-actions button,.share-actions a{font:inherit;border-radius:999px;padding:10px 14px;text-decoration:none;cursor:pointer}.share-actions button{border:1px solid #ddd;background:#fff}.diagnosis-card{background:linear-gradient(150deg,#fff 0%,#fff8ef 100%)}.diagnosis-card .shared-vacation-copy{padding:32px}.diagnosis-stamp{display:inline-flex;gap:7px;align-items:center;padding:7px 11px;border:1px solid #1a1a1a;border-radius:999px;font-size:11px;font-weight:800;letter-spacing:.08em}.diagnosis-prescription{margin-top:18px;padding:18px;border-left:4px solid #111;background:rgba(255,255,255,.72);font-size:18px}.postcard-card{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(300px,.75fr);background:#faf6ed}.postcard-card .share-photo img{height:100%;min-height:560px}.postcard-card .shared-vacation-copy{display:flex;flex-direction:column;justify-content:center;padding:40px}.postcard-kicker{font-family:Georgia,serif;font-style:italic;font-size:22px}.postcard-card h1{font-family:Georgia,serif}.postcard-rule{border:0;border-top:1px solid #bbb;width:100%;margin:24px 0}.clean-card{max-width:820px;margin:auto;background:#111;color:#fff}.clean-card .shared-vacation-copy{background:#111}.clean-card .share-facts span{background:#272727}.clean-card .muted,.clean-card .microcopy{color:#bbb}.share-foot{padding:18px;text-align:center;color:#666;font-size:12px}.share-owner-note{text-align:center;margin:14px 0;color:#777;font-size:12px}@media(max-width:760px){.postcard-card{grid-template-columns:1fr}.postcard-card .share-photo img{min-height:0}.postcard-card .shared-vacation-copy{padding:26px}.shared-vacation-copy{padding:22px}.diagnosis-card .shared-vacation-copy{padding:24px}}
</style>
<section class="shared-vacation"><div class="shell share-wrap">
<nav class="share-mode-nav" aria-label="Share style"><a class="<?=$style==='diagnosis'?'active':''?>" href="<?=e($baseUrl.'&style=diagnosis')?>">Diagnosis Card</a><a class="<?=$style==='postcard'?'active':''?>" href="<?=e($baseUrl.'&style=postcard')?>">Postcard</a><a class="<?=$style==='clean'?'active':''?>" href="<?=e($baseUrl.'&style=clean')?>">Clean Photo</a></nav>

<?php if($style==='diagnosis'):?>
<article class="shared-vacation-card diagnosis-card"><div class="share-photo"><img src="<?=e($item['image_url'])?>" alt="AI-generated fictional vacation in <?=e($item['destination'])?>"><span class="share-ai-badge">AI-generated fiction</span></div><div class="shared-vacation-copy"><span class="diagnosis-stamp">VACATION BRAIN · DIAGNOSIS</span><h1><?=e($diagnosisHeadline)?></h1><p class="lead"><?=e($postcardSubhead)?></p><?php if(!empty($item['archetype'])):?><div class="diagnosis-prescription"><strong>Additional finding:</strong> Current classification: <?=e($item['archetype'])?>.</div><?php endif;?><div class="share-facts"><span><?=e($item['destination'])?></span><span><?=e(ucfirst((string)$item['vibe']))?></span><span>Over the Top <?=(int)$item['over_the_top_strength']?>/100</span></div><?php if(!empty($item['scene'])):?><p class="muted"><?=e($item['scene'])?></p><?php endif;?>
<?php elseif($style==='postcard'):?>
<article class="shared-vacation-card postcard-card"><div class="share-photo"><img src="<?=e($item['image_url'])?>" alt="AI-generated fictional vacation in <?=e($item['destination'])?>"><span class="share-ai-badge">AI-generated fiction</span></div><div class="shared-vacation-copy"><div class="postcard-kicker">Vacation Brain says:</div><h1><?=e($postcardHeadline)?></h1><p class="lead"><?=e($postcardSubhead)?></p><hr class="postcard-rule"><p><?=e($diagnosisHeadline)?></p><div class="share-facts"><span><?=e($item['destination'])?></span><span>OTT <?=(int)$item['over_the_top_strength']?>/100</span></div>
<?php else:?>
<article class="shared-vacation-card clean-card"><div class="share-photo"><img src="<?=e($item['image_url'])?>" alt="AI-generated fictional vacation in <?=e($item['destination'])?>"><span class="share-ai-badge">AI-generated fiction</span></div><div class="shared-vacation-copy"><span class="eyebrow">Vacation Brain · Imaginary travel evidence</span><h1><?=e($item['destination'])?></h1><?php if(!empty($item['scene'])):?><p class="lead"><?=e($item['scene'])?></p><?php endif;?><div class="share-facts"><span><?=e(ucfirst((string)$item['vibe']))?></span><span>Over the Top <?=(int)$item['over_the_top_strength']?>/100</span></div>
<?php endif;?>
<div class="share-actions"><button type="button" data-native-share data-share-url="<?=e($canonicalUrl)?>" data-share-text="<?=e($shareText)?>">Share</button><button type="button" data-copy="<?=e($canonicalUrl)?>">Copy link</button><a class="button primary" href="<?=e(app_url('diagnosis.php'))?>">Diagnose your Vacation Brain</a></div><p class="microcopy" style="margin-top:16px">Created for entertainment. This AI-generated image does not document a real trip or event.</p></div></article>
<div class="share-owner-note">Public only because the owner explicitly enabled sharing. The share can be revoked from My Fake Vacations.</div>
</div></section>
<script>
document.querySelectorAll('[data-native-share]').forEach(function(button){button.addEventListener('click',async function(){var url=button.getAttribute('data-share-url')||location.href;var text=button.getAttribute('data-share-text')||document.title;try{if(navigator.share){await navigator.share({title:document.title,text:text,url:url});}else if(navigator.clipboard){await navigator.clipboard.writeText(url);button.textContent='Link copied';}}catch(e){}});});
</script>
<?php require __DIR__.'/partials/footer.php';?>
