<?php
require __DIR__.'/app/bootstrap.php';
$token=strtolower(trim((string)($_GET['token']??'')));$item=(new VacationPhotoGalleryService(db(),__DIR__))->publicShared($token);
if(!$item){http_response_code(404);$title='Vacation photo not found';require __DIR__.'/partials/header.php';?><section class="form-page"><div class="shell"><div class="form-card"><h1>This fake vacation is no longer public.</h1><p class="muted">The owner may have disabled the share link or deleted the image.</p><a class="button primary" href="<?=e(app_url('index.php'))?>">Vacation Brain</a></div></div></section><?php require __DIR__.'/partials/footer.php';exit;}
$title=$item['destination'].' — Vacation Brain';require __DIR__.'/partials/header.php';
?>
<style>.shared-vacation{padding:48px 0 80px}.shared-vacation-card{max-width:820px;margin:auto;background:#fff;border:1px solid #e5e5e5;border-radius:28px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,.08)}.shared-vacation-card img{width:100%;display:block}.shared-vacation-copy{padding:24px}.shared-vacation-copy h1{font-size:clamp(32px,5vw,54px);margin:5px 0 10px}.shared-label{display:inline-flex;padding:6px 10px;border-radius:999px;background:#f1f1f1;font-size:12px}</style>
<section class="shared-vacation"><div class="shell"><article class="shared-vacation-card"><img src="<?=e($item['image_url'])?>" alt="AI-generated fictional vacation in <?=e($item['destination'])?>"><div class="shared-vacation-copy"><span class="eyebrow">Vacation Brain · Imaginary travel evidence</span><h1><?=e($item['destination'])?></h1><?php if(!empty($item['scene'])):?><p class="section-lead"><?=e($item['scene'])?></p><?php endif;?><p><?=e(ucfirst((string)$item['vibe']))?> · Over the Top <?=(int)$item['over_the_top_strength']?>/100</p><span class="shared-label">AI-generated fictional vacation image</span><p class="microcopy" style="margin-top:16px">Created for entertainment. This image does not document a real trip or event.</p><a class="button primary" href="<?=e(app_url('index.php'))?>">Diagnose your Vacation Brain</a></div></article></div></section>
<?php require __DIR__.'/partials/footer.php';?>
