<?php
require __DIR__.'/app/bootstrap.php';$userId=require_auth();$pdo=db();$result=null;$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$home=trim((string)($_POST['home']??''));$dream=trim((string)($_POST['dream']??''));$result=(new WeatherEnvyService())->compare($home,$dream);$pdo->prepare('INSERT INTO user_events (user_id,event_type,value_text,metadata_json) VALUES (? ,"weather_envy_checked",?,?)')->execute([$userId,$dream,json_encode(['home'=>$home,'dream'=>$dream],JSON_UNESCAPED_SLASHES)]);(new ScoreService($pdo))->award($userId,'weather_envy_checked',2);(new AchievementService($pdo))->evaluate($userId);}catch(Throwable $e){$error=$e->getMessage();}}
$title='Weather Envy — Vacation Brain';require __DIR__.'/partials/header.php';
?>
<section class="dashboard"><div class="shell narrow"><div class="eyebrow">Weather Envy</div><h1 class="page-title">Somewhere is having a better day.</h1><p class="lede">No API key required. Tell Vacation Brain where you are and where you would rather be.</p>
<?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<form method="post" class="weather-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><label>Your current reality<input name="home" placeholder="Phoenix, Arizona" value="<?=e($_POST['home']??'')?>" required></label><label>Your better timeline<input name="dream" placeholder="San Diego, California" value="<?=e($_POST['dream']??'')?>" required></label><button class="button primary">Compare bad decisions</button></form>
<?php if($result):?><div class="weather-compare"><article><span>YOU ARE HERE</span><h2><?=e($result['home']['name'])?></h2><div class="weather-temp"><?=round($result['home']['temperature_f'])?>°</div><p><?=e($result['home']['condition'])?> · feels like <?=round($result['home']['feels_f'])?>°F</p></article><div class="weather-vs">VS</div><article><span>YOU COULD BE HERE</span><h2><?=e($result['dream']['name'])?></h2><div class="weather-temp"><?=round($result['dream']['temperature_f'])?>°</div><p><?=e($result['dream']['condition'])?> · feels like <?=round($result['dream']['feels_f'])?>°F</p></article></div><div class="agent-quote large"><?=e($result['line'])?></div><?php endif;?>
</div></section><?php require __DIR__.'/partials/footer.php';?>
