<?php
declare(strict_types=1);

$root=dirname(__DIR__);$read=static fn(string $f): string => file_get_contents($root.'/'.$f) ?: '';
$files=['db/053_connected_booking_inbox.sql','app/Services/BookingMailboxService.php','app/Services/BookingMailboxAgentContextService.php','booking-mailbox.php','booking-mail-oauth.php','booking-mail-source.php','assets/booking-mailbox.css','config-example.php','bin/run-travel-watches.php','partials/trip-command-center.php','api/trip-command-center.php','app/bootstrap.php'];
foreach($files as $f)if(!is_file($root.'/'.$f)){fwrite(STDERR,"Missing Connected Booking Inbox file: {$f}\n");exit(1);}
$m=$read('db/053_connected_booking_inbox.sql');foreach(['CREATE TABLE booking_mail_connections','CREATE TABLE booking_mail_messages','CREATE TABLE booking_change_proposals','access_token_encrypted','refresh_token_encrypted','source_encrypted','booking_snapshot_hash',"'app_version','1.45'"] as $n)if(strpos($m,$n)===false){fwrite(STDERR,"Connected Booking Inbox migration missing {$n}\n");exit(1);}
$s=$read('app/Services/BookingMailboxService.php');foreach(['final class BookingMailboxService','gmail.readonly','authorizationUrl','completeGoogleOAuth','syncUser','runDue','changeForBooking','booking_snapshot_hash','applyChange','dismissChange','augmentCommandCenterSnapshot','safeAgentContext','aes-256-gcm','redactPaymentData','booking-mail-oauth.php','TripBookingImportService','TripBookingService','TripTravelOperationsService','ProactiveTravelService','pageToken','deleteConnectedImports','markConnectionError'] as $n)if(strpos($s,$n)===false){fwrite(STDERR,"Connected Booking Inbox service missing {$n}\n");exit(1);}
foreach(['gmail.modify','gmail.send','gmail.compose','messages.send','messages.delete','messages.modify','TripBookingActionService','executeDirectCancellation','providerCheckout'] as $bad)if(stripos($s,$bad)!==false){fwrite(STDERR,"Connected Booking Inbox must remain read-only / transaction-isolated: {$bad}\n");exit(1);}
if(strpos($s,"status']!=='needs_review'")===false||strpos($s,'booking_snapshot_hash')===false){fwrite(STDERR,"Reservation changes must require current user review and stale-snapshot protection.\n");exit(1);}
if(strpos($s,'$bookingService->updateBookingStatus')===false||strpos($s,"'cancelled'")===false){fwrite(STDERR,"Provider-reported cancellation recording path missing.\n");exit(1);}
if(strpos($s,'provider_message_id,classification,status,error_message) VALUES (?,?,?,?,?,?)')===false){fwrite(STDERR,"Connected-mail error ledger must parameterize provider message IDs.\n");exit(1);}
if(strpos($s,'DELETE FROM trip_booking_imports')===false||strpos($s,'deleteConnectedImports')===false){fwrite(STDERR,"Disconnect must delete connected-mail import/source rows while preserving canonical bookings.\n");exit(1);}
$page=$read('booking-mailbox.php');foreach(['Connected Booking Inbox','Connect Gmail read-only','Sync now','Pause','Disconnect Gmail','Reservation changes','Apply factual change','Record provider cancellation','Redacted source','name="_csrf"','gmail.readonly','use_ai','auto_import'] as $n)if(strpos($page,$n)===false){fwrite(STDERR,"Connected Booking Inbox UI missing {$n}\n");exit(1);}
$oauth=$read('booking-mail-oauth.php');foreach(['require_auth','completeGoogleOAuth','state','code'] as $n)if(strpos($oauth,$n)===false){fwrite(STDERR,"Gmail OAuth callback missing {$n}\n");exit(1);}
$source=$read('booking-mail-source.php');foreach(['require_auth','Cache-Control: private, no-store','X-Content-Type-Options: nosniff','->source($userId,$messageId)'] as $n)if(strpos($source,$n)===false){fwrite(STDERR,"Connected-mail private source endpoint missing {$n}\n");exit(1);}
$agent=$read('app/Services/BookingMailboxAgentContextService.php');foreach(['CONNECTED BOOKING INBOX STATE','no mailbox/provider refresh','OAuth tokens','confirmation codes','payment data'] as $n)if(strpos($agent,$n)===false){fwrite(STDERR,"Connected booking agent safety context missing {$n}\n");exit(1);}
foreach(['source_encrypted','access_token_encrypted','refresh_token_encrypted','from_address','account_email'] as $bad)if(strpos($agent,$bad)!==false){fwrite(STDERR,"Connected booking agent context must not query private mailbox identity/source: {$bad}\n");exit(1);}
$worker=$read('bin/run-travel-watches.php');if(strpos($worker,'BookingMailboxService')===false||strpos($worker,'runDue($limit)')===false){fwrite(STDERR,"Connected mail must reuse the existing travel-watch worker.\n");exit(1);}
foreach(['partials/trip-command-center.php','api/trip-command-center.php'] as $f){$b=$read($f);if(strpos($b,'BookingMailboxService')===false||strpos($b,'augmentCommandCenterSnapshot')===false){fwrite(STDERR,"Command Center missing connected reservation-change integration in {$f}\n");exit(1);}}
$config=$read('config-example.php');foreach(['booking_mail','google_client_id','google_client_secret','google_redirect_uri','GOOGLE_GMAIL_CLIENT_ID','GOOGLE_GMAIL_CLIENT_SECRET'] as $n)if(strpos($config,$n)===false){fwrite(STDERR,"Connected mail config template missing {$n}\n");exit(1);}
$boot=$read('app/bootstrap.php');foreach(['/Services/BookingMailboxService.php','/Services/BookingMailboxAgentContextService.php'] as $n)if(strpos($boot,$n)===false){fwrite(STDERR,"Connected mail bootstrap missing {$n}\n");exit(1);}
$css=$read('assets/booking-mailbox.css');foreach(['vb-mailbox','vb-mail-change','vb-mail-diff','vb-mail-privacy'] as $n)if(strpos($css,$n)===false){fwrite(STDERR,"Connected mail styling missing {$n}\n");exit(1);}
echo "Connected Booking Inbox + Reservation Change Intelligence contract OK\n";
