<?php
declare(strict_types=1);

$root=dirname(__DIR__);$read=static fn(string $file): string => file_get_contents($root.'/'.$file) ?: '';
$files=['db/058_disruption_resolution_refund_intelligence.sql','app/Services/TripDisruptionResolutionService.php','app/Services/TripDisruptionResolutionAgentContextService.php','trip-resolution.php','trip-memory.php','assets/disruption-resolution.css','bin/run-travel-watches.php','app/Services/BookingActionAgentContextService.php','app/bootstrap.php','assets/trip-workspace-tabs.js'];
foreach($files as $file)if(!is_file($root.'/'.$file)){fwrite(STDERR,"Missing Disruption Resolution file: {$file}\n");exit(1);}

$m=$read('db/058_disruption_resolution_refund_intelligence.sql');
foreach(['resolution_checked_at','CREATE TABLE trip_resolution_cases','claim_needed','awaiting_provider','CREATE TABLE trip_resolution_entries','replacement_cost','refund_expected','refund_received','credit_expected','credit_received','insurance_received','voided_at','CREATE TABLE trip_resolution_evidence','CREATE TABLE trip_resolution_events',"'app_version','1.50'"] as $needle)if(strpos($m,$needle)===false){fwrite(STDERR,"Resolution migration missing {$needle}\n");exit(1);}
foreach(['card_number','payment_method','confirmation_code','provider_state_encrypted','access_token_encrypted','refresh_token_encrypted'] as $bad)if(strpos($m,$bad)!==false){fwrite(STDERR,"Resolution schema crossed a private/payment boundary: {$bad}\n");exit(1);}

$s=$read('app/Services/TripDisruptionResolutionService.php');
foreach(['final class TripDisruptionResolutionService','snapshot','saveCase','addEntry','voidEntry','addEvidence','tripFinancialSummary','safeAgentContext','runUpcoming','resolution_intelligence','Only the trip owner can manage refund, credit, expense and evidence records','Corrections are recorded by voiding','cash_outstanding','credits_received','net_cash_impact'] as $needle)if(strpos($s,$needle)===false){fwrite(STDERR,"Resolution service missing {$needle}\n");exit(1);}
foreach(['LiveTravelDataProviderService','TripBookingActionService','openHandoff','executeBookingComCancellation','prepareBookingComCancellation','confirmHandoff','getCurrentPosition','watchPosition','navigator.geolocation','card_number','payment_method','confirmation_code','provider_state_encrypted','access_token_encrypted','refresh_token_encrypted'] as $bad)if(strpos($s,$bad)!==false){fwrite(STDERR,"Resolution service crossed an execution/location/private boundary: {$bad}\n");exit(1);}

$agent=$read('app/Services/TripDisruptionResolutionAgentContextService.php');foreach(['DISRUPTION RESOLUTION + REFUND/CREDIT INTELLIGENCE','saved ledger only','explicit transaction approval','Financial detail is owner-only','Private evidence notes/URLs','Refunds, credits and reimbursements shown here are user-recorded'] as $needle)if(strpos($agent,$needle)===false){fwrite(STDERR,"Resolution agent safety context missing {$needle}\n");exit(1);}
foreach(['source_url','resolution_summary','void_reason','confirmation_code','provider_state_encrypted','access_token_encrypted','refresh_token_encrypted'] as $bad)if(strpos($agent,$bad)!==false){fwrite(STDERR,"Resolution agent context exposes private implementation field: {$bad}\n");exit(1);}

$page=$read('trip-resolution.php');foreach(['Disruption Resolution + Refund/Credit Intelligence','Track what the disruption actually cost','Credits stay separate from cash','Tracking is not execution','No provider or financial action was sent','verify_csrf()','name="_csrf"','Private resolution note','Private ledger note','Evidence','Trip Memory'] as $needle)if(strpos($page,$needle)===false){fwrite(STDERR,"Resolution Center UI missing {$needle}\n");exit(1);}
foreach(['openHandoff','executeBookingComCancellation','prepareBookingComCancellation','getCurrentPosition','watchPosition','navigator.geolocation'] as $bad)if(strpos($page,$bad)!==false){fwrite(STDERR,"Resolution Center must not execute provider/location actions: {$bad}\n");exit(1);}
$memory=$read('trip-memory.php');foreach(['TripDisruptionResolutionService','tripFinancialSummary','Disruption resolution outcome','factual trip history, not an automatic preference signal','Cash recovery and provider credits remain separate','trip-resolution.php?id='] as $needle)if(strpos($memory,$needle)===false){fwrite(STDERR,"Trip Memory is missing disruption resolution outcome context: {$needle}\n");exit(1);}

$runner=$read('bin/run-travel-watches.php');foreach(['TripDisruptionResolutionService',"\$result['resolution_intelligence']",'runUpcoming($limit)'] as $needle)if(strpos($runner,$needle)===false){fwrite(STDERR,"Resolution deadlines must reuse the existing travel-watch worker.\n");exit(1);}
$bookingAgent=$read('app/Services/BookingActionAgentContextService.php');foreach(['TripDisruptionResolutionAgentContextService','$resolution->context($userId,3)'] as $needle)if(strpos($bookingAgent,$needle)===false){fwrite(STDERR,"Main Vacation Brain agent is missing safe resolution context: {$needle}\n");exit(1);}
$boot=$read('app/bootstrap.php');foreach(['/Services/TripDisruptionResolutionService.php','/Services/TripDisruptionResolutionAgentContextService.php'] as $needle)if(strpos($boot,$needle)===false){fwrite(STDERR,"Resolution bootstrap missing {$needle}\n");exit(1);}
$tabs=$read('assets/trip-workspace-tabs.js');foreach(["['resolution','Resolution']",'trip-resolution.php?id=','Open Resolution Center'] as $needle)if(strpos($tabs,$needle)===false){fwrite(STDERR,"Trip workspace missing resolution entry: {$needle}\n");exit(1);}
$css=$read('assets/disruption-resolution.css');foreach(['vb-resolution-head','vb-resolution-summary','vb-resolution-financials','vb-resolution-case','vb-resolution-ledger','vb-resolution-evidence','@media(max-width:620px)'] as $needle)if(strpos($css,$needle)===false){fwrite(STDERR,"Resolution styling missing {$needle}\n");exit(1);}

echo "Disruption Resolution + Refund/Credit Intelligence contract OK\n";
