<?php
declare(strict_types=1);

$root=dirname(__DIR__);$read=static fn(string $file): string => file_get_contents($root.'/'.$file) ?: '';
$files=['db/057_recovery_rebooking_intelligence.sql','app/Services/TripRecoveryIntelligenceService.php','app/Services/TripRecoveryAgentContextService.php','trip-recovery.php','assets/recovery-intelligence.css','assets/trip-workspace-tabs.js','bin/run-travel-watches.php','app/Services/BookingActionAgentContextService.php','app/bootstrap.php'];
foreach($files as $file)if(!is_file($root.'/'.$file)){fwrite(STDERR,"Missing Recovery & Rebooking Intelligence file: {$file}\n");exit(1);}

$m=$read('db/057_recovery_rebooking_intelligence.sql');
foreach(['recovery_checked_at','CREATE TABLE trip_recovery_incidents','flight_cancelled','missed_connection_risk','weather_disruption','CREATE TABLE trip_recovery_options','alternate_flight','alternate_lodging','transaction_required','prepared_booking_id','CREATE TABLE trip_recovery_events',"'app_version','1.49'"] as $needle)if(strpos($m,$needle)===false){fwrite(STDERR,"Recovery migration missing {$needle}\n");exit(1);}
foreach(['card_number','payment_method','confirmation_code','provider_state_encrypted','access_token_encrypted','refresh_token_encrypted'] as $bad)if(strpos($m,$bad)!==false){fwrite(STDERR,"Recovery schema crossed a private/payment boundary: {$bad}\n");exit(1);}

$s=$read('app/Services/TripRecoveryIntelligenceService.php');
foreach(['final class TripRecoveryIntelligenceService','snapshot','refresh','setIncidentStatus','prepareOption','safeAgentContext','runUpcoming','refreshProviderResearch','LiveTravelDataProviderService','TripTravelDayCopilotService','TripItineraryIntelligenceService','TripBookingService','TripBookingActionService','ensureHandoffIntent','prepareHandoff','missed_connection_risk','weather_disruption','recovery_intelligence','Only the trip owner can prepare a recovery booking handoff','Only the trip owner or a Co-planner can refresh shared recovery research','This recovery option already has a prepared booking candidate.','resolveMissingWeather',"\$flight['ends_at']??\$flight['starts_at']",'dateAt((string)($item[\'checkin\']??\'\'),\'15:00:00\')',"status=IF(status='resolved','open',status)",'Read-only projection: expired active provider options render as stale without mutating shared state.'] as $needle)if(strpos($s,$needle)===false){fwrite(STDERR,"Recovery service missing {$needle}\n");exit(1);}
foreach(['executeDirectCancellation','executeBookingComCancellation','openHandoff','confirmHandoff','prepareBookingComCancellation','getCurrentPosition','watchPosition','navigator.geolocation','confirmation_code','provider_state_encrypted','access_token_encrypted','refresh_token_encrypted','payment_method',"UPDATE trip_recovery_options SET status='stale'","status=IF(status IN ('resolved','dismissed'),'open',status)"] as $bad)if(strpos($s,$bad)!==false){fwrite(STDERR,"Recovery service crossed an execution/location/private/read-only boundary: {$bad}\n");exit(1);}
if(strpos($s,"snapshot((int)\$row['user_id'],(int)\$row['id'],false,true)")===false){fwrite(STDERR,"Background recovery must detect without automatic provider refresh.\n");exit(1);}
if(strpos($s,"empty(\$access['is_owner'])")===false){fwrite(STDERR,"Recovery booking preparation must remain owner-only.\n");exit(1);}
if(strpos($s,"['research_only'=>true]")===false){fwrite(STDERR,"Provider support must remain a research/link option rather than an executable booking candidate.\n");exit(1);}

$agent=$read('app/Services/TripRecoveryAgentContextService.php');foreach(['RECOVERY & REBOOKING INTELLIGENCE','no provider, mailbox, payment, or device-location refresh','Recovery options are research and approval preparation','explicit transaction approval','Indicative airfare is planning data'] as $needle)if(strpos($agent,$needle)===false){fwrite(STDERR,"Recovery agent safety context missing {$needle}\n");exit(1);}
foreach(['latitude','longitude','confirmation_code','provider_state_encrypted','access_token_encrypted','refresh_token_encrypted'] as $bad)if(strpos($agent,$bad)!==false){fwrite(STDERR,"Recovery agent context must not expose exact/private fields: {$bad}\n");exit(1);}

$page=$read('trip-recovery.php');foreach(['Recovery & Rebooking Intelligence','Refresh live recovery options','Prepare booking handoff','Approval required','No automatic rebooking or cancellation','Booking & Action Execution','migration 057 / app v1.49','verify_csrf()','name="_csrf"','Trip owner approval required'] as $needle)if(strpos($page,$needle)===false){fwrite(STDERR,"Recovery Center UI missing {$needle}\n");exit(1);}
foreach(['executeDirectCancellation','openHandoff','confirmHandoff','getCurrentPosition','watchPosition'] as $bad)if(strpos($page,$bad)!==false){fwrite(STDERR,"Recovery Center must not execute provider/location actions directly: {$bad}\n");exit(1);}

$workspace=$read('assets/trip-workspace-tabs.js');foreach(["['recovery','Recovery']",'trip-recovery.php?id=','Open Recovery Center'] as $needle)if(strpos($workspace,$needle)===false){fwrite(STDERR,"Trip workspace Recovery integration missing {$needle}\n");exit(1);}
$runner=$read('bin/run-travel-watches.php');foreach(['TripRecoveryIntelligenceService',"\$result['recovery_intelligence']",'runUpcoming($limit)'] as $needle)if(strpos($runner,$needle)===false){fwrite(STDERR,"Recovery detection must reuse the existing travel-watch worker.\n");exit(1);}
$bookingAgent=$read('app/Services/BookingActionAgentContextService.php');foreach(['TripRecoveryAgentContextService','$recovery->context($userId,3)'] as $needle)if(strpos($bookingAgent,$needle)===false){fwrite(STDERR,"Main Vacation Brain agent is missing safe recovery context: {$needle}\n");exit(1);}
$boot=$read('app/bootstrap.php');foreach(['/Services/TripRecoveryIntelligenceService.php','/Services/TripRecoveryAgentContextService.php'] as $needle)if(strpos($boot,$needle)===false){fwrite(STDERR,"Recovery bootstrap missing {$needle}\n");exit(1);}
$css=$read('assets/recovery-intelligence.css');foreach(['vb-recovery-head','vb-recovery-summary','vb-recovery-incident','vb-recovery-option','vb-recovery-safety','@media(max-width:620px)'] as $needle)if(strpos($css,$needle)===false){fwrite(STDERR,"Recovery styling missing {$needle}\n");exit(1);}

echo "Recovery & Rebooking Intelligence contract OK\n";
