<?php
declare(strict_types=1);

$root=dirname(__DIR__);
$files=['db/045_traveler_memory_graph.sql','app/Services/TravelerMemoryGraphService.php','traveler-memory.php','assets/traveler-memory.css','partials/traveler-memory-summary.php','assets/traveler-memory-summary.css','dream-new.php','app/bootstrap.php','app/Services/DestinationRecommendationService.php','app/Services/VacationAgentService.php','partials/footer.php'];
foreach($files as $file){if(!is_file($root.'/'.$file)){fwrite(STDERR,"Missing Traveler Memory Graph file: {$file}\n");exit(1);}}
$read=static fn(string $file): string => file_get_contents($root.'/'.$file) ?: '';
$m=$read('db/045_traveler_memory_graph.sql');foreach(['traveler_preference_controls',"ENUM('learn','ignore','suppress')",'correction_note',"'app_version','1.37'"] as $n){if(strpos($m,$n)===false){fwrite(STDERR,"Traveler Memory migration missing {$n}\n");exit(1);}}
$s=$read('app/Services/TravelerMemoryGraphService.php');foreach(['class TravelerMemoryGraphService','function snapshot','function dashboardSummary','function setSignalControl','function setTripLearning','function augmentTraits','function rerankDestinations','function nextTripSeed','function agentContext','function rawSignals','function controlMap','function historySelect','m.learning_enabled=1','m.status="complete"','traveler_suppressed','Private trip notes are never included'] as $n){if(strpos($s,$n)===false){fwrite(STDERR,"Traveler Memory Graph service missing {$n}\n");exit(1);}}
if(strpos($s,'private_notes')!==false){fwrite(STDERR,"Traveler Memory Graph must not load or consume private trip notes.\n");exit(1);}
foreach(['user_id=? AND dream_trip_id=?','traveler_memory_correction','trip_memory_learning_changed',"['learn','ignore','suppress']"] as $n){if(strpos($s,$n)===false){fwrite(STDERR,"Traveler Memory ownership/correction audit missing {$n}\n");exit(1);}}
$page=$read('traveler-memory.php');foreach(['require_auth','verify_csrf()','Your Traveler Memory','Traveler DNA','Destination history','Spending intelligence','Travel history','Traveler DNA timeline','Ignore trip learning','Vacation Brain got this wrong','Use preference again','Do this again, better','migration 045 / app v1.37'] as $n){if(strpos($page,$n)===false){fwrite(STDERR,"Traveler Memory page missing {$n}\n");exit(1);}}
$seed=$read('dream-new.php');foreach(['memory_id','TravelerMemoryGraphService','nextTripSeed','Do this again, better','Private trip notes were not copied'] as $n){if(strpos($seed,$n)===false){fwrite(STDERR,"Repeat-trip seed missing {$n}\n");exit(1);}}
$rec=$read('app/Services/DestinationRecommendationService.php');foreach(['TravelerMemoryGraphService','augmentTraits','rerankDestinations','elseif($memory&&$memory->ready())'] as $n){if(strpos($rec,$n)===false){fwrite(STDERR,"Recommendation graph/fallback missing {$n}\n");exit(1);}}
$agent=$read('app/Services/VacationAgentService.php');foreach(['TravelerMemoryGraphService','agentContext($userId,5)','distinguish diagnosis guesses','never infer private trip notes'] as $n){if(strpos($agent,$n)===false){fwrite(STDERR,"Vacation agent Traveler Memory grounding missing {$n}\n");exit(1);}}
$footer=$read('partials/footer.php');foreach(['traveler-memory-summary.php','traveler-memory-summary.css'] as $n){if(strpos($footer,$n)===false){fwrite(STDERR,"Dashboard Traveler Memory integration missing {$n}\n");exit(1);}}
$partial=$read('partials/traveler-memory-summary.php');foreach(['dashboardSummary','Open Traveler Memory','completed trip'] as $n){if(strpos($partial,$n)===false){fwrite(STDERR,"Traveler Memory dashboard summary missing {$n}\n");exit(1);}}
$bootstrap=$read('app/bootstrap.php');if(strpos($bootstrap,"/Services/TravelerMemoryGraphService.php")===false){fwrite(STDERR,"TravelerMemoryGraphService is not loaded.\n");exit(1);}
echo "Traveler Memory Graph contract OK\n";
