<?php
declare(strict_types=1);

$root=dirname(__DIR__);$files=['db/043_travel_day_operations.sql','app/Services/TripTravelOperationsService.php','travel-mode.php','api/travel-operations.php','assets/travel-mode.css','assets/travel-mode.js','travel-mode-offline.html','assets/travel-mode-offline.js','service-worker.php','bin/run-travel-watches.php','api/trip-command-center.php','partials/trip-command-center.php','assets/trip-command-center.js','partials/footer.php','app/bootstrap.php'];
foreach($files as $file){if(!is_file($root.'/'.$file)){fwrite(STDERR,"Missing Travel Day Operations file: {$file}\n");exit(1);}}
$read=static fn(string $file): string => file_get_contents($root.'/'.$file) ?: '';
$m=$read('db/043_travel_day_operations.sql');foreach(['operational_state',"ENUM('planning','booking','ready','traveling','completed')",'travel_mode_started_at','trip_operation_events','operational_status','terminal','gate','status_source','checkin_url',"'app_version','1.35'"] as $n){if(strpos($m,$n)===false){fwrite(STDERR,"Travel operations migration missing {$n}\n");exit(1);}}
$s=$read('app/Services/TripTravelOperationsService.php');foreach(['class TripTravelOperationsService','function snapshot','function setState','function updateBookingOperations','function syncUpcoming','function offlineSnapshot','function augmentCommandCenterSnapshot','buildTimeline','timelineGroups','syncDisruptionActions','watchSignals','Travel status updated','recovery plan','requires_user_approval','external_booking_not_completed','status_source',"source_key LIKE 'travel-ops:%'"] as $n){if(strpos($s,$n)===false){fwrite(STDERR,"Travel operations service missing {$n}\n");exit(1);}}
foreach(["'planning','booking','ready','traveling','completed'","'unknown','scheduled','on_time','delayed','cancelled','completed'",'user_id=? AND dream_trip_id=?'] as $n){if(strpos($s,$n)===false){fwrite(STDERR,"Travel operations lifecycle/ownership missing {$n}\n");exit(1);}}
$page=$read('travel-mode.php');foreach(['require_auth','verify_csrf()','Travel Day Operations','Start Travel Mode','Complete trip','Flight operations','Trip wallet','Agent supervision','Save offline itinerary','Status not connected','Live provider status','Local Agent','trip-bookings.php','next-moves'] as $n){if(strpos($page,$n)===false){fwrite(STDERR,"Travel Mode page missing {$n}\n");exit(1);}}
$api=$read('api/travel-operations.php');foreach(['require_auth','Cache-Control: private, no-store','TripTravelOperationsService','operations','Trip not found','temporarily unavailable'] as $n){if(strpos($api,$n)===false){fwrite(STDERR,"Travel operations API missing {$n}\n");exit(1);}}
$js=$read('assets/travel-mode.js');foreach(['vacationBrain.travelOffline.','data-save-offline','data-remove-offline','removeOffline','serviceWorker','60000','300000','Sensitive confirmation details were excluded'] as $n){if(strpos($js,$n)===false){fwrite(STDERR,"Travel Mode client missing {$n}\n");exit(1);}}if(strpos($js,'Math.random')!==false){fwrite(STDERR,"Travel Mode must use real state, not random activity.\n");exit(1);}
$offline=$read('assets/travel-mode-offline.js');foreach(['vacationBrain.travelOffline.','No confirmation codes','localStorage','Saved itinerary'] as $n){if(strpos($offline,$n)===false){fwrite(STDERR,"Offline Travel Mode missing {$n}\n");exit(1);}}
$sw=$read('service-worker.php');foreach(['vacation-brain-shell-v3','travel-mode-offline.html','travel-mode.php','caches.match(OFFLINE_TRAVEL)'] as $n){if(strpos($sw,$n)===false){fwrite(STDERR,"Service worker Travel Mode fallback missing {$n}\n");exit(1);}}if(strpos($sw,"caches.open(CACHE).then(c=>c.put(event.request")!==false){fwrite(STDERR,"Authenticated Travel Mode HTML must not be cached as the offline copy.\n");exit(1);}
$worker=$read('bin/run-travel-watches.php');if(strpos($worker,'TripTravelOperationsService')===false||strpos($worker,'syncUpcoming')===false){fwrite(STDERR,"Existing watch worker does not maintain travel-day state.\n");exit(1);}
$commandApi=$read('api/trip-command-center.php');if(strpos($commandApi,'TripTravelOperationsService')===false||strpos($commandApi,'augmentCommandCenterSnapshot')===false){fwrite(STDERR,"Command Center API does not expose Travel Mode lifecycle.\n");exit(1);}
$commandServer=$read('partials/trip-command-center.php');foreach(['TripTravelOperationsService','augmentCommandCenterSnapshot','travel_mode_prominent','travel_mode_url','Travel Mode'] as $n){if(strpos($commandServer,$n)===false){fwrite(STDERR,"Command Center server render missing Travel Mode lifecycle {$n}\n");exit(1);}}
$commandJs=$read('assets/trip-command-center.js');foreach(['travel_mode_prominent','travel_mode_url','Travel Mode'] as $n){if(strpos($commandJs,$n)===false){fwrite(STDERR,"Command Center does not promote Travel Mode.\n");exit(1);}}
$footer=$read('partials/footer.php');foreach(['data-travel-mode-link','travel-mode.php?id=','Travel Mode · Live','Travel Mode · Ready'] as $n){if(strpos($footer,$n)===false){fwrite(STDERR,"Trip workspace Travel Mode link missing {$n}\n");exit(1);}}
$bootstrap=$read('app/bootstrap.php');if(strpos($bootstrap,"/Services/TripTravelOperationsService.php")===false){fwrite(STDERR,"TripTravelOperationsService is not loaded.\n");exit(1);}
$service=$read('app/Services/TripTravelOperationsService.php');if(strpos($service,"'confirmation_code'=>(string)")===false||strpos($service,"'privacy_note'=>'Offline copy excludes confirmation codes")===false){fwrite(STDERR,"Travel wallet/offline privacy boundary is not explicit.\n");exit(1);}
echo "Travel Day Operations contract OK\n";