<?php
declare(strict_types=1);

$root=dirname(__DIR__);$files=['db/042_trip_booking_readiness.sql','app/Services/TripBookingService.php','app/Services/TripBookingReminderService.php','trip-bookings.php','partials/trip-booking-fields.php','api/trip-bookings.php','assets/trip-bookings.css','assets/trip-booking-summary.js','trip-execution.php','api/trip-command-center.php','assets/trip-command-center.js','partials/trip-command-center.php','partials/footer.php','app/bootstrap.php'];
foreach($files as $file){if(!is_file($root.'/'.$file)){fwrite(STDERR,"Missing Booking + Trip Readiness file: {$file}\n");exit(1);}}
$read=static fn(string $file): string => file_get_contents($root.'/'.$file) ?: '';
$m=$read('db/042_trip_booking_readiness.sql');foreach(['CREATE TABLE trip_bookings','CREATE TABLE trip_readiness_requirements','CREATE TABLE trip_booking_events',"ENUM('unbooked','ready_to_book','booked','confirmed','changed','cancelled')",'cancellation_deadline','checkin_opens_at','confirmation_code','source_execution_id','requires_live_confirmation','uq_trip_booking_execution',"'app_version','1.34'",'Convert previously approved booking handoffs'] as $n){if(strpos($m,$n)===false){fwrite(STDERR,"Booking migration missing {$n}\n");exit(1);}}
$s=$read('app/Services/TripBookingService.php');foreach(['class TripBookingService','function snapshot','function readiness','function saveBooking','function updateBookingStatus','function saveRequirement','function syncApprovedHandoff','function augmentCommandCenterSnapshot','ensureDefaults','syncHistoricalHandoffs','calculateReadiness','commandHandoffs','commandAttention',"status='completed'","proposal_type='booking_handoff'",'ready_to_book','requires_live_confirmation','Confirm live availability, final price, terms, and payment','user_id=? AND dream_trip_id=?','rowCount()!==1'] as $n){if(strpos($s,$n)===false){fwrite(STDERR,"Booking service missing {$n}\n");exit(1);}}
$reminder=$read('app/Services/TripBookingReminderService.php');foreach(['class TripBookingReminderService','function dueAttention','function augmentCommandCenterSnapshot',"is_required=1","status='open'",'r.due_at<=?','Required trip item is overdue','Required trip item due soon','Review readiness','user_id=?'] as $n){if(strpos($reminder,$n)===false){fwrite(STDERR,"Booking reminder projection missing {$n}\n");exit(1);}}
$page=$read('trip-bookings.php');foreach(['require_auth','verify_csrf()','Booking & Trip Readiness','What this trip actually requires','Reservations & confirmations','Add a booking or reservation','Live confirmation required','trip-booking-fields.php','migration 042'] as $n){if(strpos($page,$n)===false){fwrite(STDERR,"Booking page missing {$n}\n");exit(1);}}
$fields=$read('partials/trip-booking-fields.php');foreach(['confirmation_code','payment_status','cancellation_deadline','checkin_opens_at','provider_url','ready_to_book','confirmed','changed','cancelled'] as $n){if(strpos($fields,$n)===false){fwrite(STDERR,"Booking fields missing {$n}\n");exit(1);}}
$api=$read('api/trip-bookings.php');foreach(['require_auth','REQUEST_METHOD','TripBookingService','trip_id','Cache-Control'] as $n){if(strpos($api,$n)===false){fwrite(STDERR,"Booking API missing {$n}\n");exit(1);}}
$execution=$read('trip-execution.php');foreach(['TripBookingService','syncApprovedHandoff','Ready to Book','Confirm live availability'] as $n){if(strpos($execution,$n)===false){fwrite(STDERR,"Booking handoff execution integration missing {$n}\n");exit(1);}}
$commandApi=$read('api/trip-command-center.php');foreach(['TripBookingService','TripBookingReminderService','augmentCommandCenterSnapshot'] as $n){if(strpos($commandApi,$n)===false){fwrite(STDERR,"Command Center API booking projection missing {$n}\n");exit(1);}}
$commandPartial=$read('partials/trip-command-center.php');foreach(['TripBookingService','TripBookingReminderService','augmentCommandCenterSnapshot','booking_summary','booking_url','required open','Live confirmation required','Reconfirm'] as $n){if(strpos($commandPartial,$n)===false){fwrite(STDERR,"Server-rendered Command Center booking readiness missing {$n}\n");exit(1);}}
$commandJs=$read('assets/trip-command-center.js');foreach(['booking_summary','booking_url','ready_to_book','Reconfirm','load(true)'] as $n){if(strpos($commandJs,$n)===false){fwrite(STDERR,"Command Center booking UI missing {$n}\n");exit(1);}}
$summaryJs=$read('assets/trip-booking-summary.js');foreach(['data-vb-booking-summary-config','trip_id','Manage bookings','required open','ready to book'] as $n){if(strpos($summaryJs,$n)===false){fwrite(STDERR,"Trip booking summary missing {$n}\n");exit(1);}}if(strpos($summaryJs,'Math.random')!==false){fwrite(STDERR,"Trip readiness must be data-derived.\n");exit(1);}
$footer=$read('partials/footer.php');foreach(['trip-bookings.css','trip-booking-summary.js','data-vb-booking-summary-config','api/trip-bookings.php','trip-bookings.php?id='] as $n){if(strpos($footer,$n)===false){fwrite(STDERR,"Trip workspace booking wiring missing {$n}\n");exit(1);}}
$bootstrap=$read('app/bootstrap.php');foreach(['/Services/TripBookingService.php','/Services/TripBookingReminderService.php'] as $n){if(strpos($bootstrap,$n)===false){fwrite(STDERR,"Booking service bootstrap missing {$n}\n");exit(1);}}
echo "Booking + Trip Readiness contract OK\n";
