<?php
declare(strict_types=1);

$root=dirname(__DIR__);$files=['db/041_trip_action_execution_approval.sql','app/Services/TripAgentExecutionService.php','trip-execution.php','trip-action.php','partials/trip-action-queue.php','assets/trip-live-agents.css','bin/run-trip-agent-jobs.php','api/brain-activity.php','app/bootstrap.php'];
foreach($files as $file){if(!is_file($root.'/'.$file)){fwrite(STDERR,"Missing Trip Action execution file: {$file}\n");exit(1);}}
$read=static fn(string $file): string => file_get_contents($root.'/'.$file) ?: '';
$m=$read('db/041_trip_action_execution_approval.sql');foreach(['CREATE TABLE trip_agent_action_executions','CREATE TABLE trip_agent_action_events',"ENUM('queued','agent_working','awaiting_approval','applied','completed','rejected','failed','cancelled')","ENUM('planning_task','itinerary_item','booking_handoff','budget_review')",'uq_trip_action_execution_action','fk_trip_action_execution_action','fk_trip_action_execution_job',"'app_version','1.33'"] as $n){if(strpos($m,$n)===false){fwrite(STDERR,"Execution migration missing {$n}\n");exit(1);}}
$s=$read('app/Services/TripAgentExecutionService.php');foreach(['class TripAgentExecutionService','function acceptAndStart','function dispatchQueued','function syncFinishedJobs','function executionsForActions','function editProposal','function approveAndApply','function reject','function release','function retry','executionRequest','createProposal','applyProposal','booking_handoff','requires_external_confirmation','confirm live availability, final price, terms, and payment','TripAgentJobService','DreamService','NotificationService',"status='awaiting_approval'", "status='completed'", "status='rejected'", "status='failed'"] as $n){if(strpos($s,$n)===false){fwrite(STDERR,"Execution service missing {$n}\n");exit(1);}}
if(strpos($s,'booked')!==false&&strpos($s,'do not claim anything was booked')===false){fwrite(STDERR,"Execution service must not imply external bookings are completed.\n");exit(1);}
$endpoint=$read('trip-execution.php');foreach(['require_auth','REQUEST_METHOD','verify_csrf()','TripAgentExecutionService','editProposal','approveAndApply','reject','retry','#next-moves'] as $n){if(strpos($endpoint,$n)===false){fwrite(STDERR,"Execution endpoint missing {$n}\n");exit(1);}}
$action=$read('trip-action.php');foreach(['acceptAndStart','executionForAction','release','Action Execution + Approval'] as $n){if(strpos($action,$n)===false){fwrite(STDERR,"Next Move acceptance is not wired to execution: {$n}\n");exit(1);}}
$ui=$read('partials/trip-action-queue.php');foreach(['Decision + execution queue','Approve & apply','Edit proposal','Reject','Queued for specialist','Specialist working','Waiting for your approval','migration 041','trip-execution.php','requires_external_confirmation'] as $n){if(strpos($ui,$n)===false){fwrite(STDERR,"Execution UI missing {$n}\n");exit(1);}}
$worker=$read('bin/run-trip-agent-jobs.php');foreach(['TripAgentExecutionService','dispatchQueued','syncFinishedJobs','execution_dispatch','execution_sync'] as $n){if(strpos($worker,$n)===false){fwrite(STDERR,"Execution worker integration missing {$n}\n");exit(1);}}
$brain=$read('api/brain-activity.php');foreach(['vb_apply_action_execution_to_activity','pending_action_approvals','active_action_executions','approval_waiting','action_working','Executing Next Moves','Trip Approval Waiting'] as $n){if(strpos($brain,$n)===false){fwrite(STDERR,"Agent EEG execution state missing {$n}\n");exit(1);}}
$bootstrap=$read('app/bootstrap.php');if(strpos($bootstrap,"/Services/TripAgentExecutionService.php")===false){fwrite(STDERR,"TripAgentExecutionService is not loaded.\n");exit(1);}
echo "Trip Action Execution + Approval contract OK\n";