<?php
declare(strict_types=1);

$root=dirname(__DIR__);$read=static fn(string $file): string => file_get_contents($root.'/'.$file) ?: '';
$files=['db/054_unified_trip_inbox.sql','app/Services/TripUnifiedInboxService.php','app/Services/TripUnifiedInboxAgentContextService.php','app/Services/TripUnifiedInboxWorkerService.php','trip-inbox.php','assets/trip-inbox.css','partials/header.php','partials/trip-command-center.php','api/trip-command-center.php','bin/run-travel-watches.php','app/Services/BookingActionAgentContextService.php','app/bootstrap.php'];
foreach($files as $file)if(!is_file($root.'/'.$file)){fwrite(STDERR,"Missing Unified Trip Inbox file: {$file}\n");exit(1);}

$m=$read('db/054_unified_trip_inbox.sql');foreach(['CREATE TABLE trip_inbox_items','CREATE TABLE trip_inbox_events','CREATE TABLE trip_inbox_preferences','CREATE TABLE trip_inbox_trip_preferences','source_fingerprint','thread_key','requires_action','snoozed_until','delivery_mode','immediate_disruptions','last_synced_at','idx_trip_inbox_sync_queue',"'app_version','1.46'"] as $needle)if(strpos($m,$needle)===false){fwrite(STDERR,"Unified Trip Inbox migration missing {$needle}\n");exit(1);}

$s=$read('app/Services/TripUnifiedInboxService.php');foreach(['final class TripUnifiedInboxService','accessibleTrips','syncUser','threads','summary','savePreferences','setTripMuted','markRead','resolve','reopen','snooze','safeAgentContext','augmentCommandCenterSnapshot','syncProactive','syncAgentActions','syncAgentJobs','syncBookingImports','syncBookingChanges','syncBookingActions','syncWatchEvents','syncOperations','syncBookingDeadlines','syncCollaboration','autoResolveMissing',"$role==='owner'","['owner','co_planner','traveler']",'trip_inbox_items','source_fingerprint'] as $needle)if(strpos($s,$needle)===false){fwrite(STDERR,"Unified Trip Inbox service missing {$needle}\n");exit(1);}
foreach(['TripBookingActionService','executeDirectCancellation','providerCheckout','completeGoogleOAuth','gmailJson','curl_init','navigator.geolocation','watchPosition','getCurrentPosition','source_encrypted','access_token_encrypted','refresh_token_encrypted','confirmation_code','provider_reference','provider_state_encrypted'] as $bad)if(strpos($s,$bad)!==false){fwrite(STDERR,"Unified Trip Inbox projection crossed a private/transaction boundary: {$bad}\n");exit(1);}
if(strpos($s,"elseif($event==='resolved')")===false||strpos($s,"elseif($event==='snoozed')")===false||strpos($s,'trip_inbox_events')===false){fwrite(STDERR,"Unified Trip Inbox local state/audit path is incomplete.\n");exit(1);}

$agent=$read('app/Services/TripUnifiedInboxAgentContextService.php');foreach(['UNIFIED TRIP INBOX STATE','no provider, mailbox, device-location, or external refresh','Resolve/Snooze/Read state is local presentation state','canonical source flow','confirmation codes','payment data','exact device coordinates','private Traveler Memory'] as $needle)if(strpos($agent,$needle)===false){fwrite(STDERR,"Unified Trip Inbox agent safety context missing {$needle}\n");exit(1);}
foreach(['source_encrypted','access_token_encrypted','refresh_token_encrypted','provider_state_encrypted','confirmation_code','location_latitude','location_longitude'] as $bad)if(strpos($agent,$bad)!==false){fwrite(STDERR,"Unified Trip Inbox agent context must not query private source fields: {$bad}\n");exit(1);}

$worker=$read('app/Services/TripUnifiedInboxWorkerService.php');foreach(['final class TripUnifiedInboxWorkerService','runDue','last_synced_at',"COALESCE(p.last_synced_at,'1970-01-01 00:00:00')",'markSynced','TripUnifiedInboxService'] as $needle)if(strpos($worker,$needle)===false){fwrite(STDERR,"Unified Trip Inbox fair worker queue missing {$needle}\n");exit(1);}
$runner=$read('bin/run-travel-watches.php');foreach(['TripUnifiedInboxWorkerService','runDue($limit)',"$result['trip_inbox']"] as $needle)if(strpos($runner,$needle)===false){fwrite(STDERR,"Unified Trip Inbox must reuse the existing travel-watch worker.\n");exit(1);}

$page=$read('trip-inbox.php');foreach(['Unified trip communications','Trip Inbox','Needs action','Unread','Snoozed','Inbox settings','delivery_mode','immediate_disruptions','Mute trip','Resolve here','Snooze','Ask agent','canonical source systems','does not store raw Gmail bodies','Resolve and Snooze change only inbox presentation state','migration 054','name="_csrf"'] as $needle)if(strpos($page,$needle)===false){fwrite(STDERR,"Unified Trip Inbox UI missing {$needle}\n");exit(1);}
foreach(['approve(', 'execute(', 'updateBookingStatus(', 'completeGoogleOAuth(', 'getCurrentPosition(', 'watchPosition('] as $bad)if(strpos($page,$bad)!==false){fwrite(STDERR,"Unified Trip Inbox UI must route canonical actions rather than execute them: {$bad}\n");exit(1);}

$header=$read('partials/header.php');foreach(['$tripInboxUnread','TripUnifiedInboxService','trip-inbox.php','Trip Inbox'] as $needle)if(strpos($header,$needle)===false){fwrite(STDERR,"Global Trip Inbox navigation missing {$needle}\n");exit(1);}
foreach(['partials/trip-command-center.php','api/trip-command-center.php'] as $file){$body=$read($file);foreach(['TripUnifiedInboxService','augmentCommandCenterSnapshot'] as $needle)if(strpos($body,$needle)===false){fwrite(STDERR,"Command Center missing Unified Trip Inbox integration in {$file}\n");exit(1);}}
$command=$read('partials/trip-command-center.php');foreach(['trip-inbox.php','Trip Inbox','read-only attention layer'] as $needle)if(strpos($command,$needle)===false){fwrite(STDERR,"Command Center Trip Inbox navigation/safety copy missing {$needle}\n");exit(1);}

$bookingAgent=$read('app/Services/BookingActionAgentContextService.php');foreach(['TripUnifiedInboxAgentContextService','$inbox->context($userId,8)'] as $needle)if(strpos($bookingAgent,$needle)===false){fwrite(STDERR,"Main Vacation Brain agent is missing safe Trip Inbox context: {$needle}\n");exit(1);}
$boot=$read('app/bootstrap.php');foreach(['/Services/TripUnifiedInboxService.php','/Services/TripUnifiedInboxAgentContextService.php','/Services/TripUnifiedInboxWorkerService.php'] as $needle)if(strpos($boot,$needle)===false){fwrite(STDERR,"Unified Trip Inbox bootstrap missing {$needle}\n");exit(1);}
$css=$read('assets/trip-inbox.css');foreach(['vb-trip-inbox','vb-inbox-stats','vb-inbox-thread','vb-inbox-timeline','vb-inbox-snooze','vb-inbox-settings','@media(max-width:620px)'] as $needle)if(strpos($css,$needle)===false){fwrite(STDERR,"Unified Trip Inbox styling missing {$needle}\n");exit(1);}

echo "Unified Trip Communications + Action Inbox contract OK\n";
