<?php
require __DIR__.'/../app/bootstrap.php';
$adminId=require_admin();$pdo=db();$service=new ContentFactoryService($pdo);
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='create_job'){
            $jobId=$service->createJob($adminId,(string)$_POST['content_type'],(int)$_POST['count'],['theme'=>$_POST['theme']??'','audience'=>$_POST['audience']??'','tone'=>$_POST['tone']??'','notes'=>$_POST['notes']??'']);
            flash('success','Generation job created. Copy the prompt, run it in your preferred model, then paste the JSON batch back here.');redirect('admin/ai-content.php?job='.$jobId);
        }
        if($action==='import_json'){
            $count=$service->importCandidates((int)$_POST['job_id'],(string)$_POST['json_batch']);flash('success',"Imported {$count} candidates for review.");redirect('admin/review-content.php');
        }
    }catch(Throwable $e){flash('error',$e->getMessage());redirect('admin/ai-content.php'.(!empty($_POST['job_id'])?'?job='.(int)$_POST['job_id']:''));}
}
$jobId=(int)($_GET['job']??0);$job=$jobId?$service->job($jobId):null;$prompt=$job?$service->renderPrompt($job):'';
$jobs=$pdo->query('SELECT j.*,p.name AS prompt_name,(SELECT COUNT(*) FROM ai_generated_candidates c WHERE c.job_id=j.id) AS candidate_count FROM ai_generation_jobs j JOIN ai_prompt_templates p ON p.id=j.prompt_template_id ORDER BY j.id DESC LIMIT 20')->fetchAll();
$manifest=$pdo->query('SELECT content_type,target_count FROM seed_generation_manifest WHERE active=1 ORDER BY priority,content_type')->fetchAll();$success=flash('success');$error=flash('error');
$title='AI Content Factory — Vacation Brain';require __DIR__.'/../partials/header.php';
?>
<section class="dashboard"><div class="shell"><div class="dashboard-head"><div><div class="eyebrow">Admin · Content Factory</div><h1>Generate without hard-wiring an AI provider.</h1><p class="muted">Create a structured job, use any model, import valid JSON, then approve what earns its place in Vacation Brain.</p></div><a class="button secondary small" href="<?=e(app_url('admin/index.php'))?>">Admin home</a></div>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="admin-two"><article class="dashboard-card"><h2>Create generation job</h2><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create_job"><div class="field"><label>Content type</label><select name="content_type" required><?php foreach($manifest as $m):?><option value="<?=e($m['content_type'])?>"><?=e($m['content_type'])?> — target <?= (int)$m['target_count']?></option><?php endforeach;?></select></div><div class="field"><label>Count</label><input type="number" min="1" max="250" name="count" value="25"></div><div class="field"><label>Theme</label><input name="theme" placeholder="airport, couples, beach brain..."></div><div class="field"><label>Audience</label><input name="audience" value="general adult travelers"></div><div class="field"><label>Tone</label><input name="tone" value="funny, playful, sarcastic"></div><div class="field"><label>Notes</label><textarea name="notes" placeholder="Anything the generation batch should emphasize or avoid"></textarea></div><button class="button primary">Create prompt</button></form></article>
<article class="dashboard-card"><h2>How this works</h2><ol class="plain-steps"><li>Create a job here.</li><li>Copy its prompt into ChatGPT or another model.</li><li>Paste the returned JSON batch into the importer.</li><li>Review each candidate.</li><li>Publish approved records to the master content library.</li></ol><p class="muted">This means the installer does not need an OpenAI, Anthropic, or other provider key. We can still generate the 2,000+ records efficiently.</p></article></div>
<?php if($job):?><article class="dashboard-card" style="margin-top:20px"><div class="admin-table-head"><div><h2>Job #<?=(int)$job['id']?> · <?=e($job['content_type'])?></h2><p class="muted"><?=(int)$job['requested_count']?> requested records.</p></div></div><div class="field"><label>Generation prompt</label><textarea class="code-area" readonly><?=e($prompt)?></textarea></div><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="import_json"><input type="hidden" name="job_id" value="<?=(int)$job['id']?>"><div class="field"><label>Paste generated JSON</label><textarea class="code-area" name="json_batch" placeholder='{"items":[...]}' required></textarea></div><button class="button primary">Import candidates</button></form></article><?php endif;?>
<article class="dashboard-card" style="margin-top:20px"><div class="admin-table-head"><h2>Recent generation jobs</h2><a class="link-arrow" href="<?=e(app_url('admin/review-content.php'))?>">Review queue →</a></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Job</th><th>Type</th><th>Requested</th><th>Candidates</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($jobs as $j):?><tr><td>#<?=(int)$j['id']?></td><td><?=e($j['content_type'])?></td><td><?=(int)$j['requested_count']?></td><td><?=(int)$j['candidate_count']?></td><td><?=e($j['status'])?></td><td><a class="link-arrow" href="?job=<?=(int)$j['id']?>">Open →</a></td></tr><?php endforeach;?></tbody></table></div></article>
</div></section><?php require __DIR__.'/../partials/footer.php';?>
