<?php
require __DIR__.'/../app/bootstrap.php';$adminId=require_assessor();$pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{
  $id=(int)($_POST['id']??0);$status=(string)($_POST['status']??'requested');
  if(!in_array($status,['requested','in_review','completed','cancelled'],true))throw new InvalidArgumentException('Invalid status.');
  $notes=trim((string)($_POST['assessor_notes']??''));
  $result=trim((string)($_POST['assessment_result_json']??''));
  if($result!==''){json_decode($result,true,512,JSON_THROW_ON_ERROR);}else{$result=null;}
  $stmt=$pdo->prepare('UPDATE professional_assessment_requests SET status=?,assigned_to=CASE WHEN ?="in_review" THEN ? ELSE assigned_to END,assessor_notes=?,assessment_result_json=?,completed_at=CASE WHEN ?="completed" THEN NOW() ELSE completed_at END WHERE id=?');
  $stmt->execute([$status,$status,$adminId,$notes?:null,$result,$status,$id]);
  flash('success','Assessment request updated.');redirect('admin/assessments.php');
}catch(Throwable $e){flash('error',$e->getMessage());redirect('admin/assessments.php');}}
$rows=$pdo->query('SELECT r.*,u.display_name AS user_name,d.diagnosis_score,d.diagnosis_title,d.vacation_brain_score FROM professional_assessment_requests r LEFT JOIN users u ON u.id=r.user_id LEFT JOIN diagnosis_results d ON d.id=r.diagnosis_result_id ORDER BY CASE r.status WHEN "requested" THEN 0 WHEN "in_review" THEN 1 ELSE 2 END,r.created_at DESC LIMIT 100')->fetchAll();
$success=flash('success');$error=flash('error');$title='Professional Assessments — Vacation Brain';require __DIR__.'/../partials/header.php';
?>
<section class="dashboard"><div class="shell"><div class="dashboard-head"><div><div class="eyebrow">Admin · Assessments</div><h1>Professional assessment queue</h1><p class="muted">Human Vacation Brain travel-preference reviews. These are not medical diagnoses.</p></div><a class="button secondary small" href="<?=e(app_url('admin/index.php'))?>">Admin home</a></div><?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="review-stack"><?php foreach($rows as $r):?><article class="review-card"><div class="review-head"><div><span class="status-pill"><?=e($r['status'])?></span><strong><?=e($r['display_name']?:$r['user_name']?:'Vacation Brain user')?></strong></div><span class="muted small"><?=e($r['email'])?> · <?=e($r['created_at'])?></span></div><?php if($r['diagnosis_title']):?><div class="diagnosis-scoreline" style="margin-top:12px"><strong><?=e($r['diagnosis_title'])?></strong><span>Diagnosis <?=(int)$r['diagnosis_score']?>/100</span><span>Brain score <?=(int)$r['vacation_brain_score']?></span></div><?php endif;?><p><?=e($r['notes']?:'No additional user notes.')?></p><details><summary>Review assessment</summary><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><div class="field"><label>Status</label><select name="status"><option value="requested" <?=$r['status']==='requested'?'selected':''?>>Requested</option><option value="in_review" <?=$r['status']==='in_review'?'selected':''?>>In review</option><option value="completed" <?=$r['status']==='completed'?'selected':''?>>Completed</option><option value="cancelled" <?=$r['status']==='cancelled'?'selected':''?>>Cancelled</option></select></div><div class="field"><label>Assessor notes</label><textarea name="assessor_notes"><?=e($r['assessor_notes']??'')?></textarea></div><div class="field"><label>Structured result JSON (optional)</label><textarea class="code-area" name="assessment_result_json" placeholder='{"vacation_style":"...","recommended_trip":"..."}'><?=e($r['assessment_result_json']??'')?></textarea></div><button class="button primary small">Save assessment</button></form></details></article><?php endforeach;?></div>
<?php if(!$rows):?><div class="dashboard-card center"><h2>No assessment requests yet.</h2><p class="muted">The funnel is ready when the first Vacation Brain needs a second opinion.</p></div><?php endif;?></div></section><?php require __DIR__.'/../partials/footer.php';?>
