<?php
require __DIR__.'/../app/bootstrap.php';$adminId=require_admin();
if (!db_table_exists('site_settings')) redirect('upgrade.php');$upload=new UploadService(dirname(__DIR__));$success=flash('success');$error=flash('error');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{
  set_site_setting('brand.site_name',trim((string)($_POST['site_name']??'Vacation Brain'))?:'Vacation Brain','branding',$adminId);
  $logo=site_setting('brand.logo_url','');if(!empty($_FILES['logo']['name'])){$logo=$upload->storeImage($_FILES['logo'],$adminId,'branding-logo',120,40)??$logo;set_site_setting('brand.logo_url',$logo,'branding',$adminId);}elseif(isset($_POST['remove_logo']))set_site_setting('brand.logo_url','','branding',$adminId);
  foreach(['app_name','short_name','description','theme_color','background_color','display'] as $k){set_site_setting('pwa.'.$k,trim((string)($_POST[$k]??'')),'pwa',$adminId);}set_site_setting('pwa.enabled',isset($_POST['pwa_enabled'])?'1':'0','pwa',$adminId);
  $icon=site_setting('pwa.icon_url','');if(!empty($_FILES['app_icon']['name'])){$icon=$upload->storeImage($_FILES['app_icon'],$adminId,'pwa-icon',256,256)??$icon;set_site_setting('pwa.icon_url',$icon,'pwa',$adminId);}elseif(isset($_POST['remove_icon']))set_site_setting('pwa.icon_url','','pwa',$adminId);
  $splash=site_setting('pwa.splash_url','');if(!empty($_FILES['splash_screen']['name'])){$splash=$upload->storeImage($_FILES['splash_screen'],$adminId,'pwa-splash',600,600)??$splash;set_site_setting('pwa.splash_url',$splash,'pwa',$adminId);}elseif(isset($_POST['remove_splash']))set_site_setting('pwa.splash_url','','pwa',$adminId);
  flash('success','Brand & PWA settings saved.');redirect('admin/brand-pwa.php');
}catch(Throwable $e){flash('error',$e->getMessage());redirect('admin/brand-pwa.php');}}
$settings=[];foreach(['brand.site_name','brand.logo_url','pwa.enabled','pwa.app_name','pwa.short_name','pwa.description','pwa.theme_color','pwa.background_color','pwa.display','pwa.icon_url','pwa.splash_url'] as $key)$settings[$key]=site_setting($key,'');$title='Brand & PWA — Admin';require __DIR__.'/../partials/header.php';
?>
<section class="dashboard"><div class="shell"><div class="dashboard-head"><div><div class="eyebrow">Admin · Brand & PWA</div><h1>Logo & app settings</h1><p class="muted">Manage the Vacation Brain logo, installable app metadata, app icon, and branded splash image.</p></div></div><?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<form method="post" enctype="multipart/form-data" class="stack"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><div class="dashboard-card stack"><h2>Brand</h2><label>Site name<input class="input" name="site_name" value="<?=e($settings['brand.site_name']?:'Vacation Brain')?>"></label><div class="brand-upload-row"><?php if($settings['brand.logo_url']):?><img class="admin-brand-preview" src="<?=e($settings['brand.logo_url'])?>" alt="Current logo"><?php endif;?><label>Logo image<input class="input" type="file" name="logo" accept="image/jpeg,image/png,image/webp"></label></div><?php if($settings['brand.logo_url']):?><label class="check-row"><input type="checkbox" name="remove_logo"> Remove current logo</label><?php endif;?></div>
<div class="dashboard-card stack"><div class="admin-table-head"><div><h2>Progressive Web App</h2><p class="muted">When enabled, Vacation Brain publishes install metadata and registers a lightweight service worker.</p></div><label class="check-row"><input type="checkbox" name="pwa_enabled" <?=site_setting_bool('pwa.enabled')?'checked':''?>> Enable PWA</label></div><div class="form-grid"><label>App name<input class="input" name="app_name" value="<?=e($settings['pwa.app_name']?:'Vacation Brain')?>"></label><label>Short name<input class="input" name="short_name" maxlength="40" value="<?=e($settings['pwa.short_name']?:'Vacation Brain')?>"></label></div><label>Description<textarea class="input" name="description" rows="3"><?=e($settings['pwa.description'])?></textarea></label><div class="form-grid"><label>Theme color<input class="input" type="color" name="theme_color" value="<?=e($settings['pwa.theme_color']?:'#ffffff')?>"></label><label>Background color<input class="input" type="color" name="background_color" value="<?=e($settings['pwa.background_color']?:'#ffffff')?>"></label><label>Display<select class="input" name="display"><?php foreach(['standalone','fullscreen','minimal-ui','browser'] as $d):?><option value="<?=$d?>" <?=($settings['pwa.display']?:'standalone')===$d?'selected':''?>><?=$d?></option><?php endforeach;?></select></label></div><div class="pwa-upload-grid"><div><?php if($settings['pwa.icon_url']):?><img class="pwa-icon-preview" src="<?=e($settings['pwa.icon_url'])?>" alt="App icon"><?php endif;?><label>App icon<input class="input" type="file" name="app_icon" accept="image/jpeg,image/png,image/webp"></label><?php if($settings['pwa.icon_url']):?><label class="check-row"><input type="checkbox" name="remove_icon"> Remove icon</label><?php endif;?></div><div><?php if($settings['pwa.splash_url']):?><img class="pwa-splash-preview" src="<?=e($settings['pwa.splash_url'])?>" alt="Splash screen"><?php endif;?><label>Splash screen<input class="input" type="file" name="splash_screen" accept="image/jpeg,image/png,image/webp"></label><?php if($settings['pwa.splash_url']):?><label class="check-row"><input type="checkbox" name="remove_splash"> Remove splash</label><?php endif;?></div></div></div><button class="button primary" type="submit">Save Brand & PWA Settings</button></form></div></section>
<?php require __DIR__.'/../partials/footer.php'; ?>
