<?php
require __DIR__.'/../app/bootstrap.php';
$adminId=require_admin();$pdo=db();
if(!db_table_exists('destination_ai_jobs'))redirect('upgrade.php');
$service=new DestinationAiService($pdo,dirname(__DIR__));$error=null;$success=flash('success');
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        $result=$service->create($adminId,$_POST);
        $message='Destination created with AI: destination #'.(int)$result['destination_id'].'. '.count($result['images']).' destination images created.';
        if(!empty($result['warning']))$message.=' Image warning: '.$result['warning'];
        flash('success',$message);
        redirect('admin/destination-prompts.php?id='.(int)$result['destination_id'].'&created=1');
    }catch(Throwable $e){$error=$e->getMessage();}
}
$jobs=$pdo->query('SELECT j.*,d.name AS saved_name FROM destination_ai_jobs j LEFT JOIN destination_catalog d ON d.id=j.destination_catalog_id ORDER BY j.id DESC LIMIT 12')->fetchAll();
$openai=(new AiProviderService($pdo))->get('openai',false);$imageReady=$openai&&!empty($openai['enabled'])&&!empty($openai['has_key']);
$title='AI Create Destination — Admin';require __DIR__.'/../partials/header.php';
?>
<section class="dashboard"><div class="shell"><div class="dashboard-head"><div><div class="eyebrow">Admin · Destinations · AI</div><h1>Create a destination with AI</h1><p class="muted">Give Vacation Brain a destination name. The configured AI researches and fills the catalog profile, prompt vocabulary, suggested scenes and vibes, then OpenAI can create the reusable destination image set.</p></div><a class="button secondary small" href="<?=e(app_url('admin/destinations.php'))?>">← Destinations</a></div>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="admin-split"><form class="dashboard-card stack" method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><h2>AI destination brief</h2><label>Destination name<input class="input" name="destination_name" maxlength="255" required value="<?=e((string)($_POST['destination_name']??''))?>" placeholder="Cabo San Lucas"></label><label>Location hint <span class="muted small">optional</span><input class="input" name="location_hint" maxlength="500" value="<?=e((string)($_POST['location_hint']??''))?>" placeholder="Baja California Sur, Mexico"></label><label>Admin direction <span class="muted small">optional</span><textarea class="input" name="admin_notes" rows="5" maxlength="4000" placeholder="Emphasize beach resorts, marina, desert-ocean scenery, nightlife, and playful tourist energy."><?=e((string)($_POST['admin_notes']??''))?></textarea></label><label class="check-row"><input type="checkbox" name="generate_images" value="1" <?=!isset($_POST['generate_images'])||!empty($_POST['generate_images'])?'checked':''?>> Generate the standard destination image set</label><label class="check-row"><input type="checkbox" name="publish" value="1" <?=!empty($_POST['publish'])?'checked':''?>> Publish destination immediately after creation</label><button class="button primary" type="submit">Create Destination with AI</button><p class="microcopy">The text/profile step uses the configured default OpenAI or Claude provider with web research. Image generation uses the enabled OpenAI key and the configured destination image model. Generated destination images are labeled as AI-generated concepts.</p></form>
<div class="dashboard-card"><span class="eyebrow">Image engine</span><h2><?=$imageReady?'Ready to create images':'OpenAI image setup needed'?></h2><p class="muted"><?=$imageReady?'The standard set creates hero, card, landmark and lifestyle images.':'Destination text can still be generated with the configured chat provider, but image creation requires an enabled OpenAI key.'?></p><hr><h3>What AI fills</h3><div class="stack"><div class="info-card"><strong>Catalog copy</strong><p>Name, location fields, short/full descriptions, best-for and vibe.</p></div><div class="info-card"><strong>Prompt vocabulary</strong><p>Visuals, landmarks, environment, activities, wardrobe context, tourist boosts, humor and avoid rules.</p></div><div class="info-card"><strong>Scene library</strong><p>Six to ten image-ready scenes plus default vibe suggestions.</p></div><div class="info-card"><strong>Destination media</strong><p>Hero, card, landmark and lifestyle images saved into the destination gallery.</p></div></div></div></div>
<div class="dashboard-card" style="margin-top:24px"><h2>Recent AI destination jobs</h2><div class="table-wrap"><table class="admin-table"><thead><tr><th>Destination</th><th>Status</th><th>Images</th><th>Provider</th><th>Created</th><th></th></tr></thead><tbody><?php foreach($jobs as $job):?><tr><td><strong><?=e($job['saved_name']??$job['destination_name'])?></strong></td><td><?=e($job['status'])?></td><td><?=(int)$job['images_created']?> / <?=(int)$job['images_requested']?></td><td><?=e(trim((string)($job['provider']??'').' '.(string)($job['model_name']??'')))?></td><td><?=e((string)$job['created_at'])?></td><td><?php if(!empty($job['destination_catalog_id'])):?><a href="<?=e(app_url('admin/destination-prompts.php?id='.(int)$job['destination_catalog_id']))?>">Open</a><?php endif;?></td></tr><?php endforeach;?><?php if(!$jobs):?><tr><td colspan="6" class="muted">No AI destination jobs yet.</td></tr><?php endif;?></tbody></table></div></div>
</div></section>
<?php require __DIR__.'/../partials/footer.php';?>
