<?php
require __DIR__.'/../app/bootstrap.php';
$adminId=require_admin();$pdo=db();
if(!db_table_exists('destination_prompt_profiles'))redirect('upgrade.php');
$id=(int)($_GET['id']??$_POST['id']??0);if($id<1){flash('error','Choose a destination first.');redirect('admin/destinations.php');}
$service=new DestinationPromptService($pdo);$ai=new DestinationAiService($pdo,dirname(__DIR__));$error=null;$success=flash('success');
try{$profile=$service->get($id);}catch(Throwable){flash('error','Destination not found.');redirect('admin/destinations.php');}
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        $action=(string)($_POST['action']??'save');
        if($action==='regenerate_images'){$images=$ai->generateImages($id,$adminId);flash('success',count($images).' destination images regenerated.');redirect('admin/destination-prompts.php?id='.$id);}
        $profile=$service->save($id,$_POST,$adminId,'manual');flash('success','Destination prompt library saved.');redirect('admin/destination-prompts.php?id='.$id);
    }catch(Throwable $e){$error=$e->getMessage();$profile=$service->get($id);}
}
$destination=$profile['destination'];$gallery=[];if(db_table_exists('destination_gallery_images')){$stmt=$pdo->prepare('SELECT * FROM destination_gallery_images WHERE destination_catalog_id=? ORDER BY sort_order,id');$stmt->execute([$id]);$gallery=$stmt->fetchAll();}
$title='Destination Prompt Library — Admin';require __DIR__.'/../partials/header.php';
$fields=['visual_keywords'=>'Visual vocabulary','landmark_keywords'=>'Landmark / place cues','environment_keywords'=>'Environment cues','activity_keywords'=>'Activities','wardrobe_keywords'=>'Wardrobe context','tourist_boost_keywords'=>'Tourist boost vocabulary','humor_keywords'=>'Humor / visual comedy','avoid_keywords'=>'Avoid / negative cues','default_scenes'=>'Suggested scenes','default_vibes'=>'Default vibes'];
?>
<section class="dashboard"><div class="shell"><div class="dashboard-head"><div><div class="eyebrow">Admin · Destination Prompt Library</div><h1><?=e($destination['name'])?></h1><p class="muted">This vocabulary is injected between the user identity references and the user’s comprehensive Vacation Brain prompt profile. Keep it destination-specific; the user profile decides which pieces matter for each image.</p></div><div style="display:flex;gap:8px;flex-wrap:wrap"><a class="button secondary small" href="<?=e(app_url('admin/destinations.php?edit='.$id))?>">Edit destination</a><a class="button secondary small" href="<?=e(app_url('destination-report.php?destination_id='.$id))?>">View report</a></div></div>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="admin-split"><form class="dashboard-card stack" method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="save"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><span class="eyebrow">Prompt profile</span><h2>Destination vocabulary</h2></div><span class="badge"><?=e(ucfirst((string)$profile['source_mode']))?></span></div><label>Prompt summary<textarea class="input" name="prompt_summary" rows="5" maxlength="4000"><?=e((string)$profile['prompt_summary'])?></textarea></label><?php foreach($fields as $field=>$label):?><label><?=$label?><textarea class="input" name="<?=$field?>" rows="5" placeholder="One item per line"><?=e($service->formValue($profile,$field))?></textarea></label><?php endforeach;?><button class="button primary" type="submit">Save Prompt Library</button></form>
<div><article class="dashboard-card"><span class="eyebrow">How it composes</span><h2>Destination + user</h2><p class="muted">Vacation Brain does not use this as one giant static prompt. It combines a coherent subset with the user’s diagnosis answers, learned traits, recent choices, Dream Trips, scene selection, vibe and Over the Top strength.</p><div class="stack"><div class="info-card"><strong>1 · Identity</strong><p>User-selected reference photos control appearance.</p></div><div class="info-card"><strong>2 · Destination</strong><p>This library supplies authentic place vocabulary and scene options.</p></div><div class="info-card"><strong>3 · Vacation Brain profile</strong><p>All diagnosis answers and accumulated preferences personalize what happens there.</p></div><div class="info-card"><strong>4 · Strength</strong><p>0–100 controls how exaggerated the vacation production becomes.</p></div></div></article>
<article class="dashboard-card" style="margin-top:20px"><span class="eyebrow">Destination media</span><h2>AI image set</h2><p class="muted">Regenerate the standard hero, card, landmark and lifestyle concepts from the current prompt library.</p><form method="post" onsubmit="return confirm('Regenerate the AI destination image set? Existing AI images for these roles will be replaced.')"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="regenerate_images"><button class="button secondary" type="submit">Regenerate Destination Images</button></form><?php if($gallery):?><div class="destination-report-gallery" style="margin-top:16px"><?php foreach($gallery as $img):?><figure><img src="<?=e($img['image_url'])?>" alt="<?=e($img['caption']??'Destination image')?>" loading="lazy"><figcaption><strong><?=e(ucwords(str_replace('_',' ',(string)($img['image_role']??'gallery'))))?></strong><br><?=e((string)($img['caption']??''))?><?php if(!empty($img['is_ai_generated'])):?><br><small>AI-generated concept</small><?php endif;?></figcaption></figure><?php endforeach;?></div><?php endif;?></article></div></div>
</div></section>
<?php require __DIR__.'/../partials/footer.php';?>
