<?php
require __DIR__.'/../app/bootstrap.php';$adminId=require_admin();$pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{
    $name=trim((string)$_POST['name']);$type=trim((string)$_POST['place_type']);$city=trim((string)$_POST['city']);
    if($name===''||$city==='')throw new InvalidArgumentException('Name and city are required.');
    $stmt=$pdo->prepare('INSERT INTO places (name,place_type,description,address,city,region,country,website_url,booking_url,price_level,active,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?,1,?)');
    $stmt->execute([$name,$type?:'activity',trim((string)($_POST['description']??''))?:null,trim((string)($_POST['address']??''))?:null,$city,trim((string)($_POST['region']??''))?:null,trim((string)($_POST['country']??'United States')),trim((string)($_POST['website_url']??''))?:null,trim((string)($_POST['booking_url']??''))?:null,(int)($_POST['price_level']??0)?:null,json_encode(['source'=>'admin'],JSON_UNESCAPED_SLASHES)]);
    $placeId=(int)$pdo->lastInsertId();$tags=array_filter(array_map('trim',explode(',',(string)($_POST['tags']??''))));
    $find=$pdo->prepare('SELECT id FROM tags WHERE slug=?');$create=$pdo->prepare('INSERT INTO tags (slug,name,tag_group) VALUES (?,? ,"local_place")');$link=$pdo->prepare('INSERT IGNORE INTO place_tags (place_id,tag_id,weight) VALUES (?,?,1)');
    foreach($tags as $tag){$slug=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$tag),'-'));if($slug==='')continue;$find->execute([$slug]);$tid=$find->fetchColumn();if(!$tid){$create->execute([$slug,ucwords(str_replace('-',' ',$slug))]);$tid=$pdo->lastInsertId();}$link->execute([$placeId,$tid]);}
    flash('success','Local place added and available to matching Vacation Substitutions.');redirect('admin/places.php');
}catch(Throwable $e){flash('error',$e->getMessage());redirect('admin/places.php');}}
$places=$pdo->query('SELECT p.*,GROUP_CONCAT(t.slug ORDER BY t.slug SEPARATOR ", ") tags FROM places p LEFT JOIN place_tags pt ON pt.place_id=p.id LEFT JOIN tags t ON t.id=pt.tag_id GROUP BY p.id ORDER BY p.created_at DESC LIMIT 100')->fetchAll();$success=flash('success');$error=flash('error');$title='Local Places — Vacation Brain';require __DIR__.'/../partials/header.php';
?>
<section class="dashboard"><div class="shell"><div class="dashboard-head"><div><div class="eyebrow">Admin · Local Guide</div><h1>Local places</h1><p class="muted">Tag places so Vacation Substitutions can match them to itinerary steps.</p></div><a class="button secondary small" href="<?=e(app_url('admin/index.php'))?>">Admin home</a></div><?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="admin-two"><article class="dashboard-card"><h2>Add place</h2><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Type</label><select name="place_type"><option>restaurant</option><option>bar</option><option>hotel</option><option>pool</option><option>spa</option><option>museum</option><option>attraction</option><option>tour</option><option>shop</option><option>activity</option><option>park</option><option>resort</option></select></div><div class="field"><label>City</label><input name="city" required></div><div class="field"><label>State / region</label><input name="region"></div><div class="field"><label>Address</label><input name="address"></div><div class="field"><label>Website</label><input name="website_url" type="url"></div><div class="field"><label>Booking URL</label><input name="booking_url" type="url"></div><div class="field"><label>Price level</label><select name="price_level"><option value="">Unknown</option><option value="1">$</option><option value="2">$$</option><option value="3">$$$</option><option value="4">$$$$</option></select></div><div class="field"><label>Tags, comma separated</label><input name="tags" placeholder="food, pool, spa, nightlife, local"></div><div class="field"><label>Description</label><textarea name="description"></textarea></div><button class="button primary">Add local place</button></form></article>
<article class="dashboard-card"><h2>Matching vocabulary</h2><p class="muted">The launch substitution templates already use tags such as:</p><div class="score-chips"><span>food</span><span>pool</span><span>local</span><span>shopping</span><span>nightlife</span><span>hotel</span><span>relaxation</span><span>spa</span><span>culture</span><span>luxury</span></div><p class="muted">A place can carry several tags. Matching prefers places that satisfy the most tags for each itinerary step.</p></article></div>
<article class="dashboard-card" style="margin-top:20px"><h2>Current places</h2><div class="table-wrap"><table class="admin-table"><thead><tr><th>Name</th><th>City</th><th>Type</th><th>Tags</th></tr></thead><tbody><?php foreach($places as $p):?><tr><td><?=e($p['name'])?><?php if(!empty($p['is_sample'])):?><br><span class="sample-badge">Sample</span><?php endif;?></td><td><?=e($p['city'])?><?= $p['region']?', '.e($p['region']):''?></td><td><?=e($p['place_type'])?></td><td><?=e($p['tags']??'')?></td></tr><?php endforeach;?></tbody></table></div></article>
</div></section><?php require __DIR__.'/../partials/footer.php';?>
