<?php
require __DIR__.'/../app/bootstrap.php';$adminId=require_admin();$pdo=db();$service=new ContentFactoryService($pdo);
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$id=(int)($_POST['candidate_id']??0);try{$action=(string)($_POST['action']??'');if($action==='publish'){$service->publish($id,$adminId);flash('success','Candidate published to the master content library.');}elseif(in_array($action,['approve','reject','edit'],true)){$service->review($id,$adminId,$action,(string)($_POST['notes']??''),$_POST['edited_json']??null);flash('success','Review saved.');}redirect('admin/review-content.php');}catch(Throwable $e){flash('error',$e->getMessage());redirect('admin/review-content.php?candidate='.$id);}}
$selected=(int)($_GET['candidate']??0);$where=$selected?'WHERE c.id='.(int)$selected:'WHERE c.status IN ("needs_review","approved")';
$rows=$pdo->query('SELECT c.*,j.content_type AS job_type,j.id AS generation_job_id FROM ai_generated_candidates c JOIN ai_generation_jobs j ON j.id=c.job_id '.$where.' ORDER BY CASE c.status WHEN "needs_review" THEN 0 ELSE 1 END,c.quality_score DESC,c.id LIMIT 50')->fetchAll();
$success=flash('success');$error=flash('error');$title='Review Content — Vacation Brain';require __DIR__.'/../partials/header.php';
?>
<section class="dashboard"><div class="shell"><div class="dashboard-head"><div><div class="eyebrow">Admin · Review</div><h1>Candidate review queue</h1><p class="muted">Nothing AI-generated becomes public until it is reviewed and published.</p></div><a class="button secondary small" href="<?=e(app_url('admin/ai-content.php'))?>">Content Factory</a></div><?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(!$rows):?><div class="dashboard-card center"><h2>Review queue is clear.</h2><p class="muted">Create a generation job and import candidates when you are ready.</p></div><?php endif;?>
<div class="review-stack"><?php foreach($rows as $row):$data=json_decode((string)$row['generated_json'],true)?:[];?><article class="review-card"><div class="review-head"><div><span class="status-pill"><?=e($row['status'])?></span><span class="muted small">Job #<?=(int)$row['generation_job_id']?> · <?=e($row['content_type'])?></span></div><span class="muted small">Candidate #<?=(int)$row['id']?></span></div><h2><?=e($data['title']??$data['name']??'Untitled candidate')?></h2><p><?=e($data['body']??$data['question']??$data['text']??$data['description']??'')?></p>
<?php if(!empty($data['choices'])):?><div class="candidate-choices"><?php foreach($data['choices'] as $choice):?><div><?=e($choice['label']??'')?></div><?php endforeach;?></div><?php endif;?>
<div class="score-chips"><?php foreach(['quality_score'=>'Quality','originality_score'=>'Originality','humor_score'=>'Humor','brand_fit_score'=>'Brand'] as $key=>$label):if($row[$key]!==null):?><span><?=$label?> <?=e((string)$row[$key])?></span><?php endif;endforeach;?></div>
<details><summary>Edit/review JSON</summary><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="candidate_id" value="<?=(int)$row['id']?>"><div class="field"><textarea class="code-area" name="edited_json"><?=e(json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?></textarea></div><div class="field"><input name="notes" placeholder="Review notes"></div><div class="review-actions"><button class="button secondary small" name="action" value="edit">Save edit</button><button class="button secondary small" name="action" value="reject">Reject</button><button class="button secondary small" name="action" value="approve">Approve</button><button class="button primary small" name="action" value="publish">Publish</button></div></form></details></article><?php endforeach;?></div>
</div></section><?php require __DIR__.'/../partials/footer.php';?>
