<?php
require __DIR__.'/../app/bootstrap.php';
$adminId=require_admin();$pdo=db();$service=new TravelProviderSettingsService($pdo);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();try{$provider=(string)($_POST['provider']??'');$action=(string)($_POST['action']??'save');if($action==='save'){$service->save($provider,$_POST,$adminId);flash('success','Travel provider settings saved.');}elseif($action==='test'){$service->save($provider,$_POST,$adminId);$result=$service->test($provider,$adminId);flash($result['success']?'success':'error',(string)$result['message']);}elseif($action==='clear'){$service->clearKey($provider,$adminId);flash('success','Saved provider credential removed. Config/environment fallback remains available if configured.');}else throw new InvalidArgumentException('Unknown provider action.');redirect('admin/travel-providers.php');}catch(Throwable $e){$error=$e->getMessage();}
}
$providers=$service->all();$success=flash('success');$flashError=flash('error');$usage=[];
if($service->ready()){try{$q=$pdo->query("SELECT provider,COUNT(*) requests,SUM(success=1) successes,SUM(success=0) failures,ROUND(AVG(latency_ms)) avg_latency,MAX(created_at) last_used FROM travel_provider_usage_log WHERE created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY provider");foreach($q->fetchAll()?:[] as $r)$usage[(string)$r['provider']]=$r;}catch(Throwable $e){error_log('Travel provider usage stats failed: '.$e->getMessage());}}
$title='Travel Providers — Vacation Brain';$pageStyles=['assets/travel-providers.css'];require __DIR__.'/../partials/header.php';
?>
<section class="dashboard vb-provider-admin"><div class="shell">
<div class="dashboard-head"><div><span class="eyebrow">Admin · Live travel</span><h1>Travel Providers</h1><p class="muted">Connect live weather, flight status, airfare, lodging, events and local-place sources without putting credentials in browser code.</p></div><a class="button secondary small" href="<?=e(app_url('admin/index.php'))?>">Admin home</a></div>
<?php if(!$service->ready()):?><div class="alert warning"><strong>Migration 046 / app v1.38 is required.</strong> <a href="<?=e(app_url('upgrade.php'))?>">Run System Upgrade →</a></div><?php endif;?><?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($flashError):?><div class="alert error"><?=e($flashError)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<div class="vb-provider-security"><strong>Server-side credentials only.</strong><span>Saved API keys are AES-256-GCM encrypted using the same application key boundary as AI provider credentials. Vacation Brain never renders the saved secret back into HTML.</span></div>
<div class="vb-provider-grid">
<?php foreach($providers as $p):$provider=(string)$p['provider'];$u=$usage[$provider]??null;$settings=$p['settings']??[];?>
<form method="post" class="dashboard-card vb-provider-card">
<input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="provider" value="<?=e($provider)?>">
<div class="vb-provider-top"><div><span class="eyebrow"><?=e(ucwords((string)$p['capability']))?></span><h2><?=e((string)$p['display_name'])?></h2></div><span class="vb-provider-test <?=e((string)($p['last_test_status']??'never'))?>"><?=e(ucfirst((string)($p['last_test_status']??'never')))?></span></div>
<div class="vb-provider-meta"><span>Credential <b><?=e((string)($p['credential_source']??'none'))?></b></span><span>Configured <b><?=!empty($p['configured'])?'Yes':'No'?></b></span><span>Priority <b><?=(int)($p['priority']??100)?></b></span></div>
<label class="vb-provider-toggle"><input type="checkbox" name="enabled" value="1" <?=!empty($p['enabled'])?'checked':''?>> Enable saved credential</label>
<label>API token / key<input class="input" type="password" name="api_key" autocomplete="new-password" placeholder="<?=e(!empty($p['masked_key'])?(string)$p['masked_key']:'Leave blank to keep current / use config fallback')?>"></label>
<label>Priority<input class="input" type="number" name="priority" min="1" max="999" value="<?=(int)($p['priority']??100)?>"></label>
<?php if($provider==='booking_com'):?><div class="vb-provider-subgrid"><label>Affiliate ID<input class="input" name="affiliate_id" maxlength="40" value="<?=e((string)($settings['affiliate_id']??''))?>" required></label><label>Booker country<input class="input" name="booker_country" maxlength="2" value="<?=e((string)($settings['booker_country']??'us'))?>"></label><label>Platform<select class="input" name="platform"><?php foreach(['desktop','mobile','tablet'] as $v):?><option value="<?=$v?>" <?=($settings['platform']??'desktop')===$v?'selected':''?>><?=e(ucfirst($v))?></option><?php endforeach;?></select></label><label>Environment<select class="input" name="environment"><option value="production" <?=($settings['environment']??'production')==='production'?'selected':''?>>Production</option><option value="sandbox" <?=($settings['environment']??'')==='sandbox'?'selected':''?>>Sandbox</option></select></label></div><?php endif;?>
<?php if($provider==='aviationstack'):?><p class="vb-provider-note">Used only for operational status of flights users have recorded as booked. Production commercial use requires an appropriate provider plan.</p><?php elseif($provider==='skyscanner'):?><p class="vb-provider-note">Indicative airfare intelligence only; Vacation Brain does not treat these estimates as confirmed or bookable fares.</p><?php elseif($provider==='booking_com'):?><p class="vb-provider-note">Search/look/redirect integration. Vacation Brain stores live snapshots but does not create a Booking.com reservation in this phase.</p><?php endif;?>
<div class="vb-provider-usage"><?php if($u):?><span><b><?=(int)$u['requests']?></b> requests · 30d</span><span><b><?=(int)$u['failures']?></b> failures</span><span><b><?=e((string)($u['avg_latency']??'—'))?></b> ms avg</span><?php else:?><span>No recorded calls in the last 30 days.</span><?php endif;?></div>
<?php if(!empty($p['last_error'])):?><div class="vb-provider-error"><?=e((string)$p['last_error'])?></div><?php endif;?>
<div class="vb-provider-actions"><button class="button primary small" type="submit" name="action" value="save">Save</button><button class="button secondary small" type="submit" name="action" value="test">Save & test</button><?php if(!empty($p['has_saved_key'])):?><button class="button secondary small" type="submit" name="action" value="clear" formnovalidate>Remove saved key</button><?php endif;?></div>
</form><?php endforeach;?>
</div>
<div class="dashboard-card vb-provider-operating"><h2>How Vacation Brain chooses data</h2><p>Admin-saved enabled credentials take precedence. Existing <code>config.php</code> / environment keys remain a backward-compatible fallback, so upgrading does not silently switch off providers that are already running. Provider failures are isolated by data type and saved with freshness/error state instead of breaking the trip dashboard.</p></div>
</div></section>
<?php require __DIR__.'/../partials/footer.php';?>
